### ISSUE TITLE
Real-time Live Trading with Great Charts

### ISSUE THREAD

**Issue by Sorcerysoft** [kernc/backtesting.py#100]
Backtesting.py has the best charting I've seen in a python trading project! I've been looking for something with similar zoom/pan/indicator/multi-timeframe features that Tradingview.com or NinjaTrader have. 

Can you suggest a live trading python open source project that has these charting features?

Can you recommend other live trading frameworks/libraries that I could drop in a Backtesting.py custom Strategy with minimal changes?

Thanks!

**Comment by kernc** [comment]
Thank you for the kind words. With [alternatives list](https://github.com/kernc/backtesting.py#alternatives) fairly recent and updated, I'm not aware of any similar/matching frameworks at present.

Please subscribe issue https://github.com/kernc/backtesting.py/issues/81 (duplicate) for updates.
