### ISSUE TITLE
Converting heatmap series to dataframe

### ISSUE THREAD

**Issue by riodda** [kernc/backtesting.py#101]
### Expected Behavior
stats should be a dataframe with all the parameters and all the results with properly named columns

### Actual Behavior
stats is pandas series of different lenght, and the optimizing paramenter(in the example Equity) is missing label.

### Steps to Reproduce

1. Do a strategy optimization
2.
3.

### Additional info
I think that the the heatmap should be a full pandas dataframe with properly named columns and with run number as index. Currently it's quite tricky to get the best parameters for a simulation with aloto of paramers, haveing a proper dataframe as heatmap would really help.

- Backtesting version:
Latest

**Comment by kernc** [comment]
> stats is pandas series of different lenght, and the optimizing paramenter(in the example Equity) is missing label

Can you show an example of an inadequate and a proposed adequate result? Not sure I get it.

When `Backtest.optimize(..., return_heatmap=True)`, [as per docs, a tuple of two series is returned](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.optimize):
```py
stats, heatmap = bt.optimize(..., return_heatmap=True)
```

You can easily [convert a pandas series to a dataframe](https://www.google.com/search?q=pandas+series+to+frame):
```py
heatmap = heatmap.to_frame()
```

**Comment by riodda** [comment]
The scenario is that i run an iteration to find the best parameters for a strategy, currently if i convert heatmap to frame i have a dataframe with an uneven number of rows between the params and also the target of the optimization column is label less. this format of dataframe makes difficould (At least for me) to get immediately the best params of the optimization runs.
For example in the image attached thersold_buy is 2 items, thersold_sell is 4 items, thersold_long_close is 7 items etc. Also as you can see the equity column also is label less.
![Immagine](https://user-images.githubusercontent.com/13453063/87054058-fab35000-c202-11ea-97a8-f6d4980ede72.png)

My workaround is to use stats._strategy convert into a string and decompose to get the params,

`best_params = str(stats._strategy)
best_params_array=best_params[17:-2].split(',')
parameters = []    
for parameter in best_params_array:
        parameters.append(parameter.split('='))
    pars = pd.DataFrame(parameters,columns=['Parameter',ticker])`

But if the dataframe will be output with a consistent number of rows for each columns (in bold what is now missing):

param1 param2 param3 **target**
0            3           6            1200
**0**            **3**            7           1300

Will make much easier to get the best params (or the worst, or the average) as the target columns is labelled and each column has the same number of rows.
Then my python is not really great therfore i might miss the way to get the best params.
Thanks for your hardwork.

**Comment by kernc** [comment]
> Then my python is not really great therfore i might miss the way to get the best params.

Again, to get a frame, have you tried running:
```py
heatmap = heatmap.to_frame('My Equity')
```
?

One simple way to get _the best_ combinations is to run:
```py
heatmap.sort_values()
```

-----
Indeed, assigning `heatmap` a `name=maximize if isinstance(maximize, str) else None` might be the default. :+1: 
https://github.com/kernc/backtesting.py/blob/0739f4b2430d003d28f9b6960c2cc0820aa1e4ef/backtesting/backtesting.py#L816-L818

-----

Additionally, `stats._strategy` is a strategy instance. You can query its attributes directly, e.g.
```py
>>> stats._strategy.thersold_buy
2
```

**Comment by riodda** [comment]
> ```python
> heatmap = heatmap.to_frame('My Equity')
> ```
Yes i did, and the dataframe that is output has different row numbers between columns.

```
heatmap.sort_values()
Traceback (most recent call last):

  File "<ipython-input-36-221809f51301>", line 1, in <module>
    heatmap.sort_values()

TypeError: sort_values() missing 1 required positional argument: 'by'
```
here comes my lack of python knowledge 'by' the column i want to sort for has no name....

Regarding the method of using `stats._strategy.thersold_buy` i forgot that the optimize reruns the strategy with the best values (but it's a method that is rigid with the parameter names).

Many thanks for your help.

**Comment by kernc** [comment]
>
```
TypeError: sort_values() missing 1 required positional argument: 'by'
```

This should work on initial `heatmap` multiindex series as returned by `.optimize()`, i.e. _before_ `.to_frame()`. (After `.to_frame()`, you need to specify a df column, e.g. `'My Equity'` passed to [`to_frame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.to_frame.html). All df columns have names.)

**Comment by kernc** [comment]
Ok, having run it, I understand. Merely:
```py
heatmap.to_frame()
```
retains the [MultiIndex](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html).

Instead try:
```py
heatmap.reset_index(name='Equity')
```
![Screenshot_2020-07-15_15-38-10](https://user-images.githubusercontent.com/684364/87551903-46f20a80-c6b1-11ea-8062-c53ada1cdec8.png)

**Comment by PilotGFX** [comment]
example: 
optiheatmap_df = optiheatmap.to_frame(name='Result').reset_index().sort_values(by="Result",ascending=False)
