### ISSUE TITLE
How to change it to run to a dIfferent stock other than GOOG?

### ISSUE THREAD

**Issue by josyjr25** [kernc/backtesting.py#1040]
### Steps to Reproduce

1.
2.
3.

```python

python code goes here

```

### Additional info

- Backtesting version: 0.?.?   
- `bokeh.__version__`:
- OS:

**Comment by eervin123** [comment]
just download a dataframe of a stock or asset. Here is a simple colab notebook showing you how to do it with `yfinance` though I highly recommend spending some time on youtube watching some tutorials. They will help with the learning curve. I posted several good youtube tutorials in the discussion forum a while back. Hopefully you can find them easily. 

screenshot for downloading data

<img width="847" alt="image" src="https://github.com/kernc/backtesting.py/assets/32274861/6bf984f8-af19-4b4f-ae5d-fad78a35ad13">

Notebook here
https://colab.research.google.com/drive/1R1PwVESGQ5fuUNr1eaAQJVJ8hP_gBOKz?usp=sharing

**Comment by kernc** [comment]
> I posted several good youtube tutorials in the discussion forum a while back. Hopefully you can find them easily.

They're here: https://github.com/kernc/backtesting.py/discussions/677

**Comment by eervin123** [comment]
@josyjr25 there is gold in those tutorials. You absolutely started with the right backtesting library out there. It is simple and straightforward, it is blazing fast and the community is pretty darn friendly.
