### ISSUE TITLE
How to trade at Open /High/ Low / Close of the next candle

### ISSUE THREAD

**Issue by sangramht** [kernc/backtesting.py#105]
How to add Alteration of Entry/Exit Points.(Instead of Entry at close I want entry be based on next candle's Open/High/Low/Close)

**Comment by kernc** [comment]
By default, the trade is entered on _next_ candlebar's _open_ price (think of it as placing a trade during the night when the exchange is closed). If you run [`Backtest(..., trade_on_close=True)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest), the trade will be entered on the _current_ bar's _closing_ price (think of it as placing the order a few seconds before the exchange closes).

If you place a _limit order_, the order will be executed when the price eventually reaches the _exact set price level_ (e.g. when it dives to its next day's _low_ price).

Does that answer your question?

**Comment by sangramht** [comment]
> By default, the trade is entered on _next_ candlebar's _open_ price (think of it as placing a trade during the night when the exchange is closed). If you run [`Backtest(..., trade_on_close=True)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest), the trade will be entered on the _current_ bar's _closing_ price (think of it as placing the order a few seconds before the exchange closes).
> 
> If you place a _limit order_, the order will be executed when the price eventually reaches the _exact set price level_ (e.g. when it dives to its next day's _low_ price).
> 
> Does that answer your question?
Yes it somewhat does, but what if I want to enter on next bars High ?

**Comment by kernc** [comment]
Then you have to wait for or checkout #47 and set `stop=` price there. :sweat_smile:

**Comment by kernc** [comment]
With #47 merged and v0.2.0 released, you can use `Strategy.buy(..., stop=stop_price)` to issue a stop-market order, entering trade on "next bar's High". :+1:
