### ISSUE TITLE
How can I specify order size?

### ISSUE THREAD

**Issue by sangramht** [kernc/backtesting.py#108]
New to backtesting Please help!

How do I specify these parameters 
1 - contract size For example 100000
2 - lot size say 2
3 - margin say 2150 

Also the newly added size parameter, is it same as the above mentioned size namely  contract size or lot size??

**Comment by kernc** [comment]
Did you try to find answers in the documentation?

From [`Strategy.buy()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.buy) and [`Order.size`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Order.size):
> A value greater than or equal to 1 indicates an absolute number of units.

From [`Backtest`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest):
> `margin` is the required margin (ratio) of a leveraged account. [...] To run the backtest using e.g. 50:1 leverge [...], set margin to 0.02 (1 / leverage).

**Comment by sangramht** [comment]
I went through the documentation but couldnt understand a way to set the contract size as well as lot size

**Comment by kernc** [comment]
Backtesting.py only accepts a `size=` parameter, i.e. an _absolute number of units_. E.g. `size=100_000`, one standard lot.

I'm afraid much more will be required to devise profitable strategies in Python. :sweat_smile:

**Comment by sangramht** [comment]
Ok so if the cash_value/start cash is set to 10000 can the size be 100_000

**Comment by kernc** [comment]
It can if the price is <= .1 or if margin is set to <= .1 ...
