### ISSUE TITLE
passing date value format for the data-series

### ISSUE THREAD

**Issue by packandsell** [kernc/backtesting.py#11]
May I ask, what's the best way to pass the Date to the trading system to make it recognize it correctly? This one I'm working with is dealing with US format, so first it goes month, then the day. Also I can combine the time string to that by removing the comma. I may have relied on the auto-detect date format feature, but it may be obscure for the dates where month and day integer are the same, so I'd prefer to pass this format explicitly. Can you advise pls?

US format: mm/dd/yyyy 24h
09/12/2016,08:00:00

Technically I'll have something like this
`dt = np.genfromtxt(filename, delimiter=',', encoding="utf-8", dtype=str, skip_header=True, usecols = (fDate_col, fTime_col))`

**Comment by kernc** [comment]
Why not use [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) to read data. It's much faster, more versatile, intuitive, and easy to use.

Something like:
```py
import pandas as pd
df = pd.read_csv(filename, parse_dates=True, infer_datetime_format=True)
```
