### ISSUE TITLE
Would be nice to have an easy-to-access way of getting the plotted graph's filename

### ISSUE THREAD

**Issue by tankorsmash** [kernc/backtesting.py#114]
### Expected Behavior
Access filename for `bt.plot()`'s output HTML file, maybe something like `plot_filename = bt.plot(..)`, but that seems too specific a thing to return, and the inner `plot()` call just returns a bokeh `Row`.

### Actual Behavior

Have to use bokeh's `curstate()` instead.

```python
from bokeh.io.state import curstate #for getting html output path
bt.plot(open_browser=False)
html_filename = curstate().file.get('filename', '') #only available after plot() above
```

I'm not all that familiar with bokeh so I'm not sure at how stable or safe this is to access.

### Steps to Reproduce

```python
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

from backtesting.test import SMA, GOOG


class SmaCross(Strategy):
    n1 = 10
    n2 = 20

    def init(self):
        self.sma1 = self.I(SMA, self.data.Close, self.n1)
        self.sma2 = self.I(SMA, self.data.Close, self.n2)

    def next(self):
        if crossover(self.sma1, self.sma2):
            self.buy()
        elif crossover(self.sma2, self.sma1):
            self.sell()


bt = Backtest(GOOG, SmaCross, cash=10000,
              commission=.002, exclusive_orders=True)

output = bt.run()
bt.plot() #access plot's HTML filename here somehow

```

### Additional info

- Backtesting version:
0.2.0

**Comment by kernc** [comment]
:thinking: What about passing a known filename to [`Backtest.plot()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.plot):
```py
filename = 'my_strategy.html'
bt = Backtest(...)
bt.plot(filename=filename)
```

**Comment by tankorsmash** [comment]
That makes sense, didn't realize that was possible!
