### ISSUE TITLE
Attach date column when printing '_equity_curve`

### ISSUE THREAD

**Issue by ironhak** [kernc/backtesting.py#1148]
When you print the equity curve like this: 
```python
bt = Backtest(df,DonchainBreakout,cash=10_000, exclusive_orders= True)
stats = bt.run()
equity = stats['_equity_curve']
print(equity)
```
The result is this:
```
          Equity  DrawdownPct  DrawdownDuration
0    10000.00000      0.00000               NaN
1    10000.00000      0.00000               NaN
2    10000.00000      0.00000               NaN
3    10000.00000      0.00000               NaN
4    10000.00000      0.00000               NaN
```
And there are as many rows as the input dataframe. It would be a good practice to have also the date column inherited from the main dataframe on this equity dataframe.

**Comment by coder145** [comment]
Certainly! It seems like the key issue here is that your data lacks a "DateTimeIndex". As your equity curve has the same index as your data. just convert the date in your data to index and it should be fine.
