### ISSUE TITLE
Bid/Ask support for order execution

### ISSUE THREAD

**Issue by krishnacdunuka** [kernc/backtesting.py#115]
### Expected Behavior
Order buy/sell should be executed according to bid/ask price of Forex market data

### Actual Behavior
No bid/ask support

- Backtesting version:
0.2.0

**Comment by kernc** [comment]
Favor [modelling spread with `commission` rate](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest).
