### ISSUE TITLE
Stop loss based on entry price

### ISSUE THREAD

**Issue by rinkesh-ahuja** [kernc/backtesting.py#120]
The trade executed based on the RSI strategy is considering the stop-loss as a percentage of the recent closing price. The same with target price.
I want to create a stop-loss and target price based on the entry price. I tried to do it by inserting the position.close function after the buy order is fulfilled. 
I know the variable `entry_price` is in the `Trade` class. I am quite unsure about it. 
Sorry! I am a complete beginner.

**Comment by kernc** [comment]
A code such as the following will set the trade stop-loss price (via [`Trade.sl`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Trade.sl)) to be 5% below entry price on long trades:
```py
class MyStrategy(Strategy):
    def next(self):
        ...
        for trade in self.trades:
            if trade.is_long and not trade.sl:  # Only long and skip already set
                trade.sl = .95 * trade.entry_price
```

**Comment by rinkesh-ahuja** [comment]
Thank you for such a quick response. I added the above-mentioned code after `self.buy` command. But it gives me errors. **I have attached the error below.**

AttributeError                            Traceback (most recent call last)
<ipython-input-1-d2c92b7bdfeb> in <module>
     60 
     61 
---> 62 backtest.run()

~\anaconda3\lib\site-packages\backtesting\backtesting.py in run(self, **kwargs)
    720 
    721                 # Next tick, a moment before bar close
--> 722                 strategy.next()
    723 
    724         self._results = self._compute_stats(broker, strategy)

<ipython-input-1-d2c92b7bdfeb> in next(self)
     46             self.buy(tp = price * 1.08)
     47 
---> 48         for trade in self.trades:
     49             if trade.is_long and not trade.sl:  # Only long and skip already set
     50                 trade.sl = .95 * trade.entry_price

AttributeError: 'System' object has no attribute 'trades'

**Comment by kernc** [comment]
Strategy has a list of active [`.trades`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.trades). Please ensure you have the latest version installed:
```
pip install -U backtesting
```

**Comment by rinkesh-ahuja** [comment]
It worked. Thank you so much! 
I also added `trade.tp` the same way. I can't thank you enough.

**Comment by kernc** [comment]
Glad you solved it. Note, setting SL this way, you are holding the asset for at least one full bar (`self.buy()` places order at time _t_ while the order is executed into a trade and the trade's SL is set at time _t+1_).
