### ISSUE TITLE
‘cp950’ Error when using ‘pip install’

### ISSUE THREAD

**Issue by yaotechuang** [kernc/backtesting.py#121]
### Expected Behavior
pip install backtesting 

### Actual Behavior
 UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 4435: illegal multibyte sequence

### Steps to Reproduce

1.
2.
3.

### Additional info

- Backtesting version:

**Comment by kernc** [comment]
It would likely help to see the full traceback. Can you post it?

**Comment by yaotechuang** [comment]
Collecting backtesting
  Using cached Backtesting-0.2.0.tar.gz (170 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\YAOTEC~1\\AppData\\Local\\Temp\\pip-install-blgpa7ca\\backtesting\\setup.py'"'"'; __file__='"'"'C:\\Users\\YAOTEC~1\\AppData\\Local\\Temp\\pip-install-blgpa7ca\\backtesting\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\YAOTEC~1\AppData\Local\Temp\pip-install-blgpa7ca\backtesting\pip-egg-info'
         cwd: C:\Users\YAOTEC~1\AppData\Local\Temp\pip-install-blgpa7ca\backtesting\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\YAOTEC~1\AppData\Local\Temp\pip-install-blgpa7ca\backtesting\setup.py", line 21, in <module>
        long_description=open(os.path.join(os.path.dirname(__file__), 'README.md')).read(),
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 4435: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by LemonCANDY42** [comment]
> ```
> Collecting backtesting
>   Using cached Backtesting-0.2.0.tar.gz (170 kB)
>     ERROR: Command errored out with exit status 1:
>      command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\YAOTEC~1\\AppData\\Local\\Temp\\pip-install-blgpa7ca\\backtesting\\setup.py'"'"'; __file__='"'"'C:\\Users\\YAOTEC~1\\AppData\\Local\\Temp\\pip-install-blgpa7ca\\backtesting\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\YAOTEC~1\AppData\Local\Temp\pip-install-blgpa7ca\backtesting\pip-egg-info'
>          cwd: C:\Users\YAOTEC~1\AppData\Local\Temp\pip-install-blgpa7ca\backtesting\
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\YAOTEC~1\AppData\Local\Temp\pip-install-blgpa7ca\backtesting\setup.py", line 21, in <module>
>         long_description=open(os.path.join(os.path.dirname(__file__), 'README.md')).read(),
>     UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 4435: illegal multibyte sequence
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ```

me too

**Comment by kernc** [comment]
@LemonCANDY42 Interesting, why are you "collecting v0.2.0" when [v0.3.3 is released](https://pypi.org/project/Backtesting/)?
