### ISSUE TITLE
Position open_time

### ISSUE THREAD

**Issue by TomaszLakota** [kernc/backtesting.py#122]
What happened to self.position.open_time? Is it possible to replace it?

**Comment by kernc** [comment]
The [advertised](https://github.com/kernc/backtesting.py/pull/47#issue-385367086) `Trade.entry_time` apparently fell out of the 0.2.0 release. :sweat_smile:

Was added afterwards in (duplicate) https://github.com/kernc/backtesting.py/issues/117, released as we speak.
