### ISSUE TITLE
How to use stop order to get into the trade ?

### ISSUE THREAD

**Issue by sdmiami** [kernc/backtesting.py#126]
### Expected Behavior
Based on the document I should be able to use stop order to get into the trade 

Based on the document we seems to have that feature 
https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Order.stop
var stop
Order stop price for stop-limit/stop-market order, otherwise None if no stop was set, or the stop price has already been hit.

### Actual Behavior
```text
\lib\site-packages\backtesting\backtesting.py", line 207, in buy    return self._broker.new_order(size, limit, stop, sl, tp)
lib\site-packages\backtesting\backtesting.py", line 697, in new_order    sl, limit or self.last_price, tp)
AssertionError: Long orders require: SL (X) < LIMIT (Y) < TP (Z)
```

### Steps to Reproduce
During self.buy use stop instead of limit, I was expecting it to work but getting error saying limit is require for long orders
self.buy(stop=value1,  sl=value2,  tp=value3)

### Additional info
If anyone have example of how to use stop-limit/stop market orders to get into the trade please share an example.

- Backtesting version: 0.2.0

**Comment by kernc** [comment]
> self.buy(stop=value1, sl=value2, tp=value3)
> AssertionError: Long orders require: SL (X) < LIMIT (Y) < TP (Z)

The assertion error you see is about passed `sl`, `limit` and `tp` values. In your case `sl` and `tp` values only, with `limit` defaulting to current market price.

That's as much I can say without seeing the full traceback, the code, or at least the particular values used.

**Comment by uberdeveloper** [comment]
@sdmiami Could you provide the actual values for sl,limit and trailing.
By default, it looks that the stop price should be less than the limit price and trailing price should be greater than the limit price for a BUY order

**Comment by sdmiami** [comment]
Below is the example

stop = 2998.75
sl = 2995.0
tp = 3007.5

AssertionError: Long orders require: SL (2995.0) < LIMIT (2985.0) < TP (3007.5)

The plan was to buy stop above red candle in the example, but the next candle didn't meet entry criteria, hence end up in an error.
![image](https://user-images.githubusercontent.com/36578278/89655943-d47fdf00-d898-11ea-92fc-5003a503d057.png)

**Comment by kernc** [comment]
There's even a todo item for it. :laughing: :sweat_smile: 

@sdmiami Does it maybe work correctly for you if you amend the assertions:
https://github.com/kernc/backtesting.py/blob/c8f9cc1e2e71aad5fbcb2fa2895ed4226d01c2d8/backtesting/backtesting.py#L705-L713
into:
```py
... (limit or stop or self.last_price) ...
```
Care to make a PR for it, along with a covering test case like yours?
