### ISSUE TITLE
Is the trailing strategy based on the current ATR or is it based on the ATR from the beginning of the trade? (question)

### ISSUE THREAD

**Issue by JanssensKobe** [kernc/backtesting.py#127]
Is the trailing strategy based on the current ATR or the ATR from the beginning of the trade?

**Comment by kernc** [comment]
Do you know any Python? Why not just look at the source? :stuck_out_tongue: 
https://github.com/kernc/backtesting.py/blob/c8f9cc1e2e71aad5fbcb2fa2895ed4226d01c2d8/backtesting/lib.py#L371-L383
https://github.com/kernc/backtesting.py/blob/c8f9cc1e2e71aad5fbcb2fa2895ed4226d01c2d8/backtesting/lib.py#L392-L400
Precomputing rolling ATR, the answer seems to be the former.
