### ISSUE TITLE
How to add slippage?

### ISSUE THREAD

**Issue by jiangjiu** [kernc/backtesting.py#128]
### Expected Behavior
https://www.backtrader.com/docu/slippage/slippage/

backtrader can set a slippage via percentage or fixed value like  0.01

### Actual Behavior
not a feature

thinking about this feature please？

**Comment by jiangjiu** [comment]
Slippage can greatly affect returns

**Comment by kernc** [comment]
Would something like this work?

```py
SPREAD = .0002
SLIPPAGE = .0001

...

bt = Backtest(..., commission=SPREAD + SLIPPAGE)
```

**Comment by jiangjiu** [comment]
good idea, well, commission can add this slippage percent，but can not set fixed value

**Comment by kernc** [comment]
Related issue https://github.com/kernc/backtesting.py/issues/113.

**Comment by ibaris** [comment]
How would be to add the a random variable during the `_process_orders` to simulate slippage? One would need 2 variables: 
- slippage range : Tuple[float, float] = Indicates the slippage range of the close price like [0.98, 1.03]. This would mean the price could range between 98% and 103%.
- slippage probability: float = A probability that a slippage will appear, e.g. 0.5 which says, that 50% of the time you experience a slippage. 

Here is the basic idea:
```python
import numpy as np

slippage_probability = 0.25
slippage_range = (0.98, 1.03)
close = 105

if np.random.rand() < slippage_probability:
    close *= np.random.uniform(slippage_range[0], slippage_range[1])
```
