### ISSUE TITLE
Is it possible to track custom stats in results? Is it possible to use tick data?

### ISSUE THREAD

**Issue by Dwyte** [kernc/backtesting.py#130]
I need a way, per trade to track the maximum profit it can have before it gets stopped out or before the market closes/week ends. Then at the end results I need to tally this property as well like what's the maximum "maximum profit" from all the trades. Is this possible within the library? Can I append custom data on each trade? Thanks, great repo btw!

Edit: Follow up question, is it possible to use tick data instead, then resample it to whatever timeframe I need? thanks!

**Comment by s-kust** [comment]
I try to pas custom data with trades like this
`trade.max_pl = max(getattr(trade, 'max_pl', -np.inf), trade.pl)`
but then I can't see it in `stats._trades.tail(20)` or `stats._strategy.closed_trades[-1]`

how to see my custom data (aka custom column) in trades after the backtest has run?

**Comment by kernc** [comment]
It won't, for the time being, automatically show in trades DataFrame nor in `Trade.__repr__`. You need to access it exactly the way it was set up:
```py
for trade in stats._strategy.closed_trades:
    this = trade.custom_data
    ...
```
E.g. to add it to the data frame:
```py
stats._trades.assign(custom_data=[t.custom_data for t in stats._strategy.closed_trades])
```
