### ISSUE TITLE
need help using backtesting

### ISSUE THREAD

**Issue by hussanirizvi2** [kernc/backtesting.py#131]
### Expected Behavior
run the test code on the site

### Actual Behavior
C:\Users\hrizvi\AppData\Local\Continuum\anaconda3\envs\python36\lib\site-packages\backtesting\_plotting.py:44: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support (e.g. PyCharm, Spyder IDE). Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '

### Steps to Reproduce
run program on spyder

from backtesting import Backtest, Strategy
from backtesting.lib import crossover

from backtesting.test import SMA, GOOG

class SmaCross(Strategy):
    def init(self):
        price = self.data.Close
        self.ma1 = self.I(SMA, price, 10)
        self.ma2 = self.I(SMA, price, 20)

    def next(self):
        if crossover(self.ma1, self.ma2):
            self.buy()
        elif crossover(self.ma2, self.ma1):
            self.sell()

bt = Backtest(GOOG, SmaCross, commission=.002,
              exclusive_orders=True)
stats = bt.run()
bt.plot()

### Additional info

- Backtesting version:

**Comment by kernc** [comment]
Continued in https://github.com/kernc/backtesting.py/issues/132.
