### ISSUE TITLE
backtesting doesnt plot graph

### ISSUE THREAD

**Issue by hussanirizvi2** [kernc/backtesting.py#132]
### Expected Behavior
graph to be plot

### Actual Behavior

> UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support (e.g. PyCharm, Spyder IDE). Reset with `backtesting.set_bokeh_output(notebook=False)`.

### Steps to Reproduce
while running the code in spyder:
```py
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

from backtesting.test import SMA, GOOG


class SmaCross(Strategy):
    def init(self):
        price = self.data.Close
        self.ma1 = self.I(SMA, price, 10)
        self.ma2 = self.I(SMA, price, 20)

    def next(self):
        if crossover(self.ma1, self.ma2):
            self.buy()
        elif crossover(self.ma2, self.ma1):
            self.sell()


bt = Backtest(GOOG, SmaCross, commission=.002,
              exclusive_orders=True)
stats = bt.run()
print(stats)
bt.plot()
```

### Additional info

- Backtesting version: 0.2.2

**Comment by kernc** [comment]
The UserWarning spells a hint: Jupyter/IPython notebook was detected. This would not work in Jupyter clients without JavaScript support (e.g. PyCharm, Spyder IDE). Spyder is presumably such a client. Reset with `backtesting.set_bokeh_output(notebook=False)`. This means using:
```py
import backtesting
backtesting.set_bokeh_output(notebook=False)
```
in your code should help.

**Comment by hussanirizvi2** [comment]
thats it! thanks a lot!

**Comment by hosseinab** [comment]
@kernc hi
this code not work

**Comment by kernc** [comment]
Please see https://github.com/kernc/backtesting.py/issues/803.

**Comment by dwellingnerd** [comment]
If you still can't work maybe you can try the code below, it does work for me.

don't type like this:
import backtesting
backtesting.set_bokeh_output(notebook=False)

try this:
from backtesting import set_bokeh_output
set_bokeh_output(notebook=False)

my version info below:
Spyder 5.3.3
Python 3.8.12
bokeh 2.4.3
backtesting 0.3.3
