### ISSUE TITLE
Hover crosshair should span across subplots

### ISSUE THREAD

**Issue by kernc** [kernc/backtesting.py#133]
### Expected Behavior

![crosshair spans across subplots](https://i.stack.imgur.com/Gvsux.gif)

### Actual Behavior

Each subplots shows its crosshair/tooltip only when it's hovered.

### Example code

* https://discourse.bokeh.org/t/mouse-vertical-line-on-linked-plots/2449/3
* https://stackoverflow.com/questions/37965669/how-do-i-link-the-crosshairtool-in-bokeh-over-several-plots/63812308#63812308

### Additional info

- Backtesting version: 0.2.2

**Comment by GJF1** [comment]
Kernc, Thanks for this awesome backtesting solution!  I apologize for asking a question here but did not see anywhere else to pose technical questions vs report problems.   My email is gord.foster@gmail.com.  Could you email me and I will ask a couple of my technical questions not addressed in the docs offline from here?  Thx G

**Comment by kernc** [comment]
> Could you email me and I will ask a couple of my technical questions

@GJF1 Can you afford my hourly rate? :raised_eyebrow: To pose questions or report problems, you're welcome to open a new issue. There are several issues tagged [question](https://github.com/kernc/backtesting.py/issues?q=label%3Aquestion) already. Appreciated if you review the existing ones first.
