### ISSUE TITLE
Allow to buy/sell a portion

### ISSUE THREAD

**Issue by dgrr** [kernc/backtesting.py#134]
Hello,

I am pretty new with this library. I am trying to test some strategies on Bitcoin, but I am struggling with the library because I don't see the way to buy or sell a little amount of BTC. If the price is 11k I need to have a balance of at least 11k to buy a unit.
BTC allows you to purchase a little amount of it. Is there any current feature supporting that? If not, can you implement it?

Thanks.

**Comment by kernc** [comment]
Here's an easy workaround for you: convert the input data to contain prices per one Satoshi or per one micro bitcoin (μBTC, as below):
```py
df: pd.DataFrame  # Bitcoin OHLC prices

df = (df / 1e6).assign(Volume=df.Volume * 1e6)
```
