### ISSUE TITLE
Attribute error with pandas_ta 

### ISSUE THREAD

**Issue by Threespire1** [kernc/backtesting.py#136]
Hi!

I'm hoping you can help me out with your great library, as I'm getting an attribute error with the df I'm using.

I'm trying to back test ema cross over vwap using pandas_ta library

### Expected Behavior

running in stand alone I get the following using the initial dateindexed df

	Open	High	Close	Low	Volume
date					
2020-09-01 23:00:00+00:00	0.73745	0.73757	0.73753	0.73738	37
2020-09-01 23:05:00+00:00	0.73748	0.73748	0.73738	0.73727	18
2020-09-01 23:10:00+00:00	0.73735	0.73735	0.73727	0.73727	3
2020-09-01 23:15:00+00:00	0.73731	0.73742	0.73737	0.73716	17
2020-09-01 23:20:00+00:00	0.73742	0.73757	0.73729	0.73729	42
...	...	...	...	...	...
2020-09-02 22:30:00+00:00	0.73360	0.73367	0.73363	0.73356	8
2020-09-02 22:35:00+00:00	0.73360	0.73367	0.73363	0.73355	6
2020-09-02 22:40:00+00:00	0.73360	0.73360	0.73355	0.73355	2
2020-09-02 22:50:00+00:00	0.73353	0.73370	0.73370	0.73353	8
2020-09-02 22:55:00+00:00	0.73372	0.73375	0.73375	0.73369	4

	Open	High	Close	Low	Volume
date					
2020-09-01 23:00:00+00:00	0.73745	0.73757	0.73753	0.73738	37
2020-09-01 23:05:00+00:00	0.73748	0.73748	0.73738	0.73727	18
2020-09-01 23:10:00+00:00	0.73735	0.73735	0.73727	0.73727	3
2020-09-01 23:15:00+00:00	0.73731	0.73742	0.73737	0.73716	17
2020-09-01 23:20:00+00:00	0.73742	0.73757	0.73729	0.73729	42
...	...	...	...	...	...
2020-09-02 22:30:00+00:00	0.73360	0.73367	0.73363	0.73356	8
2020-09-02 22:35:00+00:00	0.73360	0.73367	0.73363	0.73355	6
2020-09-02 22:40:00+00:00	0.73360	0.73360	0.73355	0.73355	2
2020-09-02 22:50:00+00:00	0.73353	0.73370	0.73370	0.73353	8
2020-09-02 22:55:00+00:00	0.73372	0.73375	0.73375	0.73369	4

result_v = ta.vwap(df['High'],df['Low'],df['Close'],df['Volume'],).tail(10)
result_v

date
2020-09-02 22:00:00+00:00    0.733838
2020-09-02 22:05:00+00:00    0.733838
2020-09-02 22:10:00+00:00    0.733838
2020-09-02 22:20:00+00:00    0.733838
2020-09-02 22:25:00+00:00    0.733838
2020-09-02 22:30:00+00:00    0.733837
2020-09-02 22:35:00+00:00    0.733837
2020-09-02 22:40:00+00:00    0.733837
2020-09-02 22:50:00+00:00    0.733837
2020-09-02 22:55:00+00:00    0.733837
Name: VWAP, dtype: float64

And ema 9

result_e = ta.ema(df['Close'],9).tail(10)
result_e

date
2020-09-02 22:00:00+00:00    0.733743
2020-09-02 22:05:00+00:00    0.733725
2020-09-02 22:10:00+00:00    0.733692
2020-09-02 22:20:00+00:00    0.733667
2020-09-02 22:25:00+00:00    0.733664
2020-09-02 22:30:00+00:00    0.733657
2020-09-02 22:35:00+00:00    0.733652
2020-09-02 22:40:00+00:00    0.733631
2020-09-02 22:50:00+00:00    0.733645
2020-09-02 22:55:00+00:00    0.733666
Name: EMA_9, dtype: float64

### Actual Behavior

When I use backtesting.py I get

[0.73753 0.73738 0.73727 0.73737 0.73729 0.73756 0.73739 0.73772 0.73786
 0.73813 0.73797 0.73779 0.73797 0.73771 0.73776 0.73738 0.7374  0.73732
 0.7377  0.73769 0.73738 0.73646 0.7366  0.73637 0.73589 0.73528 0.73552
 0.73571 0.7356  0.73598 0.73462 0.7341  0.73471 0.73386 0.73416 0.73474
 0.7346  0.73483 0.73506 0.73516 0.73563 0.73539 0.73527 0.73506 0.73484
 0.73506 0.73487 0.73505 0.73536 0.73526 0.73507 0.73497 0.73496 0.73516
 0.73517 0.7351  0.73497 0.73526 0.73522 0.73528 0.73533 0.7352  0.73531
 0.73539 0.73548 0.73542 0.73566 0.73567 0.73567 0.73561 0.73546 0.73564
 0.73564 0.73564 0.73577 0.73571 0.73553 0.73555 0.73553 0.73525 0.73535
 0.73538 0.7357  0.73608 0.73635 0.73636 0.73649 0.73616 0.73619 0.73569
 0.73545 0.73503 0.73538 0.7359  0.73554 0.73575 0.73587 0.73522 0.73566
 0.73535 0.73539 0.73518 0.73452 0.7354  0.73528 0.73507 0.73444 0.73435
 0.7342  0.73439 0.73449 0.73465 0.73486 0.73441 0.73411 0.73456 0.73465
 0.73437 0.73425 0.73426 0.73449 0.73492 0.73464 0.73467 0.73475 0.73473
 0.73489 0.73468 0.73437 0.73445 0.7347  0.73485 0.73494 0.73497 0.73496
 0.73469 0.73445 0.73429 0.73469 0.7347  0.73442 0.73439 0.73457 0.73436
 0.73448 0.73428 0.73405 0.73414 0.73382 0.7333  0.73276 0.73338 0.73367
 0.73337 0.7328  0.73345 0.73354 0.73328 0.73368 0.73462 0.73395 0.73418
 0.73347 0.73322 0.73338 0.73344 0.73298 0.73359 0.73354 0.7332  0.73337
 0.73276 0.73226 0.73161 0.73178 0.73152 0.73199 0.73184 0.73092 0.73079
 0.73139 0.73049 0.73061 0.73047 0.73094 0.73127 0.7325  0.73202 0.73165
 0.73221 0.73214 0.73234 0.73191 0.73151 0.73169 0.73129 0.73148 0.73127
 0.73162 0.73054 0.73095 0.73124 0.73151 0.73199 0.73159 0.73166 0.7318
 0.73209 0.73203 0.73184 0.73215 0.7321  0.73211 0.73222 0.73228 0.73277
 0.73243 0.73247 0.73265 0.73243 0.73245 0.73244 0.7324  0.73231 0.73239
 0.73194 0.73217 0.73235 0.73209 0.73218 0.73202 0.73208 0.73206 0.73203
 0.73192 0.73181 0.73207 0.73209 0.73175 0.73178 0.73167 0.73172 0.73189
 0.73253 0.73336 0.73336 0.73321 0.73299 0.73331 0.7334  0.7333  0.73339
 0.73331 0.73354 0.73351 0.73355 0.7336  0.7337  0.73374 0.73374 0.73381
 0.73381 0.73391 0.7339  0.73393 0.73398 0.73387 0.73385 0.73379 0.73368
 0.73374 0.73358 0.73365 0.73356 0.73357 0.73365 0.73363 0.73363 0.73355
 0.7337  0.73375]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-acd0f5b54dfd> in <module>
      6 bt = Backtest(df, VwapCross, cash=1000, commission=.0002)
      7 
----> 8 stats = bt.run()
      9 stats

C:\ProgramData\Anaconda3\lib\site-packages\backtesting\backtesting.py in run(self, **kwargs)
   1112         strategy = self._strategy(broker, data, kwargs)  # type: Strategy
   1113 
-> 1114         strategy.init()
   1115         data._update()  # Strategy.init might have changed/added to data.df
   1116 

<ipython-input-54-7894ba5a232e> in init(self)
     15 
     16         # Precompute the two moving averages
---> 17         vwap_value = vwap(self.data.High, self.data.Low, self.data.Close, self.data.Volume)
     18         ema_value = ema(self.data.Close, self.n1)
     19 

C:\ProgramData\Anaconda3\lib\site-packages\pandas_ta\overlap\vwap.py in vwap(high, low, close, volume, offset, **kwargs)
     12     offset = get_offset(offset)
     13 
---> 14     if not is_datetime_ordered(volume):
     15         print(f"[!] VWAP volume series is not datetime ordered. Results may not be as expected.")
     16 

C:\ProgramData\Anaconda3\lib\site-packages\pandas_ta\utils.py in is_datetime_ordered(df)
    172 def is_datetime_ordered(df: pd.DataFrame or pd.Series) -> bool:
    173     """Returns True if the index is a datetime and ordered."""
--> 174     index_is_datetime = pd.api.types.is_datetime64_any_dtype(df.index)
    175     try:
    176         ordered = df.index[0] < df.index[-1]

AttributeError: 'NoneType' object has no attribute 'index'

### Steps to Reproduce

1. 
create df

2.
import pandas as pd
from backtesting.lib import SignalStrategy, TrailingStrategy
from pandas_ta import vwap, ema

class VwapCross(SignalStrategy,
               TrailingStrategy):
    n1 = 9
    
    
    def init(self):
        # In init() and in next() it is important to call the
        # super method to properly initialize the parent classes
        super().init()
        print(self.data.Close)
                
        # Precompute the two moving averages
        vwap_value = vwap(self.data.High, self.data.Low, self.data.Close, self.data.Volume)
        ema_value = ema(self.data.Close, self.n1)
                
        #ema_value = self.I(ema, self.data.Close, self.n1)
        #vwap_value = self.I(vwap, self.data.High, self.data.Low, self.data.Close, self.data.Volume)
        
        
        
        # Where sma1 crosses sma2 upwards. Diff gives us [-1,0, *1*]
        signal = (pd.Series(ema_value) > vwap_value).astype(int).diff().fillna(0)
        signal = signal.replace(-1, 0)  # Upwards/long only
        
        # Use 95% of available liquidity (at the time) on each order.
        # (Leaving a value of 1. would instead buy a single share.)
        entry_size = signal * .95
                
        # Set order entry sizes using the method provided by 
        # `SignalStrategy`. See the docs.
        self.set_signal(entry_size=entry_size)
        
        # Set trailing stop-loss to 2x ATR using
        # the method provided by `TrailingStrategy`
        self.set_trailing_sl(2)

3.
from backtesting import Backtest
from backtesting.test import EURUSD

bt = Backtest(df, VwapCross, cash=1000, commission=.0002)

stats = bt.run()
stats
### Additional info

- Backtesting version:
0.2.0

Many thanks in advance for your help

Nathan

**Comment by kernc** [comment]
Closing in favor of https://github.com/kernc/backtesting.py/issues/135.
