### ISSUE TITLE
Order size for fixed amount of cash

### ISSUE THREAD

**Issue by zhixwang** [kernc/backtesting.py#137]
Hi, I'm a beginner in this project.

I want to specify the trading size of the [tutorial example](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html):

```
class SmaCross(Strategy):
    # Define the two MA lags as *class variables*
    # for later optimization
    n1 = 10
    n2 = 20
    
    def init(self):
        # Precompute the two moving averages
        self.sma1 = self.I(SMA, self.data.Close, self.n1)
        self.sma2 = self.I(SMA, self.data.Close, self.n2)
    
    def next(self):
        # If sma1 crosses above sma2, close any existing
        # short trades, and buy the asset
        if crossover(self.sma1, self.sma2):
            self.position.close()
            self.buy(size = 100)

        # Else, if sma1 crosses below sma2, close any existing
        # long trades, and sell the asset
        elif crossover(self.sma2, self.sma1):
            self.position.close()
            self.sell(size = 100)
```

However, by setting `size = 100`, I suppose it will trade for 100 units (shares of GOOGL) each time. Instead, I want to trade for an amount of size that is equivalent to 100 in cash for every trade.  

For example, if the stock price is 10$ per share, the trading size will be 10. If the price goes to $20, trade 5 shares then.

How shall I write it properly?

Thanks a lot!

**Comment by arunavo4** [comment]
@zhixwang 
        

> Order size (negative for short orders).
>         If size is a value between 0 and 1, it is interpreted as a fraction of current
>         available liquidity (cash plus `Position.pl` minus used margin).
>         A value greater than or equal to 1 indicates an absolute number of units.

```
self.buy(size=0.95)
```
Check the below link for ref https://github.com/kernc/backtesting.py/blob/aa6830be2bc334cfa59e34053e24f7b99dcd7e1b/backtesting/backtesting.py#L423-L429

**Comment by kernc** [comment]
To place an order for size equivalent of $100:
```py
current_price = self.data.Close[-1]
order_size = 100 // current_price
```
hth
