### ISSUE TITLE
How to transfer user-defined variable to user-defined strategy class

### ISSUE THREAD

**Issue by zhixwang** [kernc/backtesting.py#139]
Hi, sorry that I'm not very familiar with this nice tool yet.

I defined a strategy class called `Parcel`. I want to pass a variable (for example, named as `input_variable`) when a new instance of `Parcel` is created. 

I tried to write as:
```
class Parcel(SignalStrategy,
               TrailingStrategy):
    
    def init(self, input_variable = 10):
        super().init()
        print(input_variable )
        ....


bt = Backtest(GOOGL, Parcel, input_variable = 5, cash = 10000, commission=.002)
```

The error is:
```
TypeError: __init__() got an unexpected keyword argument 'input_variable '
```

I think this might due to that I don't really understand the meaning of **`, *, ` (the star sign)**  in the reference manual:
```
class Backtest
(
data, strategy, *, cash=10000, commission=0.0, margin=1.0, trade_on_close=False, hedging=False, exclusive_orders=False)
```

How should I correct my code properly?

Thanks a lot!

**Comment by kernc** [comment]
The asterisk in parameters specification denotes the [beginning of keyword-only parameters](https://stackoverflow.com/questions/53797057/star-as-an-argument-in-python-function).

Besides global and nonlocal scope, as shown in the examples, the only way to pass extra values is via [class variables](https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables), with specific values passed to [`Backtest.run()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.run):
```py
class Parcel(...):
    # declare the class variable in advance
    input_variable = None

    def init(self):
        super().init()
        print(self.input_variable)

bt = Backtest(...)
bt.run(input_variable=5)
```
