### ISSUE TITLE
How to set Slippage?

### ISSUE THREAD

**Issue by MarkWh1te** [kernc/backtesting.py#142]
### Expected Behavior
set  Slippage

### Actual Behavior
I donot know how to set   Slippage

**Comment by kernc** [comment]
Ok.

But do you know how to [search](https://github.com/kernc/backtesting.py/search?q=Slippage&type=issues)? :raised_eyebrow:

**Comment by kernc** [comment]
Duplicate of https://github.com/kernc/backtesting.py/issues/128.
