### ISSUE TITLE
Example of Event based backtesting

### ISSUE THREAD

**Issue by csoni** [kernc/backtesting.py#143]
Hi,
Would you be able to provide an example of Event based backtesting?

I wanted to test a simple time/event based strategy. Example, if it is the first trading day of the month, buy the security at the open and sell it at the close of the day? Would it be possible to test something like that using this package?

Thank you.

**Comment by kernc** [comment]
I guess ...

Since `next()` triggers between bars, you have to place the buy order on 31st, and the sell order on 1st is actually triggered on 2nd Open.

Assuming you have datetime-indexed daily OHLC data:
```py
class S(Strategy):
    def init(self):
        pass

    def next(self):
        ts = self.data.index[-1]

        if ts.day == ts.days_in_month:
            self.buy()
        elif ts.day == 1:
            self.position.close()
```
For more precision (i.e. to sell on 1st Close), you'd need more fine-grained OHLC data.

**Comment by csoni** [comment]
thank you.
