### ISSUE TITLE
&nbsp appearing in OHLC chart label

### ISSUE THREAD

**Issue by abhijitparida** [kernc/backtesting.py#144]
### Expected Behavior
Chart label should show OHLC chart labels without &nbsp

### Actual Behavior

&nbsp is appearing in OHLC chart label. Please see screenshot: 
![Screenshot (139)](https://user-images.githubusercontent.com/16451083/93369622-44f12700-f86d-11ea-864a-8c0240a8d635.png)

### Steps to Reproduce

1. Use Backtest.plot() method to plot a chart

### Additional info

- Backtesting version: 0.2.2
- Chrome version: 85

**Comment by kernc** [comment]
Fixed in https://github.com/kernc/backtesting.py/commit/f29d27db0284eaa09970ffe59b153cabfbc68ec9, master. Will be in the upcoming release shortly.
