### ISSUE TITLE
How to set the buy and sell signal in the graph

### ISSUE THREAD

**Issue by edwardLui** [kernc/backtesting.py#145]
How to set buy and sell signal in the graph, here is the example..
### Expected Behavior

![image](https://user-images.githubusercontent.com/34908472/93504738-7a207680-f94c-11ea-93b5-b5c9a8797737.png)

**Comment by kernc** [comment]
Can you clarify your question? I don't think I get what you want exactly.

To use a signal-based strategy, you can use [`backtesting.lib.SignalStrategy`](https://kernc.github.io/backtesting.py/doc/backtesting/lib.html#backtesting.lib.SignalStrategy) as shown in [one of the tutorials](https://kernc.github.io/backtesting.py/doc/examples/Strategies%20Library.html).

**Comment by eervin123** [comment]
I don't want to put words in @edwardLui Edward's mouth, but I believe he is looking for the option to add a "buy triangle" (green up triangle) at time of purchase, and a "sell triangle" (red down triangle) at time of sale on the price chart in the bt.plot() method.  

This is nice, but I have come to appreciate the tractor beams @kernc created as the default as seen in the image below.  

![image](https://user-images.githubusercontent.com/32274861/94868486-1d1acb00-03f8-11eb-839a-54e0ee5502d5.png)

**Comment by kernc** [comment]
Was also thinking of adding beginning markers to the P&L chart:
![Untitled](https://user-images.githubusercontent.com/684364/94869726-36e2ff00-0446-11eb-9ab8-13aa7ed65c61.jpg)
But we also have to watch out not to overwhelm Bokeh with too many objects, as with a couple thousand candles/trades the plot quickly becomes unruly and slow.
