### ISSUE TITLE
If I have an allocation table (indexed by datetime (for example: 2008-01-01), columns are the stock tickers, and the value is either 1(long)/0(no position), is it possible to translate it to P&L using the package?

### ISSUE THREAD

**Issue by auscott** [kernc/backtesting.py#146]
### Expected Behavior
If I have an allocation table (indexed by datetime (for example: 2008-01-01), columns are the stock tickers, and the value is either 1(long)/0(no position), is it possible to translate it to P&L using the package?

for example:
                       AAPL  IBM
2008-01-01          1       0
2008-01-10          0       0

### Steps to Reproduce

1.
2.
3.

### Additional info

- Backtesting version:

**Comment by kernc** [comment]
> is it possible to translate it to P&L using the package?

Yes, you can add the buy/hold/sell columns as [extra indicator columns](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Data) to the [input ohlc data](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest). Then refer to it in [`Strategy.next()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.next) either manually or through [`backtesting.lib.SignalStrategy`](https://kernc.github.io/backtesting.py/doc/backtesting/lib.html#backtesting.lib.SignalStrategy).

Duplicates: https://github.com/kernc/backtesting.py/issues/39, https://github.com/kernc/backtesting.py/issues/64.

Hth,
