### ISSUE TITLE
Check order.tp with adjusted_price when _open_trade

### ISSUE THREAD

**Issue by krishnacdunuka** [kernc/backtesting.py#147]
### Expected Behavior
Trade should not be opened

### Actual Behavior
Trade gets opened

### Steps to Reproduce

1. Place a buy/sell market order (i.e., without a limit price) with take profit (tp) set
2. For a buy order if the `order.tp` is less than that of `adjusted_price` in `_process_orders()`, it would still get opened which in real world scenario would get rejected
3. Vice-versa happens with sell trade

### Additional info

- Backtesting version: 0.2.3

**Comment by kernc** [comment]
Can you provide a brief piece of code that shows / reproduces the issue?



> 2. For a buy order if the `order.tp` is less than that of `adjusted_price` in `_process_orders()`, it would still get opened which in real world scenario would get rejected

IIUC, basically what this check was supposed to catch, but it doesn't when `tp` is less than `commission` away from the current price. Correct?

https://github.com/kernc/backtesting.py/blob/b456400e73c55afc66907013359b546b762050d4/backtesting/backtesting.py#L707-L714

Would you care to go ahead and try to fix it? :grin:

**Comment by krishnacdunuka** [comment]
For example:
Assume a buy market order with `tp=1.0333` is placed. Market data when the new order is placed is, say:
|Open|High|Low|Close|
|-|-|-|-|
|1.0325|1.0400|1.0300|1.0333|

In `new_order()` as it's a long order and `last_price`(i.e. `1.0333`) <= `order.tp` (i.e., `1.0333)` , the order gets appened to `_Broker.orders`.

After `strategy.next()` is done, let's say `self._data`'s new entry is (which is what will be used in `_process_orders()`):
|Open|High|Low|Close|
|-|-|-|-|
|1.0335|1.045|1.0330|1.0400|

Observe that this long order gets opened and closed in this bar itself.
Now, after processing and reprocessing orders, the closed trade's `entry_price` is `1.0335` and `exit_price` is `1.0333` which means this is an trade made loss. These types of orders get rejected in real world; the `tp` must be >= the trade's `entry_price`.

If the above explanation makes sense, a check of such should be placed between these lines:
https://github.com/kernc/backtesting.py/blob/b456400e73c55afc66907013359b546b762050d4/backtesting/backtesting.py#L888-L889
```python3
if need_size:
    if order.tp:
        if order.is_long and order.tp < adjusted_price or order.is_short and order.tp > adjusted_price:
            #order should not be placed
            print(f"Could not place {'long' if order.is_long else 'short'} order as adjusted_price ({adjusted_price}) {'>' if order.is_long else order.is_short'} tp ({order.tp})")
```

**Comment by kernc** [comment]
Thanks for the comprehensible example.

Since `adjusted_price` is just `last_price` adjusted for `commission`, wouldn't simply using `adjusted_price` (instead of `last_price`) in the following checks also work? That is, before placing orders.
https://github.com/kernc/backtesting.py/blob/b456400e73c55afc66907013359b546b762050d4/backtesting/backtesting.py#L707-L714
I guess less-or-equal signs (`<=`) should also be replaced with strict inequality checks (`<`). I wonder why they weren't initially. :thinking:

**Comment by krishnacdunuka** [comment]
Hey sorry for such a long black out. Looks like you've solved the issue. I'm not sure how `adjusted_price` plays here as I'm using a highly modified version of your `backtesting.py` for myself and I don't have use the `adjusted_price`. As you've understood my above example, if your changes solve the issue then well done and thank you! Again, sorry for my black out.

**Comment by kernc** [comment]
We check SL/TP against adjusted price before placing an order, so I guess this solves the issue. :crossed_fingers: 

What other customizations are you running? Anything the community might benefit from?

**Comment by krishnacdunuka** [comment]
Bid and ask prices support, profit calculation in terms of account currency (for e.g. CADJPY PL in USD), various types of metrics like realised/unrealised PLs and a few more final stats. This did come at a cost - inability to use your plotting functionality but that's not an immediate requirement for me. Thanks for your great work! It'd have taken me much longer without your base code to come up with all the logics.

**Comment by kiansina** [comment]
@kernc In calculation of entry price, the commission is also become considered, but for stop loss, the platform compares the value of stop loss with entry price not considering commission. So it gives error, because it is saying that stop loss is greater than limit (which is not in reality). It forces me to choose much smaller stop loss that at the end leads to negative return!!
