### ISSUE TITLE
Why was my order filled significantly higher than the high of the bar?

### ISSUE THREAD

**Issue by tankorsmash** [kernc/backtesting.py#153]
### Expected Behavior 

I'd expect my order to fill at or around the close of the current bar/open of next bar.

### Actual Behavior

My order looks like it was filled at $178.74, but the bar it took place in had a high of $177.89, so this doesn't seem like it should b e possible. `trade_on_close` is left default.

I wouldn't think this should be possible, regardless of how I place my order. I've tried placing a limit order at the latest close price, I've tried a market order, and I've tried a close price + a little bit of wiggle room and it doesn't place this order where I'd expect.

Is there something I can try to debug this? Is this behaviour caused by something I can look into.

### Steps to Reproduce

1.
2.
3.

### Additional info

![image](https://user-images.githubusercontent.com/1312390/95412746-a863f700-08f7-11eb-9e88-6d882b0d756e.png)

The yellow line is the trade, is this is relevant:

![image](https://user-images.githubusercontent.com/1312390/95413363-368cad00-08f9-11eb-8e7d-2f99bb896c78.png)

Data of the bar where the trade was entered:

```
Volume    127488.0000
Vw           178.4709
Open         178.3501
Close        178.6400
High         178.6700
Low          178.3450
N            924.0000
Name: 2020-05-15 11:02:00-05:00, dtype: float64
```
and the bar following it

```
Volume    76352.0000
Vw          178.6253
Open        178.6400
Close       178.6400
High        178.6700
Low         178.5600
N           644.0000
Name: 2020-05-15 11:03:00-05:00, dtype: float64
```

- Backtesting version: 0.2.0

**Comment by kernc** [comment]
Positions are opened at price adjusted for commissions:
https://github.com/kernc/backtesting.py/blob/3045b64635fe9e5af51046b7bdf7cdfcbf375c1e/backtesting/backtesting.py#L845-L847

Above chart indicates you are using 0.5% round-trip commission (`commission=.005`).

This is the reality of algorithms with transactions costs.

**Comment by tankorsmash** [comment]
Ah, that makes sense. I assumed commissions were handled after the trade magically, but I never looked into it. Thank you for the fast answer.

**Comment by kernc** [comment]
Hmm, by the looks of it, also a case of https://github.com/kernc/backtesting.py/issues/147. :thinking:

**Comment by esaesa** [comment]
> Positions are opened at price adjusted for commissions:
> 
> [backtesting.py/backtesting/backtesting.py](https://github.com/kernc/backtesting.py/blob/3045b64635fe9e5af51046b7bdf7cdfcbf375c1e/backtesting/backtesting.py#L845-L847)
> 
> Lines 845 to 847 in [3045b64](/kernc/backtesting.py/commit/3045b64635fe9e5af51046b7bdf7cdfcbf375c1e)
> 
>  # Adjust price to include commission (or bid-ask spread). 
>  # In long positions, the adjusted price is a fraction higher, and vice versa. 
>  adjusted_price = price * (1 + copysign(self._commission, order.size)) 
> Above chart indicates you are using 0.5% round-trip commission (`commission=.005`).
> 
> This is the reality of algorithms with transactions costs.

This was clear but now the logic changed can you clarified why it is not 1 + commission now in 
(https://github.com/kernc/backtesting.py/blob/cd4bc6c7ff20f843d87fd21dbf3b895e8612ad9d/backtesting/backtesting.py#L944)
It is not clear how we add total commision to price while the price still will remultiplied to size again
