### ISSUE TITLE
Testing on multiple assets

### ISSUE THREAD

**Issue by tradingrobot14** [kernc/backtesting.py#155]
Hi, I would like to backtest a trading strategy that works on multiple forex asset pairs. I need to be able to import the multiple data for different forex pairs into the backtest.  

The strategy is able to place trades on the different Forex asset pairs during the backtest.  

Is this possible? Thank you so much for your help!

**Comment by kernc** [comment]
Backtesting.py is currently (and for the forseable future) single-instrument only. But pairs trading technically _is_ possible. See https://github.com/kernc/backtesting.py/issues/104.
