### ISSUE TITLE
Accessing the optimized parameters

### ISSUE THREAD

**Issue by chhudson** [kernc/backtesting.py#16]
[New Feature]
After optimizing a strategy, I'd like to be able to access the optimized values or add them as new fields since I'm backtesting across multiple instruments.

An example:
Cci(parameter=130, parameter2=140) is the output in the `_strategy` field. 

I'd like to access `parameter=130` and create a new column on the dataframe.

**Comment by kernc** [comment]
You should be able to access the parameters directly on the `_strategy` instance: `optimization_result._strategy.parameter`.

**Comment by chhudson** [comment]
appreciate the quick response!

**Comment by joshyattridge** [comment]
Hello,
I am attempting to do this also but your solution above doesn't seem to work.
I found that the optimised values for the parameter is always to 1st one specified in the list.

This is the code I have:

output = bt.optimize(sma_fast_period=[10, 100])
print("test1:", output._strategy.sma_fast_period)
output = bt.optimize(sma_fast_period=[100, 10])
print("test2:", output._strategy.sma_fast_period)


And this is the output I get:

test1: 10
test2: 100


As you can see it selects the 1st element in the provided list each time.

Do you have a solution for this?
