### ISSUE TITLE
Python 3.5 "end of life"

### ISSUE THREAD

**Issue by kernc** [kernc/backtesting.py#161]
With [Python 3.5.x having reached its end of life/support](https://www.python.org/downloads/release/python-3510/), we can (drop supposed 3.4 support :laughing: and) begin to use ["advanced" features from Python 3.6](https://docs.python.org/3/whatsnew/3.6.html#summary-release-highlights):

* [f-strings](https://www.python.org/dev/peps/pep-0498/)
* [variable annotations](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526) over type comments
  https://github.com/kernc/backtesting.py/blob/86205f8496173302b1fc80fd47ec9fab536f119b/backtesting/_util.py#L102-L104

Additionally:
* Review `version_info` checks
  https://github.com/kernc/backtesting.py/blob/1512f0e4cd483d7c0c00b6ad6953ca28322b3b7c/setup.py#L4-L5
  https://github.com/kernc/backtesting.py/blob/1512f0e4cd483d7c0c00b6ad6953ca28322b3b7c/setup.py#L57

**Comment by gitrahulgit** [comment]
Hey! I want to work on it

**Comment by perlbeforeswine** [comment]
Hello! I'd like to work on this too, please! Do I need to do anything specific before getting started? Thank you!

**Comment by kernc** [comment]
One does the f-strings, one does the type comments — that's fine by me! :laughing:
