### ISSUE TITLE
Invalid or erroneous drawdown calculations in equity plot for resampled datasets

### ISSUE THREAD

**Issue by eervin123** [kernc/backtesting.py#162]
### Expected Behavior
Plots, where data was resampled due to >10,000 bars, should calculate max drawdowns and drawdown periods similar to those computed in the _compute_stats method

### Actual Behavior
It appears when plots are downsampled in the Backtest.plot(resample=True) the drawdown calculations and possibly drawdown duration (beginning and ending periods) are miscalculated.  

Here are two examples of such charts:
https://www.realitysharesadvisors.com/fund_dash/fix_this_eth.html
https://www.realitysharesadvisors.com/fund_dash/fix_this.html

Note the legend in one of the charts showing 0 days of max drawdown 
![image](https://user-images.githubusercontent.com/32274861/97244986-42141b00-17b7-11eb-89b5-10e7e5ad37ee.png)

Here is an example where the red line is misplaced on an incorrect drawdown.  
![bokeh_plot (1)](https://user-images.githubusercontent.com/32274861/97245057-6ec83280-17b7-11eb-924f-9fac6caa2181.png)

### Steps to Reproduce

1. I was using 5-minute candles on multiple years of data. 
2. Run Backtest.plot() on a large dataset and it should reproduce the result...Hopefully, if not, I am happy to privately share my datafiles and strategy class for you to reproduce on your system.

### Additional info

This was also referenced in a different issue  https://github.com/kernc/backtesting.py/pull/156#discussion_r511525694

- Backtesting version: 0.2.3   
- bokeh 2.2.3
- python 3.8.5
- pandas 1.1.3

**Comment by kernc** [comment]
> Plots, where data was resampled due to >10,000 bars, should calculate max drawdowns and drawdown periods similar to those computed in the _compute_stats method

Resampling of equity curve is computed this way:
https://github.com/kernc/backtesting.py/blob/05329deaa507e64dbd7858f9d253eecb20ab9f16/backtesting/_plotting.py#L118
https://github.com/kernc/backtesting.py/blob/05329deaa507e64dbd7858f9d253eecb20ab9f16/backtesting/lib.py#L62-L66
(`'Equity'` should maybe aggregate with `'last'`. :thinking:)

-----

Interestingly, the whole thing works correctly (conjecture) on this toy example:
```py
from backtesting.test._test import SmaCross
bt = Backtest(GOOG, SmaCross)
bt.run(fast=3, slow=8)
bt.plot()
```
![Screenshot_2020-10-27_15-45-18](https://user-images.githubusercontent.com/684364/97317879-94167880-186b-11eb-8c2a-b80e984a205a.png)
Resampling daily to bi-monthly:
```py
bt.plot(resample='2M', superimpose=False)
```
![Screenshot_2020-10-27_15-49-09](https://user-images.githubusercontent.com/684364/97318336-0c7d3980-186c-11eb-8d2d-bafa946e965a.png)

Max DD Duration seems to be rounded to round units (10 2-months).

Therefore, it must be something specific to your dataset and something in the way drawdown intersections are computed:
https://github.com/kernc/backtesting.py/blob/05329deaa507e64dbd7858f9d253eecb20ab9f16/backtesting/_plotting.py#L277-L290
https://github.com/kernc/backtesting.py/blob/05329deaa507e64dbd7858f9d253eecb20ab9f16/backtesting/_plotting.py#L354-L359

I don't suppose something strikes you as odd at first glance? :sweat_smile:

**Comment by eervin123** [comment]
> backtesting.py/backtesting/lib.py

> Lines 62 to 66 in 05329de

```
 _EQUITY_AGG = { 
     'Equity': 'mean', 
     'DrawdownPct': 'max', 
     'DrawdownDuration': 'max', 
 } 
```

> ('Equity' should maybe aggregate with 'last'. 🤔)

That did the trick.  Here is the before picture
![image](https://user-images.githubusercontent.com/32274861/97340416-fad26c80-1840-11eb-946c-7c4c4098c158.png)

with a zoom in on the problem period.
![image](https://user-images.githubusercontent.com/32274861/97341007-bc897d00-1841-11eb-9fa4-6bd9cea8a3ca.png)
As you can see above, this is very close and likely the culprit from some downsampling throwing an erroneous peak.


Here is an after picture after I set the `'Equity'` : `'last'` in the `_EQUITY_AGG` dict.
![image](https://user-images.githubusercontent.com/32274861/97340789-73d1c400-1841-11eb-9627-32ceacda3c4a.png)

The Max Drawdown Duration perfectly matches what is expected from the _compute_stats calculations.

**Comment by kernc** [comment]
Pleasure to work with you.
