### ISSUE TITLE
no handler when the backtesting finnished?

### ISSUE THREAD

**Issue by guzuomuse** [kernc/backtesting.py#168]
say:  i entry a lot of positions but without any closed. i want to close all when backtesting finished. so i need a handler

but i can't find it. how? 

so i think we need a "stop" method like "backtrader" to handle some logic for example close positions or do some customized statistic etc... 
this "stop" handler should be called after backtesting finished but before "built-in" statistices calculated so that we can append our 
customized statistic items
what 's your idea? @kernc

**Comment by kernc** [comment]
Backtesting.py has a decided [simple API](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html): only `init()` and `next()` to care about. With it, you could close all trades with something like:
```py
class Example(Strategy):
    def init(self):
        ...
        self.data_length = len(self.data)

    def next(self):
        if len(self.data) == self.data_length:
            ...  # end of backtest
```
The reason it currently won't work is bug https://github.com/kernc/backtesting.py/issues/158. (Expecting a fix shortly. You can do a `-1` if you need it immediately.)

> so that we can append our customized statistic items

What do you mean? Have an example? There's a pretty extendable [trade data API](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Trade-data) you can use to compute extra stats ...

**Comment by guzuomuse** [comment]
woo...minus 1 . i indeed coded like that before but could not get it work .but now i got it
> so that we can append our customized statistic items

just for custom statstic demand.  for example we want to calculate the "mae" "mfe". but as you say , we can calculate with the trade data api.
thank you.

**Comment by guzuomuse** [comment]
`        if len(self.data) == self.data_length - 1:
            self.position.close()
            pass`
give the warning info:  `c:\........pandas\core\series.py:726: RuntimeWarning: invalid value encountered in log`

**Comment by kernc** [comment]
What's your `backtesting.__version__`? Something like this had been fixed a while ago, and the only place we call `log()` ensures the values are positive:
https://github.com/kernc/backtesting.py/blob/028f02d4c5c358e39d67411eeb1f1a5f82370cef/backtesting/backtesting.py#L1395-L1396

**Comment by guzuomuse** [comment]
version:0.2.4 
easy to reproduce
in the "get start" code just replace the 
`bt = Backtest(GOOG, SmaCross, commission=.002,exclusive_orders=True)`
with
`bt = Backtest(GOOG, SmaCross,commission=.002, exclusive_orders=False, hedging=True, cash=100000000)`
the warning info will appear

**Comment by kernc** [comment]
This doesn't raise any warnings for me:
```py
from backtesting import Backtest
from backtesting.test import GOOG
from backtesting.test._test import SmaCross
bt = Backtest(GOOG, SmaCross,commission=.002, exclusive_orders=False, hedging=True, cash=100000000)
bt.run()
```
Put a [breakpoint](https://docs.python.org/3/library/functions.html#breakpoint) in _c:\\...\pandas\core\series.py, line 726_. Typing [`where`](https://docs.python.org/3/library/pdb.html#pdbcommand-where) in the subsequent debugger will give the _full stack trace_, so you'll be able to see how the process got there.

**Comment by guzuomuse** [comment]
your code above has no problem. bellow is "mine"(copyed from the "get start exmaple") full version code,please check it out.

```
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

from backtesting.test import SMA, GOOG


class SmaCross(Strategy):
    n1 = 10
    n2 = 20

    def init(self):
        self.sma1 = self.I(SMA, self.data.Close, self.n1)
        self.sma2 = self.I(SMA, self.data.Close, self.n2)

    def next(self):
        if crossover(self.sma1, self.sma2):
            self.buy()
        elif crossover(self.sma2, self.sma1):
            self.sell()


# bt = Backtest(GOOG, SmaCross, cash=10000,
#               commission=.002, exclusive_orders=True)
bt = Backtest(GOOG, SmaCross,
              commission=.002, exclusive_orders=False, hedging=True, cash=100000000)
output = bt.run()
# bt.plot()
```
