### ISSUE TITLE
Add new Metric in backtest

### ISSUE THREAD

**Issue by sajjadGG** [kernc/backtesting.py#169]
### Expected Behavior
I want to add new metrics to be reported after backtest.run() has completed for example average pip or ... is there any way
to do so?

**Comment by kernc** [comment]
What's the equation for "average pip"? Generally, [trade data API](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Trade-data) can be used to compute additional trade features ...

**Comment by sajjadGG** [comment]
> What's the equation for "average pip"? Generally, [trade data API](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Trade-data) can be used to compute additional trade features ...

thanks that solved my problem
