### ISSUE TITLE
Win rates constantly equals to 0

### ISSUE THREAD

**Issue by baptisteArnaud** [kernc/backtesting.py#17]
I throw this kind of Forex data to backtesting runner :

Open | High | Low | Close | Volume
1.11293 | 1.11308 | 1.11293 | 1.11304 | 9
1.11306 | 1.11306 | 1.11300 | 1.11300 | 5
1.11298 | 1.11298 | 1.11288 | 1.11296 | 32
1.11298 | 1.11307 | 1.11298 | 1.11307 | 9
1.11310 | 1.11312 | 1.11306 | 1.11306 | 4
1.11304 | 1.11306 | 1.11298 | 1.11300 | 7
1.11298 | 1.11300 | 1.11296 | 1.11298 | 5
1.11296 | 1.11296 | 1.11296 | 1.11296 | 1
1.11298 | 1.11298 | 1.11296 | 1.11296 | 2
1.11298 | 1.11300 | 1.11296 | 1.11298 | 5
1.11296 | 1.11300 | 1.11296 | 1.11300 | 3

Whenever I run my strategy, it gives me a 0% Win rate:

```
Start                     2019-07-29 00:00:00
End                       2019-07-30 16:24:00
Duration                      1 days 16:24:00
Exposure [%]                          50.9076
Equity Final [$]                      8581.46
Equity Peak [$]                         10000
Return [%]                           -14.1854
Buy & Hold Return [%]                0.199454
Max. Drawdown [%]                    -14.2093
Avg. Drawdown [%]                         NaN
Max. Drawdown Duration                    NaN
Avg. Drawdown Duration                    NaN
# Trades                                   78
Win Rate [%]                                0
Best Trade [%]                      -0.170316
Worst Trade [%]                       -0.2566
Avg. Trade [%]                      -0.196327
Max. Trade Duration           0 days 02:14:00
Avg. Trade Duration           0 days 00:16:00
Expectancy [%]                            NaN
SQN                                  -71.8455
Sharpe Ratio                         -8.79786
Sortino Ratio                        -8.79786
Calmar Ratio                       -0.0138168
```

But when plotting, I can see mutliple winning trades : 

[![Capture.png](https://i.postimg.cc/Qt7QscFj/Capture.png)](https://postimg.cc/ZBTBxBPQ)

Why does it give me negative P/L ?

**Comment by kernc** [comment]
On the plot, none of the trades are winning (all are red, the dashed bar lines as well as the P/L triangle indicators). If you are working on very short (e.g. 1m or 5m) time frames, the spread/commissions alone can be a challenge to overcome. :smile: 

Is this it?

**Comment by baptisteArnaud** [comment]
You are absolutely right. Thanks for pointing that out!
To simulate typical forex bid-ask spread you say in documentation I should set the commission to 0.0002?

**Comment by kernc** [comment]
I'd say that's a good, adversary average. `1.11296 * .0002 ~ .00022` is about the difference between 1.11296 Close and next 1.11298 Open (single tick (volume) above).

**Comment by kernc** [comment]
If you discover something viable on those time frames, make sure to [contrib it](https://kernc.github.io/backtesting.py/doc/backtesting/#example-strategies). :smile:
