### ISSUE TITLE
Price at different time points

### ISSUE THREAD

**Issue by Myname10** [kernc/backtesting.py#170]
Hello, 

I want to implement a strategy but i cant find how to get the price at some date t. For example, as you showed in the read me, I can access the closing price now by self.data.Close. I'm wondering how can I get the price of day before, day -2 ...

Thank you

**Comment by kernc** [comment]
It says in the [tutorial](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Strategy), admittedly somewhat involved:

> In `init()`, the whole series of points was available, whereas in `next()`, the length of `self.data` and all declared indicators is adjusted on each `next()` call so that `array[-1]` (e.g. `self.data.Close[-1]` or `self.sma1[-1]`) always contains the most recent value, `array[-2]` the previous value, etc. (ordinary Python indexing of ascending-sorted 1D arrays).

In addition it says in the [API reference](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data):

> Price data, roughly as passed into `Backtest`

So, assume `self.data` is a data frame as it was passed in, or at least a similar collection of arrays with deviations and use cases as described.
