### ISSUE TITLE
Plot the entry price and exit price 

### ISSUE THREAD

**Issue by Myname10** [kernc/backtesting.py#171]
Hello,

This is not a bug but it's a question: I'd like to plot the entry price(ep), stop lose(sl) and profit target (tp) of a tarde but I could'nt figure that out. I'd like to have some sort of arrwos at my candle sticks indicating ep, sl , tp 

Thank you

**Comment by kernc** [comment]
Entries/exits are plotted as tractor beams (centered) as the image here shows: https://github.com/kernc/backtesting.py/issues/145#issuecomment-702424290
See https://github.com/kernc/backtesting.py/issues/56 for a way to plot SL/TP levels.

**Comment by Myname10** [comment]
Thank you !
