### ISSUE TITLE
Can not use backtesting.py as a git submodules in my project

### ISSUE THREAD

**Issue by zuongthaotn** [kernc/backtesting.py#173]
### Expected Behavior
Library loads successfully

### Actual Behavior
File "/home/megaboy/GIT/algo-stocks/backtest/backtesting/backtesting.py", line 31, in <module>
    from ._plotting import plot
ImportError: attempted relative import with no known parent package

### Steps to Reproduce

1. Create a new git project, add .gitmodules file
[submodule "backtest"]
	path = backtest
	url = https://github.com/kernc/backtesting.py.git

2. create a new python file in new project
from backtest.backtesting import Backtest, Strategy
add some backtest code
3. Run file

**Comment by kernc** [comment]
This is a known Python issue. :grin: 
https://www.google.com/search?q=git+submodule+%22attempted+relative+import+with+no+known+parent+package%22

**Comment by zuongthaotn** [comment]
I have researched google but the issue is not solved. Do you have a detail suggestion?

**Comment by kernc** [comment]
@zuongthaotn What fix have you found for it?

**Comment by zuongthaotn** [comment]
I'm using 

```
BACKTESTING_MODULE_PATH = os.path.abspath('../../backtest/')
sys.path.insert(1, BACKTESTING_MODULE_PATH)
from backtest.backtesting import Backtest, Strategy
```
my folder project is /home/megaboy/GIT/algo-stocks/ and it includes:
backtest/backtesting/
.gitmodules
.gitignore
.git
test.py
