### ISSUE TITLE
An unexpected behavior 

### ISSUE THREAD

**Issue by Myname10** [kernc/backtesting.py#174]
I'm testing a strategy on daily candles but i got a weird behavior. 

Here is my order : <Order size=1.0, limit=790.0, stop=773.0, sl=720.0, tp=808.0, contingent=0>

This order get filled the next day at the entry_price: 771.2394 < my stop price = 773.0 (weird part)

Here is the next day candle: OHLC 769.7, 778.81, 765.5, 773,95

Any idea why this is happening ? 

Thank you

**Comment by kernc** [comment]
I don't understand what you mean. Need a full reproducible code example to investigate.

Stop price, once hit, turns the order into a market/limit order:
https://github.com/kernc/backtesting.py/blob/252cabdf15fd8827560393cc4eb64d48a5a66bd9/backtesting/backtesting.py#L781-L790
https://github.com/kernc/backtesting.py/blob/252cabdf15fd8827560393cc4eb64d48a5a66bd9/backtesting/backtesting.py#L810-L814

**Comment by Myname10** [comment]
Here is my code

class DummyStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        print(self.data.index[-1])
        # closing  non contingent orders
        for order in self.orders:
            if not order.is_contingent:
                order.cancel() 
        
        if f"{self.data.index[-1]}" == "2013-02-06 00:00:00":
            self.buy(stop = 773, limit = 790, sl=720, tp = 808)
        
        print('orders  ', self.orders)
        print('trades  ', self.trades)
        for trade in self.trades:
            print(trade.entry_price)
        print('-'*100)
        

bt = Backtest(GOOG, DummyStrategy, cash=20_000, commission=.002,
              exclusive_orders=True)
stats = bt.run()
bt.plot()

The stop price was hit but and the entry_price was smaller than the stop price.  My understanding is when i have a buy stop limit order, the order is trigged once the price is above stop and the entry_price should be between stop and limit prices. Am I missing something here ?

**Comment by kernc** [comment]
Your reasoning is correct. The bug is in line:
https://github.com/kernc/backtesting.py/blob/252cabdf15fd8827560393cc4eb64d48a5a66bd9/backtesting/backtesting.py#L805-L806
The lesser `open` wins `min` over `stop_price`. Instead, the line should (probably :sweat_smile:) say:
```py
price = (min(stop_price or open, order.limit)
```

**Comment by Myname10** [comment]
I'll try to test this formula 👍  Thank you

**Comment by kernc** [comment]
Can you verify the proposed fix works?

**Comment by Myname10** [comment]
https://github.com/kernc/backtesting.py/blob/252cabdf15fd8827560393cc4eb64d48a5a66bd9/backtesting/backtesting.py#L770

You need to change the line above as you used the word open as a variable of self.open[0]

**Comment by Myname10** [comment]
I still don't understand the entry price. 

I used a dummy strategy enter at the date 2015-05-07 00:00:00 at the price slightly bigger than the high of the candle. Here's my order: self.buy(stop = 47.17, limit = 47.21, sl = sl, tp = tp, size = size) and the order executed at the entry_price = 47.2643 as u can see in the figure 
![image](https://user-images.githubusercontent.com/44066130/98991587-53d21e00-252c-11eb-9b25-1ce81ff13ab8.png).

**Comment by kernc** [comment]
> buy(stop=47.17, limit=47.21, ...) and the order executed at the entry_price = 47.2643

This is expected. Entry price is adjusted for spread/commission:
https://github.com/kernc/backtesting.py/blob/09e631a4354e1dd6b41b5e7dee05fec38e601e07/backtesting/backtesting.py#L846-L848

The only issue is that your `adjusted_price` is not below set `limit`. :thinking:

**Comment by kernc** [comment]
>  issue is that your `adjusted_price` is not below set `limit`

For the time being, wontfix. We only work with a single set of prices (i.e. no separate bid and ask prices), so this behavior corresponds to backtest being loaded with [mid prices](https://en.wikipedia.org/wiki/Mid_price), which are the norm.
