### ISSUE TITLE
Way to get closed-trade and active-trade data

### ISSUE THREAD

**Issue by tedmiss** [kernc/backtesting.py#175]
How to access trade data after running backtesting and output into csv files?

**Comment by kernc** [comment]
Yes, please rtfm the [Quick Start manual, Trade data section](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Trade-data). Something like this would work:
```py
stats._trades.to_csv('output.csv')
```
