### ISSUE TITLE
a bug in _process_trades

### ISSUE THREAD

**Issue by sdmovie** [kernc/backtesting.py#179]
### Expected Behavior
I have multiple trades of same stock, each -500 , then a new order come to close 500 stock, exception occured
the code has little bug
[file backtesting.py, line 864](https://github.com/kernc/backtesting.py/blob/252cabdf15fd8827560393cc4eb64d48a5a66bd9/backtesting/backtesting.py#L864-L879):
```py

              for trade in list(self.trades):
                    if trade.is_long == order.is_long:
                        continue
                    assert trade.size * order.size < 0
                    #if need_size ==0: #add to fix
                    #      break       
                    # Order size greater than this opposite-directed existing trade,
                    # so it will be closed completely
                    if abs(need_size) >= abs(trade.size):
                        self._close_trade(trade, price, time_index)
                        need_size += trade.size
                    else:
                        # The existing trade is larger than the new order,
                        # so it will only be closed partially
                        self._reduce_trade(trade, price, need_size, time_index)
                        need_size = 0
                        break
```
the reason is order 500 is filled by first -500 trade, then need_size is zero, should not call _reduce_trade with need_size =0  is 
add code when need_size == 0 the break

### Steps to Reproduce

1.
2.
3.

### Additional info

- Backtesting version: 0.2.5

**Comment by kernc** [comment]
Can you post the exception traceback or code to exactly reproduce the bug?

**Comment by kernc** [comment]
@sdmovie A reproducible code example would be much appreciated!

**Comment by sdmovie** [comment]
It's a bit tight linked to my data and algorithm.
I try to repro using backtesting.py original .
`from backtesting.test import SMA,GOOG
from backtesting.lib import crossover
class shentouganwu_test(Strategy):
    def init(self):
        Close=self.data.close
        self.ma1 = self.I(SMA, Close, 10)
        self.ma2 = self.I(SMA, Close, 20)
    def next(self):
        if crossover(self.ma1, self.ma2) and abs((self.ma2[-1]-self.ma1[-1])/self.ma1[-1])<0.001:
            print(self.ma1[-1], self.ma2[-2]) 
            self.buy(size=1)
        if crossover(self.ma2,self.ma1) and abs((self.ma2[-1]-self.ma1[-1])/self.ma1[-1])<0.001:
            self.sell(size=1)
df=GOOG.rename(columns={"Close":"close"})
backtest = Backtest(df, shentouganwu_test, commission=.002)
result=backtest.run()
backtest.plot()
            `
* I changed local repo to use lowercase(no Cap) for open/high/low/close/volume.
The idea is crossup and cross down do not show in pair, thus multiple buy in executed, then a sell come, exception shouw as below -

180.49899999999997 180.36349999999987
410.1260000000002 408.9839999999999
415.4970000000002 413.8729999999999
355.64500000000027 354.02750000000003
377.85300000000035 378.1995
378.2700000000003 378.3034999999999
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-32-4299aaf4741b> in <module>
      1 df=GOOG.rename(columns={"Close":"close"})
      2 backtest = Backtest(df, shentouganwu_test, commission=.002)
----> 3 result=backtest.run()
      4 backtest.plot()

d:\backtesting.py\backtesting\backtesting.py in run(self, **kwargs)
   1147                 # Handle orders processing and broker stuff
   1148                 try:
-> 1149                     broker.next()
   1150                 except _OutOfMoneyError:
   1151                     break

d:\backtesting.py\backtesting\backtesting.py in next(self)
    751     def next(self):
    752         i = self._i = len(self._data) - 1
--> 753         self._process_orders()
    754 
    755         # Log account equity for the equity curve

d:\backtesting.py\backtesting\backtesting.py in _process_orders(self)
    876                         # The existing trade is larger than the new order,
    877                         # so it will only be closed partially
--> 878                         self._reduce_trade(trade, price, need_size, time_index)
    879                         need_size = 0
    880                         break

d:\backtesting.py\backtesting\backtesting.py in _reduce_trade(self, trade, price, size, time_index)
    913 
    914     def _reduce_trade(self, trade: Trade, price: float, size: float, time_index: int):
--> 915         assert trade.size * size < 0
    916         assert abs(trade.size) >= abs(size)
    917 

AssertionError:

**Comment by kernc** [comment]
Excellent, this makes a proper bug report! Thanks!
