### ISSUE TITLE
It's possible modify StopLoss or Take Profit in open order? 

### ISSUE THREAD

**Issue by Belladona-c0re** [kernc/backtesting.py#18]
Hi,

Somebody can help me to know if it's possible to modify values like stoploss or takeprofit from a order?

I want to check a strategy that when the order take TP, this move the StopLoss to EMA value.

This can be possible?

Thanks guys !

**Comment by kernc** [comment]
> Is it possible to modify values like stoploss or takeprofit from a order?

See [`Strategy.orders.set_sl/tp()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Orders.set_sl).
