### ISSUE TITLE
Is there a tutorial showing how I can use my own pandas dataframe?

### ISSUE THREAD

**Issue by sedna16** [kernc/backtesting.py#182]
I've checked the docs and there seems to be no way to implement or add my own pandas dataframe.

I needs to do this because I will be using that df in the next()

**Comment by kernc** [comment]
> add my own pandas dataframe

What do you mean? Backtesting.py only works with _your_ data frames! The dataframe needs the [OHLC(V) columns as prescribed](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Data), and any additional columns are optional. See: https://github.com/kernc/backtesting.py/issues/64.

If you need back the `df` in `next()`, you can use its [`.df` accessor](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data):
```py
    def next(self):
        df = self.data.df
        ...
```

**Comment by sedna16** [comment]
I tried doing it. Here's what I got with the result
-------
[504 rows x 7 columns]
Start                     2018-11-14 00:00:00
End                       2020-11-13 00:00:00
Duration                    730 days 00:00:00
Exposure Time [%]                           0
Equity Final [$]                        10000
Equity Peak [$]                         10000
Return [%]                                  0
Buy & Hold Return [%]                 70.2681
Max. Drawdown [%]                          -0
Avg. Drawdown [%]                         NaN
Max. Drawdown Duration                    NaN
Avg. Drawdown Duration                    NaN
# Trades                                    0
Win Rate [%]                              NaN
Best Trade [%]                            NaN
Worst Trade [%]                           NaN
Avg. Trade [%]                            NaN
Max. Trade Duration                       NaN
Avg. Trade Duration                       NaN
Profit Factor                             NaN
Expectancy [%]                            NaN
SQN                                       NaN
Sharpe Ratio                              NaN
Sortino Ratio                             NaN
Calmar Ratio                              NaN
_strategy                            SMACross
_equity_curve                          Equ...
_trades                   Empty DataFrame
...
dtype: object

----------------------

The colums for dataframe as as follows:
- Date (index)
- Open
- High
- Low
- Close
- Volume
- sma_20
- sma_50

**Comment by sedna16** [comment]
Take note: the indicators are pre-added from outside the SMACross class

**Comment by kernc** [comment]
Sorry, but without code/data, that's really not enough to go on. :point_right: Zero trades were made.
Perhaps raise your cash/leverage.

**Comment by sedna16** [comment]
ok, I'll try to post the code here after work.

**Comment by sedna16** [comment]
I think I finally got it working (results, no charts yet)

`def next(self):

		# If sma1 crosses above sma2, close any existing
		# short trades, and buy the asset
		if crossover(self.data.df.sma_20, self.data.df.sma_50):
			self.position.close()
			self.buy()

		# Else, if sma1 crosses below sma2, close any existing
		# long trades, and sell the asset
		elif crossover(self.data.df.sma_50, self.data.df.sma_20):
			self.position.close()
			self.sell()`

**Comment by kernc** [comment]
So is there an issue here?

**Comment by sedna16** [comment]
I'll test it out.

**Comment by sedna16** [comment]
> Note, you should find it far more performant not to convert to df:
> 
> ```python
> if crossover(self.data.sma_20, self.data.sma_50):
>     ...
> ```
> 
> So is there an issue here?

Tested this out, it worked. But somehow the first time I used it, it didn't behaved properly.
