### ISSUE TITLE
Wording in warning

### ISSUE THREAD

**Issue by tankorsmash** [kernc/backtesting.py#184]
>A SL/TP order would execute in the same bar as its contingent upon stop/limit order.

I think this is saying "a 'stop loss/take profit' order would execute in the same bar, as it's contingent upon a stop or limit order", but I am not quite sure. I keep trying to think of a better wording, but I can't come up with anything.

https://github.com/kernc/backtesting.py/blob/10a6de22b091d977c9ecfa1d5b692dc3805c3a59/backtesting/backtesting.py#L902

```
"A SL/TP order would execute in the same bar as its contingent upon "
                            "stop/limit order. Since we can't assert the precise intra-candle "
                            "price movement, the affected SL/TP order will be executed on "
                            "the next (matching) price/bar, making the result (of this trade) "
                            "somewhat dubious. "
                            "See https://github.com/kernc/backtesting.py/issues/119",
```

Referenced issue https://github.com/kernc/backtesting.py/issues/119

**Comment by kernc** [comment]
How about _parent_?

**Comment by kernc** [comment]
If you have better ideas, freely open a PR! :smile:

**Comment by tankorsmash** [comment]
Will do, thanks!
