### ISSUE TITLE
Progress Indicator

### ISSUE THREAD

**Issue by TrifonT** [kernc/backtesting.py#187]
When using Backtest.optimize on big data (e.g. 1 min bars for some years) it takes some hours to complete.

It would be nice to have some reporting of the progress made so far, for example number of tries completed.

**Comment by kernc** [comment]
> nice to have some reporting of the progress made so far

[tqdm](https://github.com/tqdm/tqdm#installation) is used if installed. For best tqdm experience in Jupyter Notebooks, you also need [ipywidgets](https://github.com/jupyter-widgets/ipywidgets#install).

> Backtest.optimize on big data takes some hours to complete.

Do look at [`max_tries=` parameter or model-based optimization](https://kernc.github.io/backtesting.py/doc/examples/Parameter%20Heatmap%20&amp;%20Optimization.html) to limit the search space.

**Comment by TrifonT** [comment]
Great, thank you!
