### ISSUE TITLE
Debugging on specific date

### ISSUE THREAD

**Issue by s-kust** [kernc/backtesting.py#188]
I need something like this to work:

```py
from IPython.core.debugger import set_trace
...
    def next(self):
        if self.data.index[-1] == THE DESIRED DATE HERE:
        set_trace()
```
How to do that?

**Comment by kernc** [comment]
You need to know what `self.data.index[-1]` _is_ to compare it. In case of datetime index, it happens to be a [`pandas.Timestamp`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html). Something like this would work:
```py
    if self.data.index[-1] == pd.Timestamp('2019-10-18'):
        breakpoint()
```

**Comment by s-kust** [comment]
Thank you.

I have determined that the following also works:

```
from datetime import datetime
...
    def next(self):
         timestamp = "2014-04-01"
         if (self.data.index[-1] == datetime.strptime(timestamp,"%Y-%m-%d")):
             set_trace()
```
