### ISSUE TITLE
User Forum

### ISSUE THREAD

**Issue by jamhot1** [kernc/backtesting.py#189]
Not an issue

I really like this project. I think it has a lot of potential and I much prefer it over BT. Is there a support forum for it? If not, would anyone benefit from one being created? I would be happy to host one personally if it had enough interest.

Welcome to hear thoughts on it.

**Comment by eervin123** [comment]
Agreed, it is a great project and @kernc is fantastic at responding and engaging with those looking to help regardless of their [in]experience ;)  I aim to do what I can to contribute wherever possible.

**Comment by jamhot1** [comment]
Yes @kernc makes a lot of effort to answer noob questions (myself included) A forum would make a great addition and would probably help Kernc to concentrate on actual problems/bugs rather than programming tips. Platforms such as Quantopian seem to benefit greatly by harnessing a community.

**Comment by kernc** [comment]
GitHub kindly notified me it had made available a new feature: discussions.

Therefore, despite knowing full well that putting further reliances onto Microsoft's stack will bite us eventually, with minimal effort involved, say welcome to the [official backtesting.py discussion forum](https://github.com/kernc/backtesting.py/discussions). Hope I find you both participating regularly! :smile:

@jamhot1 If you want to host a related unofficial forum yourself, obviously welcome. It's a fun endeavor when you're young.

**Comment by ufuktasdan** [comment]
### How can I create optimization class so that I can collect more optimization?

I can optimize the strategy like:

stats_optimized, heatmap = bt.optimize(
    length=range(2,50,1),
    maximize="Sharpe Ratio",
    return_heatmap=True
)

However when I made a class to create more optimizations and call the class

class OptimizeParameters():
    def __init__(self):
        cash = cash
        my_data = test._read_file(self.address)
        strat = My_Strat
        self.bt = Backtest(my_data, strat, cash=cash)
        self.optimize()
        
    def optimize(self):
        stats_optimized, heatmap = self.bt.optimize(
            length=range(2,50,1),
            maximize="Sharpe Ratio",
            return_heatmap=True
        )
        
 RuntimeError: Indicator "Bollinger(1,1)" errored with exception: TA_BBANDS function failed with error code 2: Bad Parameter (TA_BAD_PARAM)
 
 I don't think Talib has problem, but I guess it is because of self.bt cannot take the values from my_data.

**Comment by Aditya365x** [comment]
i am creating a tool that will combine the news+ Price to predict the  buy and sell moves and i will use this repo in backtesting my stratgy.
