### ISSUE TITLE
Snipped example does not work on colab

### ISSUE THREAD

**Issue by maliozer** [kernc/backtesting.py#191]
### Expected Behavior
Snipped example output on documentation

### Actual Behavior
Backtesting example does not work returns this
ImportError: cannot import name 'values_from_object'

### Steps to Reproduce

1.
2.
3.

### Additional info

- Backtesting version: 0.?.?

**Comment by kernc** [comment]
What's the full traceback? Can you provide some help on how to reproduce the issue? All examples work for me on Colab after I `!pip install backtesting`.

**Comment by maliozer** [comment]
I figure out the other packages which I try yo use with backtesting somehow changes pandas version, it wasn't about your library, sorry.
