### ISSUE TITLE
Doc Suggestion: Answer question on StackOverflow

### ISSUE THREAD

**Issue by eervin123** [kernc/backtesting.py#192]
In trying to help this project get a little more exposure I noticed the following unanswered question on StackOverflow.  Not sure if anyone here would like to take a stab at it.  

**Backtesting trading strategy using backtesting.py**
https://stackoverflow.com/questions/61580922/backtesting-trading-strategy-using-backtesting-py

I would try to but I'm not sure I fully understand what they were looking to do.

**Comment by kernc** [comment]
Thanks! Featuring unsupported v0.1 API, that question looks too out-of-date to answer. :flushed:
