### ISSUE TITLE
Separate statistics for long and short trades?

### ISSUE THREAD

**Issue by s-kust** [kernc/backtesting.py#194]
After the backtest run, we see the statistics. It is very good! Is there any simple way to see that statistics separately for long ans short trades?

**Comment by kernc** [comment]
No "simple" way. You'd have to analyze [`stats._trades`](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Trade-data) yourself.

Might be up for exposing `compute_stats(trades: List[Trade]) -> pd.Series` in `backtesting.lib` module if someone contribs it. :+1:

**Comment by s-kust** [comment]
`compute_stats`

Is it possible to call that function explicitly somehow to obtain separate statistics for long and short trades?

**Comment by kernc** [comment]
It is since v0.3.2 possible to use [`backtesting.lib.compute_stats`](https://kernc.github.io/backtesting.py/doc/backtesting/lib.html#backtesting.lib.compute_stats) and do something like:
```py
stats = Backtest(GOOG, MyStrategy).run()
only_long_trades = stats._trades[stats._trades.Size > 0]
long_stats = compute_stats(stats=stats, trades=only_long_trades,
                           data=GOOG, risk_free_rate=.02)
```
