### ISSUE TITLE
ExitPrice was not the right one

### ISSUE THREAD

**Issue by abdel-ely-ds** [kernc/backtesting.py#206]
Hello I'm testing a strategy for which all the orders are bracket orders (stop_price, limit price, target price, sl_price are all specified). However I noticed that the exit price for some trades are < target price as you can see in the screenshot below

![image](https://user-images.githubusercontent.com/76486913/103022431-3d1bdf80-454c-11eb-9d3c-37540a23e77e.png)

![image](https://user-images.githubusercontent.com/76486913/103022588-9be15900-454c-11eb-87cc-ccc9e715ad4a.png)

Any Help ? Thank you

**Comment by kernc** [comment]
You place a short order and don't [backtest with `hedging=True`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest)?

**Comment by abdel-ely-ds** [comment]
It's a long order as you can see in the screenshot. I backtest with default params so hedging= False 

![image](https://user-images.githubusercontent.com/76486913/103027462-33977500-4556-11eb-9691-dfe04cef617b.png)

**Comment by kernc** [comment]
You run with [`exclusive_orders=True`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest), thus your current trade closes when you open a new buy order on (likely) the previous bar.

**Comment by abdel-ely-ds** [comment]
You mean that if I'm on a trade and then I place an order, my trade will close even if my order is not filled( not executed). Is that what you mean ? Should I keep exclusive_orders = False ?

**Comment by kernc** [comment]
> Should I keep exclusive_orders = False ?

If you don't want new orders to auto-close/cancel existing trades, apparently.

https://github.com/kernc/backtesting.py/blob/bbcb7bac8ffe65a5002edfcdf8bc50f92eaca2b9/backtesting/backtesting.py#L719-L728

**Comment by abdel-ely-ds** [comment]
Thank you everything works
