### ISSUE TITLE
Question: How to explicitly close a trade from a strategy  

### ISSUE THREAD

**Issue by Priyedev** [kernc/backtesting.py#222]
I am new to backtesting framework and recently learned python so need some help to implement a strategy, I want to implement a strategy which opens long or short trades without any stop loss and take profit level. I get that I can do that using self.buy() and  self.sell() methods of strategy class as in examples but I am not sure _how I close a trade_ as there's no self.close(). My strategy may have multiple long and short trades open at same time and each trade needs to be explicitly closed by strategy based on certain criteria (not by stop loss or take profit). I get that I need to have exclusive_orders=False. Do I need to loop through all open positions or trades and then call close on Position or Trade, if so how do I uniquely identify a Position or Trade? would be helpful if you can point me to or provide a related example snippet.
Thanks

**Comment by kernc** [comment]
See https://github.com/kernc/backtesting.py/issues/43.

As some general guidance, first read through [the tutorials](https://kernc.github.io/backtesting.py/doc/backtesting/#tutorials), then go over the [available API](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html), so you see what's possible.

Other than that, [use the search](https://github.com/kernc/backtesting.py/issues?q=is%3Aissue+label%3Aquestion), use [discussions](https://github.com/kernc/backtesting.py/discussions), find Python help on [StackOverflow](https://stackoverflow.com/).

Thanks!

**Comment by kernc** [comment]
Oh:

> Do I need to loop through all open positions or trades and then call close on Position or Trade, if so how do I uniquely identify a Position or Trade?

Yes. You can identify them by any Python object properties you attach to them. :man_shrugging:

**Comment by Priyedev** [comment]
Thanks @kernc , really appreciate your prompt response.  #200 is the one I need for tagging, will keep an eye on it when its merged
