### ISSUE TITLE
How to place exact dollar value to buy/sell

### ISSUE THREAD

**Issue by adamrg73** [kernc/backtesting.py#226]
var size
Order size (negative for short orders).

If size is a value between 0 and 1, it is interpreted as a fraction of current available liquidity (cash plus Position.pl minus used margin). A value greater than or equal to 1 indicates an absolute number of units.

I dont understand how to know how much dollars the size is if its greater than 1.

I want to be able to do for example, 1 contract of XYZ/USD = $3.91 USD

I want to be able to work with numbers like that and place orders and do position sizing with this type of contracts.
Thanks

**Comment by kernc** [comment]
> A value greater than or equal to 1 indicates an absolute number of units.

If one unit of asset (e.g. a contract) costs $3.91 and you want to spend $10, you just have to figure out how many (whole) _units_ fit in to sum at most $10. Basic arithmetic. Does this help?

Please also review [the existing FAQ](https://github.com/kernc/backtesting.py/issues?q=label%3Aquestion+). This sort of question had been answered a couple times already.

**Comment by adamrg73** [comment]
Hi I checked some your reply on another post, it says:

current_price = self.data.Close[-1]
order_size = 100 // current_price


so if YFIUSD last close price = 36521
I wana buy 1 contract of that which is on the exchange, 36521 / 10000 = $3.65

so then on your backtesting.py i put:

current_price = self.data.Close[-1]
order_size = 100 // current_price


I get 0. No trades execute.
?

**Comment by adamrg73** [comment]
?

**Comment by kernc** [comment]
```py
order_size = 100 // current_price
```
from https://github.com/kernc/backtesting.py/issues/137 indicates the number of units fitting into _$100_ allowance. In your case:
```
order_size = 100 // 3.65  # should be: 27
```
In that case, also make sure your input dataframe is denominated in unit prices (e.g. $3.65), not contract prices ($36,521).

Alternatively, if you just want to sell one mini lot, pass:
```py
self.sell(size=10_000)
```

**Comment by nikolhaas65** [comment]
Hi, I have rediscovered the same issue and tried to find the root of that. 
Besides, the solution order_size = 100 USD // 100.000 USD (trade with 100 USD on BTC-PERPETUAL) will not work, because in this case order_size = 0.

my request
https://github.com/kernc/backtesting.py/issues/1198
