### ISSUE TITLE
Extra stats conditions when optimizing?

### ISSUE THREAD

**Issue by konradg40** [kernc/backtesting.py#234]
First of all, thank you for this wonderful library.

When I maximize sharpe ratio, I could get a very good sharpe but with higher volatility levels than I prefer.
My idea was to maximize sharpe ratio with a maximum volatility set, alternatively it would be nice if I could select the 
highest sharpe ratio runs (that I find acceptable) and then reorder those again based on the volatility level.
I tried to find the answer in the documentation without luck.
Any help would be appreciated.

**Comment by kernc** [comment]
[`Backtest.optimize(maximize=)` parameter](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.optimize) takes a _callable_ (function) that takes the [run stats](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.run) and returns an ordinal value. Some example functions you could use:
```py
# Sharpe over some threshold and with minimum volatility
maximize_func = lambda s: int(s['Sharpe Ratio'] > acceptable_threshold) * -s['Volatility (Ann.) [%]']
# Sharpe, divided by annual volatility
maximize_func = lambda s: s['Sharpe Ratio'] / s['Volatility (Ann.) [%]']
# Calmar ratio = rate of return over max drawdown
maximize_func = 'Calmar Ratio'

... = bt.optimize(..., maximize=maximize_func)

**Comment by konradg40** [comment]
Thank you for the quick and clear answer!
