### ISSUE TITLE
deprecated stuff

### ISSUE THREAD

**Issue by fritol** [kernc/backtesting.py#235]
### Expected Behavior

from backtesting import Backtest

bt = Backtest(GOOG, SmaCross, cash=10_000, commission=.002)
stats = bt.run()
stats

### Actual Behavior
FutureWarning: Index.is_all_dates is deprecated, will be removed in a future version.  check index.inferred_type instead
  if (not data.index.is_all_dates

FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  if len(data.columns & {'Open', 'High', 'Low', 'Close', 'Volume'}) != 5:

### Steps to Reproduce

from backtesting import Backtest

bt = Backtest(GOOG, SmaCross, cash=10_000, commission=.002)
stats = bt.run()
stats

### Additional info

- Backtesting version: 0.?.?

**Comment by kernc** [comment]
Thanks, fixed already in https://github.com/kernc/backtesting.py/commit/c2c334385a2598dd7e775b928f7eec568e5aba97, https://github.com/kernc/backtesting.py/commit/0f24dbf8a28078424da8661cfb53bf732253db71, now released as 0.3.1.
