### ISSUE TITLE
using tapy.py with backtesting.py

### ISSUE THREAD

**Issue by mahdishemshadi** [kernc/backtesting.py#240]
Hi
I wanna use indicators in [tapy.py](https://pypi.org/project/tapy/) but I got this error
```
RuntimeError: Indicator "" errored with exception: 'NoneType' object is not callable
```
what should I do to use these two classes together?

**Comment by kernc** [comment]
Can you provide a short example how you are using the lib?

**Comment by mahdishemshadi** [comment]
prices = pd.read_csv('زاگرس.csv')[-1000:]
prices = prices.rename(
    columns={'date': 'Date', 'open': 'Open', 'close': 'Close', 'high': 'High', 'low': 'Low', 'volume': 'Volume'})
prices.set_index(pd.DatetimeIndex(prices['Date']), inplace=True)
prices = prices.drop('Date', 1)
prices['Open'] = prices['Open'].astype('double')
prices['Close'] = prices['Close'].astype('double')
prices['High'] = prices['High'].astype('double')
prices['Low'] = prices['Low'].astype('double')
prices['Volume'] = prices['Volume'].astype('double')
indicators = Indicators(prices)
prices = indicators.df

class MRM(Strategy):

    def init(self):

        stock = self.data

        self.rsi = self.I(ta.RSI, stock.Close, 14)
        self.macd, self.macdsignal, self.macdhist = self.I(ta.MACD, stock.Close, 12, 26, 9)
        self.mfi = self.I(ta.MFI, stock.High, stock.Low, stock.Close, stock.Volume)
        self.ichi = indicators.ichimoku_kinko_hyo()
        
this is what I did. the previous error solved but now when I print self.ichi I got None in output

**Comment by mahdishemshadi** [comment]
The problem solved completely.
Thanks
