### ISSUE TITLE
Would it be possible to add a positive commission?

### ISSUE THREAD

**Issue by JanssensKobe** [kernc/backtesting.py#248]
I'm trying to backtest a limit orders based strategy on a crypto exchange named bybit. The problem is that you get rebates when you use limit orders. But I see I can't enter positive commissions (-0.00025). Would it be possible to change this?

```
AssertionError: commission should be between 0-10%, is -0.00025
```

**Comment by kernc** [comment]
For now, why not amend the line:
https://github.com/kernc/backtesting.py/blob/73e1534428fc2db9e681030862133b5067508520/backtesting/backtesting.py#L667
in you own copy, and try it out.

Do report if anything breaks.

**Comment by JanssensKobe** [comment]
Thanks!

**Comment by kernc** [comment]
Did you solve it? Does it work?

**Comment by JanssensKobe** [comment]
Yeah I changed the line to this and everything worked afterwards, with the results I was expecting.

```python
 assert -0.1 <= commission < .1, f"commission should be between -10% -> 10%, is {commission}" 
```

**Comment by kernc** [comment]
If you PR it with text `... between -10% (e.g. market-maker's rebates) and 10% (fees)`, I'll accept it.
