### ISSUE TITLE
Understand what is plotted

### ISSUE THREAD

**Issue by RusEu** [kernc/backtesting.py#25]
### Expected Behavior

On the example of the SMA strategy, it should buy when the fast sma crosses above slow sma, 
but i don't understand what it is plotted.

1. Which symbol represents the moment when the order has been executed ?
2. Is it Long/Short strategy, or Long only ?

### Actual Behavior

![image](https://user-images.githubusercontent.com/11183790/68161672-a6aaea00-ff56-11e9-9d5e-b5df5e6ade96.png)

### Steps to Reproduce

1. On any example of the documentation

### Additional info

- Backtesting version:

Documentation website

**Comment by RusEu** [comment]
After making a little research I realized that:

Arrow down => open trade
Arrow up => close trade

Thank you for the great library you developed!

**Comment by kernc** [comment]
Triangle = long; inverse triangle = short. There are as of yet no strike indicators, just those at position close.

On your chart, the first large red candle in the first rectangle results in a bearish cross. You enter short on the next doji's open, exiting with a loss some six green candles later. Etc.
