### ISSUE TITLE
Is it possible to optimize based on multiple variables?

### ISSUE THREAD

**Issue by Gladi-iwnl** [kernc/backtesting.py#256]
Is it possible to optimize based on multiple variables? Or set the constraint to a value from the results?

Example:
```py
stats = backtest.optimize(
    n1=range(10, 110, 10),
    n2=range(20, 210, 20),
    constraint=stats['Max. Drawdown [%]'] < 20,
    maximize='Return [%]]')
```

**Comment by kernc** [comment]
> Or set the constraint to a value from the results?

Constraint is a function that takes parameter combination and either marks it admissible (acceptable or valid) or not. It operates on combinations of parameters (optimization variables) _way before_ we obtain the backtest results. So, no.

I think what you want is [`maximize=`, which can also be a callable](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.optimize) that takes _results_ and returns a _value_, the greater the better. Like:
```py
def maximize(stats):
    if stats['Max. Drawdown [%]'] > 20:
        return -np.inf  # i.e. worst
    return stats['Return [%]']

stats = bt.optimize(..., maximize=maximize)
```

**Comment by Gladi-iwnl** [comment]
So if I use this maximize function, I would only get returns where the Max. Drawdown is higher than -30?
´´´python
def maximize(stats):
    if stats['Max. Drawdown [%]'] > -30:
        return stats['Return [%]']

stats, heatmap = bt.optimize(
    p1=range(1,6,1),
    p2=range(1,11,1),
    p3=range(3,20,1),
    maximize=maximize,
    return_heatmap=True)

print(heatmap.sort_values().iloc[-20:])
´´´
Also, when I try to run this optimization and sort the heatmap I get a TypeError:
´´´
  File "/run/media/gladi/B204D33B04D300F1/Work/backtestingTryout/MAShiftSl.py", line 64, in <module>
    print(heatmap.sort_values().iloc[-20:])
  File "/home/gladi/.local/lib/python3.9/site-packages/pandas/core/series.py", line 3260, in sort_values
    sorted_index = nargsort(values_to_sort, kind, ascending, na_position)
  File "/home/gladi/.local/lib/python3.9/site-packages/pandas/core/sorting.py", line 379, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: '<' not supported between instances of 'float' and 'str'
´´´

**Comment by kernc** [comment]
> ```python
> def maximize(stats):
>     if stats['Max. Drawdown [%]'] > -30:
>         return stats['Return [%]']
> ```

No, with maximize function as above, you have an `else` branch you're not handling. The later `TypeError` is probably a consequence of implicitly returned `None` value.
