### ISSUE TITLE
Create an instance of the Strategy class

### ISSUE THREAD

**Issue by mahdishemshadi** [kernc/backtesting.py#259]
### Steps to Reproduce

1.
2.
3.

### Additional info

- Backtesting version: 0.?.?

**Comment by mahdishemshadi** [comment]
Hi. How can I create an instance of the Strategy class?

**Comment by kernc** [comment]
You don't. [`Backtest`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest) takes the sub-class directly, not the instance.
