### ISSUE TITLE
Position Open Price

### ISSUE THREAD

**Issue by tamerb2050** [kernc/backtesting.py#27]
### Expected Behavior
`position.open.price `should be 0.00 after closing position.

### Actual Behavior
![Ekran Alıntısı](https://user-images.githubusercontent.com/51494556/68876013-d5724e80-0714-11ea-8946-17be27cfb1d2.PNG)

- Backtesting version: 0.1.2

**Comment by kernc** [comment]
After closing the position, `Position.open_price`, `Position.open_time`, and `Position.pl_pct` should evaluate to 0. :+1:

Care to open a pull request for it?
