### ISSUE TITLE
Resampling error: Multiprocessing AttributeError: '_Indicator' object has no attribute '_opts'

### ISSUE THREAD

**Issue by emiliobasualdo** [kernc/backtesting.py#283]
Hi @kernc, great simulator.
### Expected Behavior
I trying to test a strategy `for` many symbols `[btc-usd, eth-usd, ...]` while multiprocessing.
I believe the simulation is executed successfully. Now, the plotting function seems to be generating an error when Multiprocessing and plotting the Indicator.
When running a simple SMA simulation with `ThreadPoolExecutor`, the program executes & plots perfectly.
When running a simple SMA simulation with `ProcessPoolExecutor`, the plotting produces the following error.

After playing around with the `bt.plot()` parameters, I found out that the error only jumps when the `resample` parameter is set to a value different than True. Example below.

I'm having some hard time to understand why the `_opts` attribute is not assigned in `_Array.__new__` https://github.com/kernc/backtesting.py/blob/5e1acccb7b0c9c1f369531035a9c887736f92cc5/backtesting/_util.py#L48-L52

### Actual Behavior
```
Traceback (most recent call last):
  File "/Users/pilo/development/itba/pf/test/sma.py", line 94, in <module>
    bt.plot(plot_equity=True, superimpose=False, resample="5T",
  File "/Users/pilo/development/itba/pf/test/venv/lib/python3.8/site-packages/backtesting/backtesting.py", line 1704, in plot
    plot(
  File "/Users/pilo/development/itba/pf/test/venv/lib/python3.8/site-packages/backtesting/_plotting.py", line 185, in plot
    df, indicators, equity_data, trades = _maybe_resample_data(
  File "/Users/pilo/development/itba/pf/test/venv/lib/python3.8/site-packages/backtesting/_plotting.py", line 110, in _maybe_resample_data
    indicators = [_Indicator(i.df.resample(freq, label='right').mean()
  File "/Users/pilo/development/itba/pf/test/venv/lib/python3.8/site-packages/backtesting/_plotting.py", line 110, in <listcomp>
    indicators = [_Indicator(i.df.resample(freq, label='right').mean()
  File "/Users/pilo/development/itba/pf/test/venv/lib/python3.8/site-packages/backtesting/_util.py", line 83, in df
    df = pd.DataFrame(values.T, index=self._opts['data'].index,
AttributeError: '_Indicator' object has no attribute '_opts'

``` 

### Steps to Reproduce
I have made a very simplified version by forking the GOOG data with SMA twice.
```py
import multiprocessing as mp
from concurrent.futures import ProcessPoolExecutor

mp.set_start_method('fork')

class SmaCross(Strategy):
    def init(self):
        price = self.data.Close
        self.ma1 = self.I(SMA, price, 10)
        self.ma2 = self.I(SMA, price, 20)

    def next(self):
        if crossover(self.ma1, self.ma2):
            self.buy()
        elif crossover(self.ma2, self.ma1):
            self.sell()


run_list = [Backtest(GOOG, SmaCross, commission=.002, exclusive_orders=True),
            Backtest(GOOG, SmaCross, commission=.002, exclusive_orders=True)]

def bt_run(bt):
    bt.run()
    return bt

with ProcessPoolExecutor() as executor:
    bts = executor.map(bt_run, run_list)

for bt in bts:
    bt.plot(resample="1W") # <- if resample=True, no error occurs
```
### Additional info

I have also tried with 1M OHLC data of my own.
Moreover, when running with threads, the Indicator is plotted in the figure perfectly. When running with Process and `resample=True` the Indicator is not plotted.

- Backtesting version: 0.3.1

**Comment by kernc** [comment]
Thanks for the nice repro! Since [`ProcessPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor) pickles the objects it's passed between itself and children, I think the issue is that our `_Indicator` (`_Array`) doesn't provide [`__getstate__`/`__setstate__`](https://docs.python.org/3/library/pickle.html#object.__getstate__) methods to carry over its member attributes, or something like that.

**Comment by emiliobasualdo** [comment]
Like a charm!
