### ISSUE TITLE
Track the actions of the trade strategy

### ISSUE THREAD

**Issue by Gnommer** [kernc/backtesting.py#29]
if we say are defining the next in the strategy class like buy and sell actions how can we track this in the _trade_data object so we can track easily when the order was placed and when the broker executed the buy sell and hold to present in the plots ?

- Backtesting version: 0.1.2

**Comment by Gnommer** [comment]
@kernc any suggestions on the above issue ?

**Comment by kernc** [comment]
`results._trade_data`, as mentioned in https://github.com/kernc/backtesting.py/issues/4, is only available _after_ the simulation run. For the time being, if you need to query state _during_ the simulation, you should look into the properties of [`Position`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Position) (`Strategy.position`) and track state changes manually yourself.

**Comment by Benouare** [comment]
Just for help : 
```
final = pd.DataFrame()
final = final.append(trades[trades[["Entry Price"]].notnull().all(1)])
final = final.append(trades[trades[["Exit Price"]].notnull().all(1)])
final = final.sort_index()
```
It looks like this just shows the buy/close position dates.
