### ISSUE TITLE
View actual values used in strategy for each buy/sell decision

### ISSUE THREAD

**Issue by Emile-Strasheim** [kernc/backtesting.py#297]
Firstly, this is an awesome tool, thank you very much.

Is it possible to view the actual values used for each decision to buy or sell, as defined in the Strategy Class object? i.e. what was the values of the variables used to determine what decision should be made?

I have defined my own strategy, but I want to review the decisions to ensure that the strategy is executed correctly, i.e. the right values are used to make the decision.

**Comment by kernc** [comment]
You can access the strategy _instance_ (with its values) via `stats._strategy` as showcased in [the quick start example](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Optimization).

**Comment by Emile-Strasheim** [comment]
Ah, thank you so much.
