### ISSUE TITLE
Option to limit order size/exposure

### ISSUE THREAD

**Issue by adrianmiu** [kernc/backtesting.py#3]
Is there a way to place orders that are limited in size? 

I'm working on a Forex strategy where I want to specify the size of the order based on the SL/TP levels provided by a prediction model. Your library mentions that the Strategy.buy/sell methods use "all available funds" which cannot be used in this case.

Thank you!

**Comment by kernc** [comment]
Would you like to try to make a PR for it? I think API-wise, something like this might work?
```py
Strategy.buy(..., size: float = 1)  # percentage of cash
```

**Comment by adrianmiu** [comment]
I would if I were a python programmer. Unfortunately I'm just hacking around... started playing with python a month ago. With that being said, it is an interesting challenge but I won't make any promise :)

**Comment by Pk13055** [comment]
I have monkey patched the code to make it work with variable position sizing. I will clean it up and submit a PR.

**Comment by kernc** [comment]
@Pk13055 If you find time, I'd appreciate it! I know I've been looking into it briefly and it seemed harder than I was willing to handle at the time. :sweat_smile:

**Comment by packandsell** [comment]
Gents, I'm also working with FOREX markets and also with leverage of 1:100 and up. Usually my position size is estimated in so called Lots (100k USD), the money management would be 0.1 Lots per 1000 USD balance. Could you please advise on how to simulate this?

**Comment by hotsun** [comment]
I updated:

    @property
    def size(self):
        """Position size in units of asset. Negative if position is short."""
        return int(self._broker._position)

and it looks ok for me.
