### ISSUE TITLE
Main contributer using swastika in profile picture

### ISSUE THREAD

**Issue by dnandha** [kernc/backtesting.py#30]
I have a serious issue with the main contributer @kernc using a right-facing swastika as his profile picture. @kernc please explain or remove the use of the symbol.

**Comment by kernc** [comment]
It's a Buddhist swastika, not a Nazi swastika, obviously. I had assumed you in particular should be able to tell the difference. I don't think there's any meaning to what direction it's facing.

Does that answer your concerns?

**Comment by motey** [comment]
As an obviously European user with not any other hint to Buddhist culture references in your profile, it leads me to believe this is not a valid argue but a poor excuse. 
It is two different things if somebody with a visible Buddhist cultural background (e.g. linked to Tibetan user groups) uses a swastika vs a random European dude (e.g. linked to European usergroups) uses a swastika. 
Either you have absolutely no sensitivity for an issues like this or you are a fascist troll misusing a foreign culture for signalling your political views to peers. Both cases are problematic. I reported that issue to github.

**Comment by kernc** [comment]
@motey I have no understanding of religious or spiritual views ever being limited to any certain narrow geographical areas. I assure you your concerns are unfounded. Best wishes! 🖖

**Comment by motey** [comment]
> Guess we're lucky you even gave us two options? 

no problem mate.

>  I have no understanding of religious or spiritual views ever being limited to any certain narrow geographical areas

Yes, i am with you. But every rule has exceptions; Its a shame fascist did contaminate this originally Buddhist symbol, but it is what it is. In Europe this symbol is now related to hate,  racism, and genocide. Again, that is sad but, that is the is the situation.  Displaying a swastika, even if it is meant to represent a Buddhist symbol, can be highly insensitive and offensive to those who have been affected by the atrocities committed under the Nazi regime. It's crucial to be aware of the impact such a symbol can have on others.

There are many alternatives to show your relation to Buddhist culture/religion like the lotus flower, the Dharmawheel, Buddha himself and so on. Why would you, as a European, consist on using a swastika?

> Rest assured, your concerns are unfounded. Best wishes!

My concerns are not of matter here. The matter is how a European behaves on a global plattform, shrugging of any concerns related to a big historical issues. And for what? to just to stand the ground having a certain avatar picture.

**Comment by kernc** [comment]
> here in Europe

If you don't like the intonation in Europe, you can always fly elsewhere.

> "Works for me" is always a strong argument.
> I was offended
> but still it is highly problematic symbol

It's a good-enough argument. People can be offended by _anything_. It's not a virtue, the opposite is.
I can handle the mild controversy, most times, or at least have been able to for over a decade. Occasionally, I stumble upon a zealot. It's warming knowing they, even complete online strangers, have my good interest at their hearts!

Best wishes!
