### ISSUE TITLE
Start Tracking Backtest Results AFTER A Specific Datetime?

### ISSUE THREAD

**Issue by windowshopr** [kernc/backtesting.py#307]
I'm wanting to load in, say, last week's data for a stock (Monday to Friday), but I also need to include a few days prior to that in order to calculate the moving averages before that Monday AM. Is there a way to set a condition to make sure that trades don't actually start until the Datetime index is >= some specific date?

Using a simple example, I would envision it would work (pseudo) something like this, however not sure how to get it working:

```
class SmaCross(Strategy):
    def init(self):
        start_day = datetime.strptime("2021-04-05", "%Y-%m-%d")
        self.date = self.data.index

        price = self.data.Close
        self.ma1 = self.I(SMA, price, fast_ma)
        self.ma2 = self.I(SMA, price, slow_ma)


    def next(self):
        if crossover(self.ma1, self.ma2) and self.date >= start_day:
            self.buy()
        elif crossover(self.ma2, self.ma1) and self.date >= start_day:
            self.sell()
```

Would love some guidance to set the time constraint. Running Windows 10, Python 3.

**Comment by kernc** [comment]
See https://github.com/kernc/backtesting.py/issues/188.

**Comment by windowshopr** [comment]
I did see that post yes. So when we refer to "self.data.index[-1]", does that mean that it'll reference the most recent index in the series as it goes through the dataset?

**Comment by kernc** [comment]
Exactly, on each invocation of `next()`, `self.data.*[-1]` is the last, [most recent value](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data).
