### ISSUE TITLE
Is it possible to have a neutral position (cash) or is it long/short) only?

### ISSUE THREAD

**Issue by ogborstad** [kernc/backtesting.py#31]
I would like to test strategies that are long / cash and not only long / short. Is this possible?

**Comment by kernc** [comment]
Yes, you can close the position and cash out with [`Strategy.position.close()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Position.close), or by extending [`SignalStrategy`](https://kernc.github.io/backtesting.py/doc/backtesting/lib.html#backtesting.lib.SignalStrategy) that does that for you.
