### ISSUE TITLE
SMA optimisation example error

### ISSUE THREAD

**Issue by juanweber** [kernc/backtesting.py#32]
Hello!
Copy/pasting the example code for optimisation of the SMA strategy gives the following error:

`AttributeError: Strategy 'SmaCross' is missing parameter 'n1'. Strategy class should define parameters as class variables before they can be optimized or run with.`

Not sure of what's wrong.

**Comment by kernc** [comment]
Do you mean the example from [Quick Start User Guide](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html)?

You likely have an error in your paste. It should work (at least the demo examples run within CI do). Try here: [JupyterLab](https://mybinder.org/v2/gh/kernc/backtesting.py/master?urlpath=lab%2Ftree%2Fdoc%2Fexamples%2FQuick%20Start%20User%20Guide.ipynb)

**Comment by juanweber** [comment]
I copy/pasted from the quick start user guide and it works well!
I can't find the first source of where I did it in the beginning, my bad.
Happy holidays ;)
