### ISSUE TITLE
order is removed due to no enough cash/margin, however, it's a sell order

### ISSUE THREAD

**Issue by zillionare** [kernc/backtesting.py#328]
Currently position is long and there's buy trade in queue:

```
<Trade size=476 time=7- price=21.0- pl=652>
```

Now a sell signal is triggerred, and a sell order is placed, however, the order is removed/cancelled in `_process_orders` due to no cash/margin:

![图片](https://user-images.githubusercontent.com/7206696/116680575-6a870700-a9de-11eb-800c-932a8faf957f.png)

logger is added by me.

Since this is a sell order, why we need cash/margin?

### Expected Behavior
if the order is for sell, we need to check if we hold long position; otherwise, check if cash is enough.
### Actual Behavior
the sell order is discarded due to no cash/margin. Thus no more buy/sell even buy/sell signals are fired.

### Steps to Reproduce

1. trigger a long trade with size 0.9999
2. trigger a sell order, see if it's placed
3.

### Additional info

- Backtesting version: 0.3.1

**Comment by gaborvecsei** [comment]
(I am not familiar with the codebase, I am a new user)

> Since this is a sell order, why we need cash/margin?

Actually I think we need "some" cash as we need to pay a commission.

**Comment by kernc** [comment]
The commission is already accounted for with spread at trade entry. If we're just selling (buying) some units we already have (owe), we should not be checking available cash.

**Comment by gaborvecsei** [comment]
@kernc, just for the sake of my understanding:

- When we are closing a position (selling), there is no commissions we need to pay?

I understand that there is a commission when we enter a trade (e.g. buy a stock), but we should also pay a commission when we are selling. At elast for *Interactive Brokers*, we pay commission when closing a position. (And as I know this is the same for most of the cases).

**Comment by kernc** [comment]
> I understand that there is a commission when we enter a trade (e.g. buy a stock), but we should also pay a commission when we are selling. At elast for _Interactive Brokers_, we pay commission when closing a position. (And as I know this is the same for most of the cases).

Ah, this already came up in https://github.com/kernc/backtesting.py/issues/149. The idea then was to just pass `Backtest(commission=2*real_commission)`, which is approximately valid for all but the instruments with very wide price fluctuation.
