### ISSUE TITLE
Error when plotting a large amount of data

### ISSUE THREAD

**Issue by thomasd3** [kernc/backtesting.py#35]
I have a very simple test:

```
df=load_dataframe(r’./historical.xlsx')
df = df.set_index('date')

# the backtest is a strategy that does nothing for now
bt = Backtest(df, empty_strategy, cash=1, commission=.002)
bt.run()

# and the display simply
bt.plot()

```

with all the data, bt.plot() will fail with _Javascript Error: Maximum call stack size exceeded._

if I add:

```
df = df[0:50000]
```

then the display works fine.

I have about 1.3M data points (and need them); is there a way to resample the data but ONLY for the display?

**Comment by thomasd3** [comment]
I just realized that even with 50k data, it fails, but 20k is fine.

**Comment by kernc** [comment]
> is there a way to resample the data but ONLY for the display?

Not presently. I think the exact amount might depend on available RAM and web browser configuration. Would certainly welcome automagically downsampling to a reasonable amount of candles for plot. :+1:
