### ISSUE TITLE
How to set trailing stop-loss?

### ISSUE THREAD

**Issue by Pilipets** [kernc/backtesting.py#358]
`self.buy(size=pos_size/price, sl=price - atr)`

This is the way I'm setting stop_loss in my strategy, but how can I make it trailing?

https://www.investopedia.com/articles/trading/08/trailing-stop-loss.asp

**Comment by kernc** [comment]
I guess you must have found [the example](https://kernc.github.io/backtesting.py/doc/examples/Strategies%20Library.html) with [`backtesting.lib.TrailingStrategy`](https://kernc.github.io/backtesting.py/doc/backtesting/lib.html#backtesting.lib.TrailingStrategy) or [one of the prior discussions](https://github.com/kernc/backtesting.py/discussions/238) or [`Trade.sl` in API docs](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Trade.sl).
