### ISSUE TITLE
'Buy & Hold Return [%]' never seem to return negative values

### ISSUE THREAD

**Issue by a-holm** [kernc/backtesting.py#36]
### Expected Behavior
bt.run() should produce statistics where 'Buy & Hold Return [%]' returns a negative value.

### Actual Behavior
'Buy & Hold Return [%]' always returns a positive value

### Steps to Reproduce

1. Get data where you know 'Buy & Hold Return [%]' returns a negative value. Put it into a pandas dataframe like normal (called df).
2. run something like this:
```
bt = Backtest(df, EmaCross, cash=10, commission=.002)
bt.run()
```
3. 'Buy & Hold Return [%]' is positive.

### Additional info

The reason for this bug is in line 906 of backtesting/backtesting.py

`s.loc['Buy & Hold Return [%]'] = abs(c[-1] - c[0]) / c[0] * 100  # long OR short
`

returns the absolute value. It loses very important information. Anyone who needs the absolute value can always take the absolute value of the returned value. But now the information is lost if 'Buy & Hold Return [%]' is positive or negative. This makes it useless to compare in both long and short strategies.

**Comment by kernc** [comment]
Mind the comment. In this case, Buy&Hold is a hypernym for Buy&Hold _and_ Sell&Hold, namely any long-term position, taken along the foreseen direction of the underlying market.

Otherwise, even a blank strategy that does no trading whatsoever would fare better than B&H with negative return.

> This makes it useless to compare in both long and short strategies.

I'm not sure I understand. Can you elaborate?

**Comment by kernc** [comment]
Lacking further discussion on this issue, I find the current adversarial behavior preferred.

**Comment by kernc** [comment]
This was changed as of https://github.com/kernc/backtesting.py/commit/3045b64635fe9e5af51046b7bdf7cdfcbf375c1e.
