### ISSUE TITLE
How to pass parameters into strategy?

### ISSUE THREAD

**Issue by arisliang** [kernc/backtesting.py#378]
As the [documentation](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#gsc.tab=0) indicates, the Backtest takes the subclass of Strategy not instance.

However, there may be cases where we want to pass parameters into strategy. Usually a constructor would do, but since we can't make an instance, so how do we pass parameters into strategy?

**Comment by kernc** [comment]
> Keyword arguments are interpreted as strategy parameters.

in [`Backtest.run()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.run).

**Comment by arisliang** [comment]
Can we have an example for the passing format? I tried a few but doesn't work.

**Comment by kernc** [comment]
Can you show an example of what you've tried?

**Comment by arisliang** [comment]
I've tried to put the parameter in the strategy constructor.

```
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

from backtesting.test import SMA, GOOG


class SmaCross(Strategy):
    n1 = 10
    n2 = 20

    def __init__(self, p1: int):
        super(SmaCross, self).__init__()

        self.p1 = p1

    def init(self):
        close = self.data.Close
        self.sma1 = self.I(SMA, close, self.n1)
        self.sma2 = self.I(SMA, close, self.n2)

    def next(self):
        if crossover(self.sma1, self.sma2):
            self.buy()
        elif crossover(self.sma2, self.sma1):
            self.sell()


bt = Backtest(GOOG, SmaCross,
              cash=10000, commission=.002,
              exclusive_orders=True)

output = bt.run(p1=1)
bt.plot()
```

**Comment by arisliang** [comment]
I switched to class variable, and it worked.

```
class SmaCross(Strategy):
    n1 = 10
    n2 = 20

    p2 = 2
    p3 = 3

    def init(self):
        close = self.data.Close
        self.sma1 = self.I(SMA, close, self.n1)
        self.sma2 = self.I(SMA, close, self.n2)

    def next(self):
        if crossover(self.sma1, self.sma2):
            self.buy()
        elif crossover(self.sma2, self.sma1):
            self.sell()


print(GOOG.head())
bt = Backtest(GOOG, SmaCross,
              cash=10000, commission=.002,
              exclusive_orders=True)

output = bt.run(p2=4, p3=6)
bt.plot()
```

**Comment by ReposCollector** [comment]
Hi, the same approach does not work for 'optimize'
How can I pass the parameters when using 'optimize'?

**Comment by PilotGFX** [comment]
in backtesting.py otpimize_grid class i added best_params in the return,  then when you run the backtest as well as the stats and heatmap you can add a third variable which will get the best_params, then you can just do like this:  strategyclass.var1 = best_params[0] strategyclass.var2 = best_params[1]  . alternatively without editing backtesting.py you can also make some code that extracts the optimized settings out of the string of _strategy . i havent tried on _optimize_skopt class yet, but maybe i have to resort to this extract from string method.

**Comment by PilotGFX** [comment]
> Hi @kernc , the same approach does not work for 'optimize' How can I pass the parameters when using 'optimize'?
in backtesting.py otpimize_grid class i added best_params in the return,  then when you run the backtest as well as the stats and heatmap you can add a third variable which will get the best_params, then you can just do like this:  strategyclass.var1 = best_params[0] strategyclass.var2 = best_params[1]  . alternatively without editing backtesting.py you can also make some code that extracts the optimized settings out of the string of _strategy . i havent tried on _optimize_skopt class yet, but maybe i have to resort to this extract from string method.

**Comment by BradKML** [comment]
Thanks for the note, would use this with Ray-Tune and BOHB instead of the native optimizer, will share in the Discussions
