### ISSUE TITLE
'legend' keyword is deprecated when running example

### ISSUE THREAD

**Issue by TroyHGP** [kernc/backtesting.py#38]
Hi there,

I am unable to run the example code. I've also attempted to use my own data and I receive the same error as when running the example. Any idea how to make this run?

I get this code repeated a few times when I attempt to run it -
`D:\Programs\Programming\Python\lib\site-packages\bokeh\util\deprecation.py:68: BokehDeprecationWarning:

'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead`

Thank you in advance.

**Comment by kernc** [comment]
Fixed in https://github.com/kernc/backtesting.py/commit/f415e7a591e50a5c95965a22227e88032cc8cde7. Hope to be released soon, or welcome to checkout master if you can't wait. :smile:

**Comment by TroyHGP** [comment]
Great thank you!
