### ISSUE TITLE
Documentation of crossover

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [kernc/backtesting.py#386]
This is about the documentation of crossover.

https://kernc.github.io/backtesting.py/doc/backtesting/lib.html#backtesting.lib.crossover

It just says `Return True if series1 just crossed over series2.` Does it mean series1 crosses series2 from below or from above?

https://www.investopedia.com/terms/c/crossover.asp

Investopedia says the following.

`The crossover is a point on the trading chart in which a security's price and a technical indicator line intersect, or when two indicators themselves cross.`

It does not mention whether it is crossing from above or from below. So I'd assume `crossover` means from below and above.

https://github.com/kernc/backtesting.py

But the example on the README seems to mean `crossover` is from below. If this is the case, should the function `crossover()` be renamed to `crossoverfrombelow()`?

### Expected Behavior

NA

### Actual Behavior

NA

### Steps to Reproduce

NA

### Additional info

NA

**Comment by zlpatel** [comment]
Per my understanding, Crossover is by default considered as "from below". Here's a snip from investopedia.(https://www.investopedia.com/terms/g/goldencross.asp)

>  How do I identify a golden cross on a chart?

> The golden cross occurs when a short-term moving average crosses over a major long-term moving average to the upside and is interpreted by analysts and traders as signaling a definitive upward turn in a market. Some analysts define it as a crossover of the 100-day moving average by the 50-day moving average; others define it as the crossover of the 200-day average by the 50-day average. Basically, the short-term average trends up faster than the long-term average, until they cross. 
 
Crossover is used in reference to series 1 and series 2. you switch their position in the crossover function when you need to detect the opposite crossover. But the function stays the same. 

Crossover(A,B) where A crosses over B. Meaning of crossover will change depending on whether A is faster moving data or slower.

**Comment by prRZ5F4LXZ** [comment]
Then, an alternative name could be `goldencross`.

But the name of `crossover` is still ambiguous as it does not say the direction of cross. But the implementation of the `crossover` function clearly means from below. Therefore, I think the name of the `crossover()` function should be renamed to reflect what it actually does.

**Comment by rbscholtus** [comment]
One indicator goes **over** (/above) another so it crosses **over**, implying it's from below to above. It's not terribly black and white in it's meaning but not really a problem either. I'll try to make a pull request for improved documentation if I get a chance.

We could potentially add `crossunder()` except this word isn't backed by proper English.

Golden crosses and death crosses are more specific than just one indicator crossing another in general.

**Comment by prRZ5F4LXZ** [comment]
https://www.dictionary.com/browse/crossover

I don't think that is a correct interpretation of 'crossover'. 'over' just means that one line is crossed on top of another one ('top' in the direction perpendicular to the plane in which the lines are drawn).

This is clearly demonstrated in the context of a figure in genetics in which there is no `above` or `below` implied by `over`.

https://www.genome.gov/genetics-glossary/Crossing-Over

**Comment by rbscholtus** [comment]
Genetics is a little different. We're talking about one (financial) value going over another, so, not under.
I know there could be interpretations, but this is mine.

**Comment by prRZ5F4LXZ** [comment]
I know that is for genetics. But I am talking about English. The genetics example just proves that 'over' does not mean 'above'.

**Comment by eervin123** [comment]
To me, a native English speaker and someone who has been in finance for `over` 20 years. See what I did there. ;) 

I read this perfectly as `over` meaning above. Every chart that I think of in finance is a plane where up/over/above/rising etc. are all directionally relevant. These are not floating objects in a spatial void where the concept of up down, left and right are absent. When I hear,  "When the fast moving average crosses `over` the slow moving average, you do X" I instantly picture the fast moving average going higher, or above the slow moving average. So, when A `crosses` `over` B is perfectly understandable in the context of financial assets rising and falling. 

I suppose, with no context, as in the dictionary above for railroad tracks, on the horizontal plane, crossover means left to right and that would indeed be ambiguous, but this is just one person's opinion. 

I'm not sure this needs any further explanation, but to clear any doubt, I suppose you could add a statement to the documentation.

**Comment by fortesantonio** [comment]
Two ideas that might work for Backtesting.py crossovers Libraries ;

def crossesOver(stream1, stream2):
    if isinstance(stream2, int) or isinstance(stream2, float):
        if stream1[len(stream1)-1] <= stream2:
            return False
        else:
            if stream1[len(stream1)-2] > stream2:
                return False
            elif stream1[len(stream1)-2] < stream2:
                return True
            else:
                x = 2
                while stream1[len(stream1)-x] == stream2:
                    x = x + 1
                if stream1[len(stream1)-x] < stream2:
                    return True
                else:
                    return False
    else:
        if stream1[len(stream1)-1] <= stream2[len(stream2)-1]:
            return False
        else:
            if stream1[len(stream1)-2] > stream2[len(stream2)-2]:
                return False
            elif stream1[len(stream1)-2] < stream2[len(stream2)-2]:
                return True
            else:
                x = 2
                while stream1[len(stream1)-x] == stream2[len(stream2)-x]:
                    x = x + 1
                if stream1[len(stream1)-x] < stream2[len(stream2)-x]:
                    return True
                else:
                    return False


def crossesUnder(stream1, stream2):
    if isinstance(stream2, int) or isinstance(stream2, float):
        if stream1[len(stream1)-1] >= stream2:
            return False
        else:
            if stream1[len(stream1)-2] < stream2:
                return False
            elif stream1[len(stream1)-2] > stream2:
                return True
            else:
                x = 2
                while stream1[len(stream1)-x] == stream2:
                    x = x + 1
                if stream1[len(stream1)-x] > stream2:
                    return True
                else:
                    return False
    else:
        if stream1[len(stream1)-1] >= stream2[len(stream2)-1]:
            return False
        else:
            if stream1[len(stream1)-2] < stream2[len(stream2)-2]:
                return False
            elif stream1[len(stream1)-2] > stream2[len(stream2)-2]:
                return True
            else:
                x = 2
                while stream1[len(stream1)-x] == stream2[len(stream2)-x]:
                    x = x + 1
                if stream1[len(stream1)-x] > stream2[len(stream2)-x]:
                    return True
                else:
                    return False
