### ISSUE TITLE
How to add custom data

### ISSUE THREAD

**Issue by codingalex** [kernc/backtesting.py#39]
I would like to use other data such as sentiment for my backtests. Is there any way to custom data to self.data?

**Comment by kernc** [comment]
Whatever columns you pass in in the initial dataframe should remain available. From the [docs](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Data):
> Your data frames can have other columns

Is this what you're looking for?

**Comment by codingalex** [comment]
That's true! Thank you so much :)
