### ISSUE TITLE
how to remove warning: HSL() was deprecated in Bokeh 2.3.1.....

### ISSUE THREAD

**Issue by wenny0501** [kernc/backtesting.py#396]
### Actual Behavior

Hi,
I link this module, backtesting.
thank you for your work.
everytime I run backtesting, a warning comes:
BokehDeprecationWarning: HSL() was deprecated in Bokeh 2.3.1 and will be removed, use RGB() or named colors instead.

BokehJS 2.3.2 successfully loaded.

how can we remove this warning?

![image](https://user-images.githubusercontent.com/68882045/123869403-ee863e00-d8fe-11eb-9842-d60041232813.png)

- Backtesting version: 0.3.1

**Comment by Hungryarie** [comment]
I've got the same issue here

**Comment by kernc** [comment]
Fixed in https://github.com/kernc/backtesting.py/commit/6200869e7208eb6c3a2272e3f90457144641b9a0, available in v0.3.2. `pip install -U backtesting`

**Comment by Hungryarie** [comment]
thanks! confirmed that the warning is gone
