### ISSUE TITLE
Way to access equity values, individual trade returns, ...

### ISSUE THREAD

**Issue by fabio11c** [kernc/backtesting.py#4]
Is there a way to extract the returns of the strategy and not only have a plot?

**Comment by kernc** [comment]
```py
bt = Backtest(...)
result = bt.run()

result._trade_data  # type: pd.DataFrame
```
In `_trade_data`, you can find columns such as changing Equity values, P/L of individual trades, ...
https://github.com/kernc/backtesting.py/blob/a7d1d4f3fa658290182dfa2fdbf69bffe6a8f018/backtesting/backtesting.py#L849-L865

Note, this is currently private API, so it may change.

**Comment by fabio11c** [comment]
Ok, thanks...what do you mean with a "private API"?

**Comment by fabio11c** [comment]
`result._trade_data` is not an atribute of `bt.run()`. Im still having the issue.

**Comment by kernc** [comment]
`bt.run()._trade_data`

It should be. It's the way plotting functions access raw trading data:

https://github.com/kernc/backtesting.py/blob/a7d1d4f3fa658290182dfa2fdbf69bffe6a8f018/backtesting/backtesting.py#L911
https://github.com/kernc/backtesting.py/blob/a7d1d4f3fa658290182dfa2fdbf69bffe6a8f018/backtesting/_plotting.py#L80

**Comment by kernc** [comment]
> what do you mean with a "private API"?

It's undocumented API, without reliability (change) guarantees, not meant for public consumption. It's why the attribute is prefixed with an underscore, following [a common Python convention](https://docs.python.org/3/tutorial/classes.html#private-variables).

You are welcome to use it in testing, though. Maybe even let me know how you are using it and whether you need/expect something else from/like it too. :+1:

**Comment by packandsell** [comment]
Hello, everyone. Is there a way to have final PnL in pips or calculate it somehow?

**Comment by kernc** [comment]
<sup>Hello. :smiley: This is not a forum, and even the forums are clearer when restrained to one topic per thread.</sup> 

This might do it for you, within `Strategy.next()`:
```python
pl_pips = self.position.pl / self.data.pip
```
https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data

-----

Note to self: `data` should be better documented.

**Comment by kernc** [comment]
Oh, you mean final `result['P/L']`. I guess you can just divide it by pip size? If you don't know what that is, backtesting.py uses the following heuristic formula to determine it from Close values:
https://github.com/kernc/backtesting.py/blob/a7d1d4f3fa658290182dfa2fdbf69bffe6a8f018/backtesting/_util.py#L100-L101
