### ISSUE TITLE
pip is not working 

### ISSUE THREAD

**Issue by wblockchain** [kernc/backtesting.py#40]
### Expected Behavior
install via pip 

### Actual Behavior
i just tried to install using pip and i got unknown command. also we have an error here as of build status : https://travis-ci.org/kernc/backtesting.py
### Steps to Reproduce

1.
2.
3.

### Additional info

- Backtesting version:

**Comment by kernc** [comment]
> i got unknown command

https://pip.pypa.io/en/stable/installing/#do-i-need-to-install-pip

> an error here as of build status

The build issue is known. Should be fixed once https://github.com/mwouts/jupytext/issues/414 is released.
