### ISSUE TITLE
Passing Variables to Strategy

### ISSUE THREAD

**Issue by sumobull** [kernc/backtesting.py#41]
Hi,

Is there a way to pass a variable to the class being called by Backtest?  I would like to loop through my own strategy using range defined variables.  

Thanks in advance.

**Comment by kernc** [comment]
[`Backtest.run(**kwargs)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.run) will be set on the `Strategy` instance right after object instantiation and before `Strategy.init()` is called. It's similar with `Backtest.optimize(**kwargs)`.

If that's not _exactly_ what you're after, I'm afraid I didn't understand what you mean. :sweat_smile:

**Comment by sumobull** [comment]
I believe this is exactly what I am looking for.  I will test this evening.  Thanks!

**Comment by ali-meesam23** [comment]
It works once I execute .run()
but if I directly try to .optimzie(), the variable doesn't register.

Any suggestions?
