### ISSUE TITLE
Tulipy Library Usage

### ISSUE THREAD

**Issue by sumobull** [kernc/backtesting.py#42]
Do you have a quick functional example showing Backtesting working with tulipy? I can't seem to get the data structure correct when passing to self.I().

**Comment by kernc** [comment]
For an example with MACD, simply:
```py
self.I(ti.macd, self.data.Close, 2, 5, 9)
```
would work if it were not for bug https://github.com/cirla/tulipy/issues/30 (if you care enough, please upvote / raise your voice in that issue, or even maybe open a new issue — the community interest needs to be shown). The problem is that tulipy indicators return a shorter array, stripped of leading NaNs, so Backtesting complains since the result array is not of a matching size. I'm afraid for the time being, as the issue recommends, you'll have to pad the result arrays yourself:
```py
def tulip_pad(func, *args, **kwargs):
    result = func(*args, **kwargs)
    size = len(args[0])
    padded = np.r_[[np.nan]*(size - x.size), x]
    return padded

self.I(tulip_pad, ti.macd, self.data.Close, 2, 5, 9)
```

**Comment by sumobull** [comment]
Hi Kernc.

OK, so the behavior you are describing is what I saw regarding the mismatched array sizes.  I will test out the workaround and also open a new issue regarding.  Thanks again for the help with this.  Cool stuff.

**Comment by sumobull** [comment]
Kernc,

I am receiving the below error when trying to run the script w/the padding function being called.  Have any idea what is wrong?  Thanks again for the help.  

Traceback (most recent call last):
  File "./go_test", line 48, in <module>
    bt.run()
  File "/home/ej/bin/pyv3/lib/python3.7/site-packages/backtesting/backtesting.py", line 685, in run
    strategy.init()
  File "./go_test", line 22, in init
    self.sma1 = self.I(self.tulip_pad, ti.sma, self.data.Close, self.n1)
  File "/home/ej/bin/pyv3/lib/python3.7/site-packages/backtesting/backtesting.py", line 128, in I
    value = func(*args, **kwargs)
  File "./go_test", line 38, in tulip_pad
    outputs = func(*args, **kwargs)
TypeError: 'SmaCross' object is not callable



The Code

class SmaCross(Strategy):
    
    n1 = 11
    n2 = 20
    

    def init(self):
        # Precompute two moving averages
        
        self.sma1 = self.I(self.tulip_pad, ti.sma, self.data.Close, self.n1)
        self.sma2 = self.I(self.tulip_pad, ti.sma, self.data.Close, self.n2)
        
        
    def next(self):
        
        # If sma1 crosses above sma2, buy the asset
        if crossover(self.sma1, self.sma2):
            self.buy()

        # Else, if sma1 crosses below sma2, sell it
        elif crossover(self.sma2, self.sma1):
            self.sell()
        

    def tulip_pad(func, *args, **kwargs):
        outputs = func(*args, **kwargs])
        if not isinstance(outputs, tuple):
            outputs = (outputs,)
        expect_size = len(args[0])
        padded = [np.r_[np.repeat(np.nan, expect_size - o.size), o]
                  for o in outputs_2]
        return padded
    
bt = Backtest(GOOG, SmaCross, cash=10000, commission=.002)
bt.run()

**Comment by jdx-dev** [comment]
Hey @sumobull, don't make `tulip_pad()` a class method. Instead define it as a local function within `init()`. You can just copy the code from above right into `init()` and it should work just fine.

The issue needs to be upvoted though.

```python
def init(self):
    # Precompute two moving averages

   def tulip_pad(func, *args, **kwargs):
       outputs = func(*args, **kwargs])
       if not isinstance(outputs, tuple):
           outputs = (outputs,)
       expect_size = len(args[0])
       padded = [np.r_[np.repeat(np.nan, expect_size - o.size), o]
              for o in outputs_2]
        return padded
    
    self.sma1 = self.I(tulip_pad, ti.sma, self.data.Close, self.n1)
    self.sma2 = self.I(tulip_pad, ti.sma, self.data.Close, self.n2)
    
    
def next(self):
    
    # If sma1 crosses above sma2, buy the asset
    if crossover(self.sma1, self.sma2):
        self.buy()

    # Else, if sma1 crosses below sma2, sell it
    elif crossover(self.sma2, self.sma1):
        self.sell()
    


```

**Comment by sumobull** [comment]
Thanks!

**Comment by mblacklock** [comment]
I had to use:
return padded[0] 
in def tulip_pad to get it to work but looks good
