### ISSUE TITLE
HTML Plot not being saved

### ISSUE THREAD

**Issue by codingalex** [kernc/backtesting.py#45]
### Actual Behavior
When using JupyterLab hosted on Google Cloud Platform, backtesting.py does not save plots to a file. 
This is the code I used:
```py
bt.plot(filename="/home/jupyter/test.html", open_browser=True)
```
The plot is being displayed in the Jupyter notebook but somehow is not saved to file.

### Steps to Reproduce

1. Create Notebook on Google Cloud AI Platform
2. Install backtesting.py
3. Try to save plot with `bt.plot(filename=)`

### Additional info

- Backtesting version: 0.1.2

**Comment by kernc** [comment]
Ah, a bug due to these lines:
https://github.com/kernc/backtesting.py/blob/abbd1fae2e8a326c90f52cab2e4405797087cb0c/backtesting/_plotting.py#L53-L59
I guess the two branches should be reversed. :+1:
