### ISSUE TITLE
Backtest config for Micro E-mini Dow

### ISSUE THREAD

**Issue by antonma** [kernc/backtesting.py#475]
### Question

Hello guys,

I would like to to run a backtest on my 5 min MYM (micro YM -> us30) future data and wonder how can I define the commissions and margin. This is the information I have from my broker (https://www.ampfutures.com/):

Commissions in ->  $0.42 (commissions per side) $0.84 (commissions per round)
Day trade Margin      -> $50.00
Tick cost                    -> $0.5 so one pip is 0.5 $

Any idea if I can use this information in backtesting py?

Thank you!

```python

bt = Backtest(data, ClusterMACross, cash = 10000, commission = ? margin = ?, exclusive_orders = True)

```

### Additional info

- Backtesting version: 0.3.2

**Comment by kernc** [comment]
> Commissions in -> $0.42 (commissions per side) $0.84 (commissions per round)

What fraction of MYM average price does the commission cost represent? Put that value in as the `commission=`.

> Day trade Margin -> $50.00

I'll have to assume you deposited (or were gifted) $5. With margin $50, the leverage is 10x. Thus, set `margin=1/10`.
