### ISSUE TITLE
AttributeError: '_Array' object has no attribute 'rolling'

### ISSUE THREAD

**Issue by connorfewin** [kernc/backtesting.py#487]
I am trying to implement a bollinger band strategy and backtest it. The low band is bb_bbl and the high band is bb_bbh. I am using a technical analysis library. I have functions that can either return each bollinger band, or add both bands to the data frame. The original data frame is in the correct format.

I am trying to run it, but I am getting the same error. Not sure what I am doing wrong. The documentation doesn't specify having a rolling attribute.
```py
class BollingerStrategy(Strategy):
    
    def init(self):
        self.bb_bbh = tech.getBollingerBandHigh(self.data)
        self.bb_bbl = tech.getBollingerBandLow(self.data)
    
    def next(self):
        if self.bb_bbh == NaN or self.bb_bbl == NaN:
            pass
        elif self.data.Close < self.bb_bbl:
            self.buy()
        elif self.data.Close > self.bb_bbh:
            self.position.close()
```

This is my code for the strategy. The `tech.getBollingerBandHigh(self.data)` takes a data frame and returns the time stamped bollinger band. The first 20 entries of the bollinger bands are NaN because there is not enough data to calculate them yet.

**Comment by kernc** [comment]
Simply, [`Strategy.data`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data) in _not_ a data frame. Use `self.data.df`.
