### ISSUE TITLE
wrong logic of buy and sel

### ISSUE THREAD

**Issue by Realmlai** [kernc/backtesting.py#49]
### Expected Behavior
I found the buy and sell signal was wrong.
please check out the attachment.

### Actual Behavior
wrongly P/L -1.538
because the trade is a win trade

### Steps to Reproduce
![backtestinglogic](https://user-images.githubusercontent.com/60931992/76278980-fc5a1f00-62c7-11ea-8ca8-592a81ef6171.png)
1.
2.
3.

### Additional info

- Backtesting version:

**Comment by kernc** [comment]
Note, `Strategy.sell()` implicitly closes the long position and opens a new short one (that'll change in the upcoming version, see #47). If that doesn't answer your concerns, why do you think the last trade is a win?

**Comment by kernc** [comment]
The green up arrow is not a buy signal, but rather an end point marker of a market-long (upwards) and profitable (green) trade.

**Comment by Realmlai** [comment]
Great, thank you kernc

**Comment by MattoDemente** [comment]
Then, how do I identify the buy/sell signals in the plot ?

**Comment by kernc** [comment]
The dotted lines indicate duration of trades and the PL triangles closing trades' success. There are no other visual indicators showing trades entering, nor order placing. It's very simple to devise something yourself:
```py
class MyStrategy(Strategy):
    def init(self):
        # Shows buy/sell signal as a scatter plot. Init to all-NaN.
        self.signal = self.I(lambda: np.repeat(np.nan, len(self.data.Close), scatter=True)

    def next(self):
        ...
        # on some condition
        self.buy()

    def buy(self, *args, **kwargs):
        self.signal[-1] = 1  # On buy, input 1 instead of existing NaN
        super().buy(*args, **kwargs)
```
