### ISSUE TITLE
Open a limit order in certain time frame

### ISSUE THREAD

**Issue by sword134** [kernc/backtesting.py#502]
Hello,
I am trying to open a long limit order when the time is between 2:55pm and 3pm and only in that timeframe.

In raw python it would look like this, where x is my index column in my dataframe.

```
def time_in_range(x):
    start = time(14, 55)
    end = time(15 0)
    x = datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
    """Return true if x is in the range [start, end]"""
    if start <= end:
        return start <= x <= end
    else:
        return start <= x or x <= end
```

I am however unsure how I would make it in the backtesting library? How do I open a long limit order when the time is between 2:55pm and 3pm and then close it say 10 minutes later if it hasn't been filled?

**Comment by kernc** [comment]
[`Strategy.data.index`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data) is an instance of [`pd.DatetimeIndex`](https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.html) and it's values are [`pd.Timestamp`](https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html). So something like this might work:
```py
    time = self.data.index[-1].time()
    if start <= time <= end:
        self.buy(...)
    ...
    for order in self.orders:
        if time >= time(15, 10):
            order.cancel()
```

**Comment by sword134** [comment]
> You can test the order via [`Order.is_long`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Order.is_long). The active [`Trade`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Trade.is_long) has a similar property.
> 
> You can also just loop over `for order in self.orders`, because once the order fills and becomes a trade, it is removed from `Strategy.orders` and put into [`Strategy.trades`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.trades).

This also cancels the stoploss on the current trade though. Is there a way to disguinish between the stoploss which is attached to the current trade and the order for a limit short (in case the current trade is a long). I only want to cancel the short order, not the stoploss attached to the current active long trade

**Comment by kernc** [comment]
> Is there a way to disguinish between the stoploss which is attached to the current trade and the order for a limit short

Orders have [`.is_contingent`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Order.is_contingent) property which is True for SL/TP orders.

**Comment by eromoe** [comment]
@kernc How can I make cancel a order when it exceed certain time ? 
I tend to close an order if it is not filled in certain time interval ,  but Order class doesn't contain entry_time .

**Comment by kernc** [comment]
Whatever is not provided by the library, you can code yourself. Something like:
```py
order = self.buy(...)
self.order_times[order] = self.data.index[-1]

for o in self.orders:
    if self.data.index[-1] - self.order_times[o] > pd.Timedelta('3 days'):
        o.cancel()
```
If you think `Order` needs a new property `.placed_time` (or somesuch), open a new feature request for it.
