### ISSUE TITLE
Stop-loss generates short order

### ISSUE THREAD

**Issue by ww-driving** [kernc/backtesting.py#507]
The stop loss generates a short order, which isn't expected.

```python

from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from backtesting.test import GOOG, SMA

class BBandsCross(Strategy):

    def init(self):
        self.bbm = self.I(SMA, self.data.Close, 20)

    def next(self):
        if crossover(self.data.Close, self.bbm) and self.position.size == 0:
            self.buy()
        elif crossover(self.bbm, self.data.Close) and self.position.size > 0:
            self.sell(size=self.position.size)
        for trade in self.trades:
            if trade.is_long and not trade.sl:  # Only long and skip already set
                trade.sl = .95 * trade.entry_price

bt = Backtest(GOOG, BBandsCross, cash=10000, commission=.002)
stats = bt.run()

```

### Additional info

![image](https://user-images.githubusercontent.com/88955064/137620466-9ca66006-a32b-4eac-a6cf-20be0479cd23.png)

![image](https://user-images.githubusercontent.com/88955064/137620507-e8e8092c-bf89-49fe-9fef-7e9cf7ba61e6.png)

- Backtesting version: 0.3.2

**Comment by kernc** [comment]
The short order that encounters huge losses is created by:
```py
        elif crossover(self.bbm, self.data.Close) and self.position.size > 0:
            self.sell(size=self.position.size)
```
[`Trade.sl=`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Trade.sl) places a contingent stop-loss order that is closed once the trade is fully closed.

This is how it trades and orders work with FIFO brokers. See [`Backtest(..., hedging=True)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest) if you want to take distinct trades in both directions simultaneously.

**Comment by keivanipchihagh** [comment]
> @wakandan For a short (SL) order, if current `low < stop_price`, the order becomes a limit/market order and executes immediately. I don't think there's anything wrong with this logic.

I'm not sure if the logic is correct. For a long position, stop-loss is hit when the price falls below the `stop_price`, so the correct condition would be `(low < stop_price)`. Same goes for a short position where `stop_loss` is hit when `(high > stop_price)`.
