### ISSUE TITLE
Using Talib and plot question

### ISSUE THREAD

**Issue by Realmlai** [kernc/backtesting.py#52]
I've two question:
1. I'm using Talib SMA , sma data can output normally, but can't count in the  Equity and other results.

2. Can backtest plot with "Strategy" value. That means only display the indicator like sma 

### Code ###

from backtesting import Strategy
from backtesting.lib import crossover
from backtesting import Backtest
import backtesting
import pandas as pd
import talib

df = pd.read_csv("C:/Users/Peter/Desktop/EURUSD_Candlestick_1_Hour_01.09.2018-19.10.2019_b.csv")

df.index = pd.to_datetime(df['Date'])
df.sort_index(ascending = True, inplace=True)

class SmaCross(Strategy):   
    def init(self):
        
        FSMA = talib.SMA(df['Close'], timeperiod=14)
        SSMA = talib.SMA(df['Close'], timeperiod=30)
    
    def next(self):
        if crossover(FSMA, SSMA):
            self.buy()

        elif crossover(SSMA, FSMA):
            self.sell()
                
bt = Backtest(df, SmaCross, cash=1000, commission=.002)
bt.run()

========================
Start                     2018-01-10 00:00:00
End                       2019-12-09 23:00:00
Duration                    698 days 23:00:00
Exposure [%]                                0
Equity Final [$]                         1000
Equity Peak [$]                          1000
Return [%]                                  0
Buy & Hold Return [%]                 4.74283
Max. Drawdown [%]                          -0
Avg. Drawdown [%]                         NaN
Max. Drawdown Duration                    NaN
Avg. Drawdown Duration                    NaN
 Trades                                    0
Win Rate [%]                              NaN
Best Trade [%]                            NaN
Worst Trade [%]                           NaN
Avg. Trade [%]                            NaN
Max. Trade Duration                       NaT
Avg. Trade Duration                       NaT
Expectancy [%]                            NaN
SQN                                       NaN
Sharpe Ratio                              NaN
Sortino Ratio                             NaN
Calmar Ratio                              NaN
_strategy                            SmaCross
dtype: object

**Comment by kernc** [comment]
Yes, please see the main [example](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Strategy) and compare it to your code. You are missing `Strategy.I()` calls around your indicator computation.

**Comment by vsdubey** [comment]
Getting the same error as above even after using the indicator in 

> Strategy.I()
Please help
