### ISSUE TITLE
Proper way to set multiple constraints for Backtest.optimize?

### ISSUE THREAD

**Issue by Clifford-Yen** [kernc/backtesting.py#520]
Hi there,

I am wondering how to set up multiple constraints for Backtest.optimize? I know the most common constraint used for Backtest.optimize is to make sure n1 < n2, where n1 is used for the short term SMA1 and n2 is used for the long term SMA2. It can also be used like this way as shown in the documentation:

```python
constraint=lambda p: p.n_exit < p.n_enter < p.n1 < p.n2,
```

However, how can we set up multiple constraints with multiple statements? For example, if I want to make sure n1 < n2, and maybe I have other parameters n3 and n4, and I want to make sure n3 < n4 while n3 and n4 are not related to n1 and n2, how to properly set it up? Thank you.

**Comment by kernc** [comment]
Simply pass to [`constraint=`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.optimize) _any Python function_ that takes parameters `p` and returns `True` if the parameter combination is admissible, or `False` if not. E.g.:
```py
def my_constraints(params):
    return params.n1 < params.n2 and params.n3 < params.n4

...
bt.optimize(..., constraint=my_constraints)
```
