### ISSUE TITLE
bad practice pass class referrence as argument in run() function as destructor never  called.

### ISSUE THREAD

**Issue by guzuomuse** [kernc/backtesting.py#532]
as the title: is it bad to pass class referrence in bt.run()?
### Expected Behavior
destructor should be called

### Actual Behavior
destructor never called

### Steps to Reproduce

```python

from backtesting import Backtest, Strategy
from backtesting.lib import crossover

from backtesting.test import SMA, GOOG


class Test:
    def __del__(self):
        print('__test__instance__never__called_yet!')
        pass

    pass


class SmaCross(Strategy):
    test_instance = None

    def init(self):
        price = self.data.Close
        self.ma1 = self.I(SMA, price, 10)
        self.ma2 = self.I(SMA, price, 20)

    def next(self):
        if crossover(self.ma1, self.ma2):
            self.buy()
        elif crossover(self.ma2, self.ma1):
            self.sell()

    def __del__(self):
        print('strategy__del__never__called')
        pass


bt = Backtest(GOOG, SmaCross, commission=.002,
              exclusive_orders=True)
stats = bt.run(test_instance=Test())


```

### Additional info

run the code above the __del__in Strategy(SmaCross) class and Test class neither called .is it an expected behavior or bad practice?

if bad any alertnative solution?

**Comment by kernc** [comment]
The destructor is called once the object reference count becomes zero. In this case, a reference to the strategy instance is kept in `stats['_strategy']`:
https://github.com/kernc/backtesting.py/blob/267d99f0d48745acf98156b2e69150c02d42f761/backtesting/_stats.py#L141
If you don't need it, you can:
```py
...
stats.pop('_strategy')
```
and this should invoke both your destructors.

**Comment by guzuomuse** [comment]
nice.
