### ISSUE TITLE
lazy evaluation  only calculate indicator value when need  

### ISSUE THREAD

**Issue by guzuomuse** [kernc/backtesting.py#536]
<pre>
from backtesting import Backtest, Strategy

from backtesting.test import GOOG

# ############################################ stupid_indicators ---start
def my_indicator1(data):  # return all 2
    l1 = []
    for i in range(len(data)):
        l1.append(2)
    return l1
    pass

def my_indicator2(data):  # return all 3
    l1 = []
    for i in range(len(data)):
        l1.append(3)
    return l1
    pass

# ############################################ stupid_indicators ---end

class St(Strategy):

    # noinspection PyAttributeOutsideInit
    def init(self):
        price = self.data.Close
        self.my_indicator1 = self.I(my_indicator1, price)
        self.my_indicator2 = self.I(my_indicator2, price)
    def next(self):
        if self.my_indicator1 % 3 == 0 and self.my_indicator2 % 3 == 0:
            self.buy()
            pass
        """<b>
        here is the problem: the first "% 3" condition will never satisfy,so we should not calculate the "indicator2"
        actual behavior: the indicator2 still called that's not necessary
        expected behavior:don't call indicator2 util if really need---lazy evaluation <------how to achieve this?
        </b>
        """
        pass

bt = Backtest(GOOG, St, commission=.002,
              exclusive_orders=True)
stats = bt.run()

</pre>

**Comment by kernc** [comment]
> don't call indicator2 util if really need---lazy evaluation <------how to achieve this?

Simply call the (reasonably adapted) function straight in `next()` instead of `init()`?
```py
        if my_indicator1(self.data) % 3 == 0 and my_indicator2(self.data) % 3 == 0:
            ....
```

Please consider using [Discussions forum](https://github.com/kernc/backtesting.py/discussions) for your future non-bug/issue queries.
