### ISSUE TITLE
Exit short and enter long on the same bar

### ISSUE THREAD

**Issue by mac133k** [kernc/backtesting.py#552]
### Expected Behavior
I tried to implement a strategy where the stop level to exit a short position is a stop entry for a long position, so I expected to have the short position closed at the stop level and the long position opened at the same level on the same bar. I coded it like this:

```
def next(self):
    if not self.position:
        if self.data.signal[-1] == -1:
            self.sell(sl=self.data.level[-1])
            self.buy(stop=self.data.level[-1])
...
```

The above is the portion of code that was supposed to open a short position with the stop price at the specific level and submit a stop entry buy order at the same level. 

### Actual Behavior
The buy instruction trumps the short sell, which means the short position is not opened at all, but the buy order is submitted and gets executed at the level price.

### The questions

Before I start tampering with trades or position fill prices I thought I should ask here first:
* Does somebody know if there is a way to achieve switching from short to long by executing two orders on the same bar? Either through a standard solution or a hacky workaround?
* If it is not possible at all in the current version can it be a feature for a future release?

### Additional info

- Backtesting version: 0.3.2

**Comment by kernc** [comment]
Have you tried running with [`Backtest(..., hedging=True)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest&gsc.tab=0)?

**Comment by mac133k** [comment]
I think that does the trick, thanks.
