### ISSUE TITLE
Improve column names and len checkers

### ISSUE THREAD

**Issue by diegolovison** [kernc/backtesting.py#57]
My data source is returning the following columns: `['open', 'high', 'low', 'close', 'tick_volume', 'spread', 'real_volume']`

* I think that we could remove https://github.com/kernc/backtesting.py/blob/master/backtesting/backtesting.py#L659
* I think that the column names should be configurable https://github.com/kernc/backtesting.py/blob/master/backtesting/backtesting.py#L662

In my case, I could call `Backtest(stock_data, SmaCross, commission=.002, column_open='open', column_high='high'....)`

This is not a bug but an improvement

**Comment by diegolovison** [comment]
If you agree, I can fix it.
Cheers

**Comment by kernc** [comment]
In your case, you can call:
```py
data = data.rename(columns=data.columns.str.title()) \
           .rename(columns=dict(real_volume='Volume'))  # Optional. Volume will NaN by default
Backtest(data, ...)
```
It's about as many key presses. Even with pandas API as unstable as it lately appears to be, I think this is better.
