### ISSUE TITLE
Multiple buys or sells incorrectly executed at same time on same candle

### ISSUE THREAD

**Issue by coryde87** [kernc/backtesting.py#571]
### Expected Behavior
Only one sell should be executed but more than one is executed. It looks like it could have something to do with leftover cash? I've tried this with some other parameters using the same dataset and get similar issues where it places multiple buy/sell orders at the same time on the same candle.

### Actual Behavior
_trades output (the two sell orders showing the issue are highlighted):
![image](https://user-images.githubusercontent.com/97609809/149207851-2efd48c0-23b6-476d-8c95-109ebaf6091d.png)

Section of plot with the two sells:
![image](https://user-images.githubusercontent.com/97609809/149208079-8c8dfba9-6f1e-44b1-a297-fca6e381f94c.png)

### Steps to Reproduce

```python
import backtesting
from backtesting import Backtest, Strategy
from backtesting.lib import crossover, resample_apply, barssince
from backtesting.test import SMA, GOOG, EURUSD
import pandas as pd
import pandas_ta as ta

# set pip loss limit value
loss_pips = 0.0008 
# set pip profit limit value
profit_pips = 0.001
# Load data
df = pd.read_csv('EURUSD_S5_2021-12-06 000000_2021-12-10 170000.csv', sep=",")
df = df.iloc[0:4999]
# requires the DataFrame index to be a DatetimeIndex.
df.set_index(pd.DatetimeIndex(df["time"]), inplace=True)

class SmaCross(Strategy):
    def init(self):
        price = self.data.Close
        open_price_list = self.data.Open
        self.ma1 = self.I(SMA, price, 10)
        self.ma2 = self.I(SMA, price, 20)
        self.rsi = self.I(ta.rsi, price.s)
    def next(self):
        previous_price = self.data.Close[-1]
        if crossover(self.ma1, self.ma2) and (barssince(self.rsi <= 25) <= 10): 
            self.buy(sl=(previous_price-loss_pips), tp=(previous_price+profit_pips))
        elif crossover(self.ma2, self.ma1) and (barssince(self.rsi >= 65) <= 10):
            self.sell(sl=(previous_price+loss_pips), tp=(previous_price-profit_pips))

bt = Backtest(df, SmaCross, commission=0,
              exclusive_orders=False)
stats = bt.run()
bt.plot()
```

### Additional info

- Backtesting version: 0.3.3   
- CSV file:
[EURUSD_S5_2021-12-06 000000_2021-12-10 170000.csv](https://github.com/kernc/backtesting.py/files/7857201/EURUSD_S5_2021-12-06.000000_2021-12-10.170000.csv)

**Comment by kernc** [comment]
Orders might have been placed earlier than bar 2847 when they are executed into trades.
Do a `print(len(self.data), self.data.index[-1])` before `self.sell()` and you'll see.

**Comment by coryde87** [comment]
> Orders might have been placed earlier than bar 2847 when they are executed into trades. Do a `print(len(self.data), self.data.index[-1])` before `self.sell()` and you'll see.

Yep there was an order placed before that sell. I am confused though, I thought orders would only be executed at the bar you requested rather than being filled at a later point? Sorry for my poor understanding of this but I'm not understanding why multiple trades get executed on the same bar from previously placed orders. Do you know of any material I can read to gain a better understanding of this? Thanks

**Comment by kernc** [comment]
It [says in the docs: Orders are GTC](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Order). Normally, orders without `stop=` and `limit=` are market orders and execute on next bar, but since orders by default are [as large as possible](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.buy), your next-placed order couldn't execute until the previous one was either SL- or TP-ed.

If you need to close previous unfilled orders, see discussion https://github.com/kernc/backtesting.py/discussions/567.
Alternatively, you could add [`if not self.position`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Position) check before your order-placing calls.
