### ISSUE TITLE
Confused on how return is calculated when holding

### ISSUE THREAD

**Issue by emilyvainberg12** [kernc/backtesting.py#578]
From the trades below, it seems like every trade made money (sell price was higher than buy price)

<img width="946" alt="Screen Shot 2022-01-22 at 2 25 19 PM" src="https://user-images.githubusercontent.com/60680869/150654326-b2265ad5-d2f4-4344-b4e5-c1a5f025ebd6.png">

However when I look at the return calculations, it shows a negative return

<img width="471" alt="Screen Shot 2022-01-22 at 2 27 15 PM" src="https://user-images.githubusercontent.com/60680869/150654363-6b8269a2-1528-4c8f-982e-2ebfd3c22d64.png">

I don't understand why the equity is changing after all stocks are sold and held until the next purchase. Below is the first trading instance and the subsequent equity values.

<img width="1289" alt="Screen Shot 2022-01-22 at 2 28 34 PM" src="https://user-images.githubusercontent.com/60680869/150654412-2d9406c9-c19f-4718-89b0-24cefeb9c4a4.png">

Maybe I have a fundamental misunderstanding on how return works, but why is my equity changing after having sold all of the stocks?

**Comment by kernc** [comment]
> it seems like every trade made money (sell price was higher than buy price)

Some of those trades are _short selling_ trades (`size` < 0) and their return is negative (`PnL` < 0).

Current equity is the sum of cash on hand plus trades' PnL, so it naturally changes during the backtest:
https://github.com/kernc/backtesting.py/blob/94d20da85e278102a0cc71b27a3a35b815e11648/backtesting/backtesting.py#L753-L755

If you just need to close a trade/position, use [`Trade.close()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Trade.close)/[`Position.close()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Position.close).

With these things in mind, is there still an issue here?

**Comment by emilyvainberg12** [comment]
Hi, thank you for responding so quickly. 
So when I buy I use:
 self.position.close()
 self.buy()
And when I sell I use:
self.position.close()
self.sell()

How do I sell for cash instead of buying shorts. I want to use an implementation that doesn't deal with any shorting.
