### ISSUE TITLE
How to stack positions and close with the size of pervious trade 

### ISSUE THREAD

**Issue by antonma** [kernc/backtesting.py#580]
Hey, I'm trying to implement a strategy where I would like to buy shares, hold them for x bars and close them in the same order with the same size as bought. 
### Expected Behavior
Buy only
The self.position.size would be the sum of all open trades. 
E.g.:
self.buy(size = 20)
self.position.size would be 20
self.buy(size = 20)
self.position.size would be 40
self.sell(size = 20)
self.position.size would be 20

### Actual Behavior
Currently the size of self.position.size is not a sum of open trades but the size of the last trade.
Bar 469 Trade Buy Size: 10
Bar 541 Trade Buy Size: 10
Bar 558 Trade Buy Size: 10
Bar 563 Trade Buy Size: 10

Position: <Position: 10 (1 trades)>
Position Size: 10

**Comment by kernc** [comment]
[`Position.size`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Position.size) is nothing else but the sum of sizes of all open trades!
https://github.com/kernc/backtesting.py/blob/94d20da85e278102a0cc71b27a3a35b815e11648/backtesting/backtesting.py#L320-L322

Your other trades must have, therefore, been closed on some bars in between.

**Comment by antonma** [comment]
Hi, 
than you for your replay. This is what I'm trying:

```
def next(self):               
        if len(self._broker.trades) > 0:                        
            print("Trades Count: " + str(len(self.trades)))             
            #if (len(self.data)-1 >= self.trades[0].entry_bar + 20):        
            #    print("Bar " + str(self.trades[0].entry_bar) + " Trade Size: " + str(self.trades[0].size))                   

        if self.data.Close[-2] < self.center_ma[-2]:
            self.prev_signal = -1
        elif self.data.Close[-2] > self.center_ma[-2]:
            self.prev_signal = 1

        if self.data.Close[-1] < self.center_ma[-1]:
            self.signal = -1
        elif self.data.Close[-1] > self.center_ma[-1]:
            self.signal = 1
    
        #print("no posiiton")
        if ( self.signal ==  1 and self.signal != self.prev_signal):                        
            self.buy(size= 0.1)       

```

The trades count is always 1 and I do not close a position or sell anything.

**Comment by antonma** [comment]
Oh, I think my issue was exclusive_orders=True...
