### ISSUE TITLE
Can backtesting.py be used to back test a long only strategy which switches between different equities

### ISSUE THREAD

**Issue by tridgeway176** [kernc/backtesting.py#60]
### Expected Behavior
From a basket of equities the strategy buys the equity at 100% with best momentum.
If the equity with best momentum changes the previously equity is sold and fully invested in the equity with best momentum.

**Comment by kernc** [comment]
No. Unfortunately, backtesting.py only supports testing on a single equity at a time. For your use case, maybe try [`bt`](https://pmorissette.github.io/bt/) and its [`bt.algos.SelectMomentum`](https://pmorissette.github.io/bt/bt.html#bt.algos.SelectMomentum).

**Comment by kernc** [comment]
Duplicate of issue https://github.com/kernc/backtesting.py/issues/20.
