### ISSUE TITLE
saving bokeh plots and display on dash

### ISSUE THREAD

**Issue by GSav90** [kernc/backtesting.py#608]
### Expected Behavior

First of all, thanks a lot for this awesome library. It is really a game changer. 

I'm interested in saving the bokeh plot generated and display it on my dash app for different runs. So, I have couple of questions:

1. How can I save the bokeh plot and load it in my dash app? 

- I know the "backtest" object created has backtest.plot() object. How do I call this object from dash? Can you please guide a bit. I have never used bokeh and looking at the documents, I couldn't find anything concrete. 
- I see we have an option to create a file. Is it possible to load the html file or extract json from it?

**Comment by kernc** [comment]
Continued in https://github.com/kernc/backtesting.py/discussions/610.
