### ISSUE TITLE
how to get the data of the best combination of parameters after doing the optimization with bt.optimize()

### ISSUE THREAD

**Issue by samueltg92** [kernc/backtesting.py#625]
### Expected Behavior
I was expecting the results of the best combination of parameters but it threw me an error

### Actual Behavior

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_18003/1385639418.py in <module>
      5 )
      6 print(stats)
----> 7 print(stats._MARSI)
      8 print(stats._strategy)

~/miniconda3/envs/TRADING/lib/python3.9/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5581         ):
   5582             return self[name]
-> 5583         return object.__getattribute__(self, name)
   5584 
   5585     def __setattr__(self, name: str, value) -> None:

AttributeError: '_Stats' object has no attribute '_MARSI'

### Steps to Reproduce

```python
This is the code used.

stats = bt.optimize(
    ema_window = [50, 100, 200],
    rsi_window = range(2, 4),
    maximize = 'Equity Final [$]',
)
print(stats)
print(stats._MARSI)
print(stats._strategy)
```

### Additional info

- Backtesting version: 0.?.?

**Comment by kernc** [comment]
The error is in your line `print(stats._MARSI)`. Simply remove the line, and you'll see the results.
