### ISSUE TITLE
Trying to use code for different stocks

### ISSUE THREAD

**Issue by deemcgee** [kernc/backtesting.py#626]
### Expected Behavior
Expecting to run code for Boeing stock (BA) using code and change the date timeframe.

### Actual Behavior

ImportError                               Traceback (most recent call last)
/var/folders/ys/kp32whkx5bn9nwysmmsrhb5w0000gn/T/ipykernel_40223/2200655262.py in <module>
      2 from backtesting.lib import crossover
      3 
----> 4 from backtesting.test import SMA, BA
      5 
      6 

ImportError: cannot import name 'BA' from 'backtesting.test' (/opt/anaconda3/lib/python3.9/site-packages/backtesting/test/__init__.py) 

### Steps to Reproduce

1.
2.
3.

```python

from backtesting import Backtest, Strategy
from backtesting.lib import crossover

from backtesting.test import SMA, BA


class SmaCross(Strategy):
    n1 = 10
    n2 = 20

    def init(self):
        close = self.data.Close
        self.sma1 = self.I(SMA, close, self.n1)
        self.sma2 = self.I(SMA, close, self.n2)

    def next(self):
        if crossover(self.sma1, self.sma2):
            self.buy()
        elif crossover(self.sma2, self.sma1):
            self.sell()


bt = Backtest(BA, SmaCross,
              cash=10000, commission=.002,
              exclusive_orders=True)

output = bt.run()
bt.plot()

```

### Additional info

- Backtesting version: 0.3.3

**Comment by kernc** [comment]
The error is in your code:
```py
from backtesting.test import SMA, BA
```
There is [_no_ `backtesting.test.BA`](https://github.com/kernc/backtesting.py/blob/master/backtesting/test/__init__.py).

Backtesting.py is "bring your own data". You can use one of the tools mentioned in the [Quick Start tutorial](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Data).

**Comment by deemcgee** [comment]
I still don't understand. I ran this code:

import pandas as pd


def _read_file(filename):
    from os.path import dirname, join

    return pd.read_csv(join(dirname(__file__), filename),
                       index_col=0, parse_dates=True, infer_datetime_format=True)


GOOG = _read_file('GOOG.csv')

EURUSD = _read_file('EURUSD.csv')


def SMA(arr: pd.Series, n: int) -> pd.Series:
    return pd.Series(arr).rolling(n).mean()

I got this output:

NameError                                 Traceback (most recent call last)
/var/folders/ys/kp32whkx5bn9nwysmmsrhb5w0000gn/T/ipykernel_41246/243035785.py in <module>
      9 
     10 
---> 11 GOOG = _read_file('GOOG.csv')
     12 
     13 EURUSD = _read_file('EURUSD.csv')

/var/folders/ys/kp32whkx5bn9nwysmmsrhb5w0000gn/T/ipykernel_41246/243035785.py in _read_file(filename)
      5     from os.path import dirname, join
      6 
----> 7     return pd.read_csv(join(dirname(__file__), filename),
      8                        index_col=0, parse_dates=True, infer_datetime_format=True)
      9 

NameError: name '__file__' is not defined

I downloaded the GOOG and EURUSD csv files for reference and I still don't get how to run different stocks. Do I import the csv file first then run the code you gave? If so should I then change the GOOG data frame to the stock of my choosing.?I hope this isn't a stupid question, but I'm trying to understand.
