### ISSUE TITLE
Question about commissions

### ISSUE THREAD

**Issue by samueltg92** [kernc/backtesting.py#627]
Hello, I want to backtest with realistic conditions such as a commission of 4usd per lot traded that my broker charges me. It means 2usd of commission to open a trade and 2usd of commission to close the same trade. In this case what is the proper number to work when I call Backtest(df, MyStrat, cash=xxx, margin=xxx, commission=????)

Thanks in advance

**Comment by kernc** [comment]
Presently, you can only set the commission in price-relative terms:
```py
commission = (2 + 2) / (df.Close.mean() * LOT_SIZE)
```
On average, this will be correct and might suit you just fine.
