### ISSUE TITLE
When running GOOG example, no stats table is visible

### ISSUE THREAD

**Issue by mptorr** [kernc/backtesting.py#63]
### Expected Behavior
Stats table should appear on `bt.run()`

### Actual Behavior
Only the .html chart is visible.
Run window only shows `Process finished with exit code 0`.

### Additional info
Running this on PyCharm (latest, MacOS), latest Backtesting version.
Running GOOG script from PyCharm directly (ie, not using Terminal)

Brute force solution was to modify `def run()` on backtesting.py (line 724) from:

```
        self._results = self._compute_stats(broker, strategy)
        return self._results
```

to:

```
        self._results = self._compute_stats(broker, strategy)
        print(self._results.to_string())
        return self._results
```

**Comment by kernc** [comment]
The [supposedly relevant PyCharm bug](https://youtrack.jetbrains.com/issue/PY-25931) is marked obsolete. Maybe update PyCharm? Certainly I think it's their issue. Python works as advertised. :smile:

**Comment by mptorr** [comment]
I understand. 
PyCharm I'm using is 2020.1 (latest version).

**Comment by arunavo4** [comment]
@mptorr I think that you could simply `print(bt.run())` or capture the stats like `stats = bt.run()` and either use the `stats` or `print(stats)`

**Comment by kernc** [comment]
Indeed, `Backtest.run()` just _returns_ the stats series. It's on you then to print/use it.
