### ISSUE TITLE
Entry Price is not correct

### ISSUE THREAD

**Issue by rinkesh-ahuja** [kernc/backtesting.py#633]
I am trying to backtest _inside candle pattern_ on 15 mins timeframe. But, the entry price is not correct as I tried to see the _stats._trades_. The exit price seems correct but the entry price is way above than what I have set by placing 'Stop' orders. I tried to cross-check it in trading view charts as well as the data I am passing. The price does not even hover in the range what the entry price I am getting with this backtest. This issue is recurring with almost every code. Not sure if something is wrong with the trade. I am attaching the entire code below.

```
from backtesting import Strategy, Backtest
from backtesting.lib import resample_apply
import pandas as pd
import numpy as np

class System(Strategy):
    rr = 2
    
    def init(self):
        pass
    
    def next(self):  
        
        if (self.data.Close[-2] > self.data.Open[-2] and    
             self.data.High[-1] < self.data.High[-2] and
             self.data.Low[-1] > self.data.Low[-2]):
                 self.buy(stop=self.data.High[-1], sl=self.data.Low[-1],
                          tp=self.data.High[-1]+(self.rr*(self.data.High[-1] - self.data.Low[-1])))


df = pd.read_csv("Data.csv", index_col="Date_Time", parse_dates=True)
bt = Backtest(data = df, strategy = System, commission = 0.01,
                    cash = 100000, exclusive_orders=False, hedging=True)


bt.run()
 ```

I am so grateful to you for this library and prompt response. Kudos 👍

**Comment by kernc** [comment]
This has to do with `commission=0.01`. The adjusted entry price should be 1% higher.
https://github.com/kernc/backtesting.py/blob/65f54f6819cac5f36fd94ebf0377644c62b4ee3d/backtesting/backtesting.py#L746-L751

**Comment by rinkesh-ahuja** [comment]
Absolute genius!!!!

Now, after detection of this pattern, I have added one more condition to confirm that trade takes place ONLY when the current candle crosses the high of previous candle. 
`
self.data.High[0] > self.data.High[-1]
`
But as I can see from the trade book, the entry takes place WHENEVER the price crosses the high of the 'previous candle'. I want to limit it to the next immediate candle only. I hope it makes sense what I am saying. Or indexing with [0]/current candle doesn't work at all!?

Thank you so much!

**Comment by kernc** [comment]
> Or indexing with [0]/current candle doesn't work at all!?

The indexing in backtesting.py is like normal Python lists, in ascending order: `self.data.High[-1]` is the most recent value, `self.data.High[-2]` the previous value, etc.

**Comment by armwdev** [comment]
I have a similar problem with this. Especially with shorting, when I increase the commission value, the "Entry Price"  gets even lower than the current candle low. Shouldn't this be even possible? I mean instead of changing the "Entry Price", shouldn't it be logical to decrease the position size instead when the commission gets higher or vice versa? I think the close and open prices are final so I am not sure why those are changed depending on the commission value. Thanks for the help.
