### ISSUE TITLE
Using crossover with pandas.ta does not generate any trade

### ISSUE THREAD

**Issue by mdmoura** [kernc/backtesting.py#636]
I created this backtest using `pandas.ta` for MACD calculation:

```
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from backtesting.test import GOOG
import pandas as pd
import pandas_ta as ta

class Macd(Strategy):

    def init(self):

        self.df = GOOG

        macd = ta.macd(self.df["Close"])

        self.df["Macd"] = macd[macd.columns[0]]
        self.df["MacdHistogram"] = macd[macd.columns[1]]
        self.df["MacdSignal"] = macd[macd.columns[2]]

    def next(self):
        if crossover(self.df["MacdSignal"], self.df["Macd"]):
            self.buy()
        elif crossover(self.df["Macd"], self.df["MacdSignal"]):
            self.sell()

bt = Backtest(GOOG, Macd, commission = .002, exclusive_orders = True)
stats = bt.run()
print(stats)
bt.plot()
```

However, when I run it no trade is generated and I know many would.

I am using backtesting `crossover` method. What am I missing?

### Additional info

- Backtesting version: 0.3.3

**Comment by kernc** [comment]
```py
self.df = GOOG
```
This doesn't work. It's [`Strategy.data`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data) you're looking for.

**Comment by mdmoura** [comment]
I was able to backtest using pandas.ta MACD indicator and data loaded from Yahoo Finance.

1. Does my code reflect the correct way to use backtesting?

2. Why isn't the MACD being plotted even if I am using `self.I`?

I believe this code would be useful for an example on backtesting documentation. What do you think?

```
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
import pandas as pd
import pandas_ta as ta
import yfinance as yf

class Macd(Strategy):

    macd_slow = 7
    macd_fast = 5
    macd_signal = 3

    def init(self):  

        self.macd = self.I(ta.macd, self.data.df["Close"], self.macd_fast, self.macd_slow, self.macd_signal)

    def next(self):

        if crossover(self.macd[2], self.macd[0]):
            self.position.close()
            self.buy()

        elif crossover(self.macd[0], self.macd[1]):
            self.position.close()
            self.sell()

data = yf.download("EURUSD=X", start = "2020-01-01", end = "2022-01-01", period = "1d")

backtest = Backtest(data, Macd, commission = .002, exclusive_orders = True, trade_on_close = True)
stats = backtest.run()

print(stats)
backtest.plot()
```

**Comment by kernc** [comment]
[Indexing "begins" at -1](https://kernc.github.io/backtesting.py/doc/backtesting/#manuals).

Perhaps macd _is_ plotted as an overlay. Pass [`self.I(ta.macd, ..., overlay=False)`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.I).

Use the discussion forum for questions. Thanks.

**Comment by mdmoura** [comment]
> Use the discussion forum for questions. Thanks.

I will do that. I just realised that there is a discussion forum. I was trying StackOverflow.

Thank you

**Comment by kernc** [comment]
Oh, absolutely! I even prefer questions posted on StackOverflow as that way it's not I who has to answer them. :laughing:

**Comment by TreborNamor** [comment]
`if crossover(self.macd[2], self.macd[0]):
            self.position.close()
            self.buy()

        elif crossover(self.macd[0], self.macd[1]):
            self.position.close()
            self.sell()`


I am curious, I believe you may have flipped the standard usage of macd indicator.  Wouldn't it be a buy signal when macd line crossover signal line and a sell signal when signal line crossover macd line?
