### ISSUE TITLE
How can you use df column instead of indicator class to trigger buy and sell?

### ISSUE THREAD

**Issue by leeu3581** [kernc/backtesting.py#64]
If I have a df column of True and False values, is there a way for this to trigger buy and sell instead of using indicators?

I would like to do something along the lines of the following:
```py
def next(self):
  if df['Entry'] == True:
   self.buy()
  elif df['Exit'] == True:
   self.sell()
```
How can I convert a df column to your customized numpy arrays? I tried df.Entry.to_numpy() but this doesn't seem to be the correct format to do the iterative comparisons. 

Thank you!

**Comment by kernc** [comment]
See https://github.com/kernc/backtesting.py/issues/39. You can pass extra precomputed columns in the `Backtest(..., data=)`. They will be accessible likewise.
