### ISSUE TITLE
Exception in _stats.py:123 when debugging with PyCharm

### ISSUE THREAD

**Issue by fshsweden** [kernc/backtesting.py#655]
### Expected Behavior
Being able to debug backtracing in PyCharm 2022.1

### Actual Behavior
Exception in run(), but only when debugging

### Steps to Reproduce

1. Use the simple demo program from projects github frontpage
2. Create a project in PyCharm 2022.1 , and start debugging using Run - Debug
3. Command line is:  /home/xyz/.pyenv/versions/anaconda3-2021.05/envs/backtesting/bin/python /mnt/043CF6233CF60F82/jetbrains_tools/apps/PyCharm-P/ch-0/221.5080.212/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 38605 --file /home/xyz/dev/backtesting/test.py
4. It bombs in _stats.py line 123: max_dd = -np.nan_to_num(dd.max())
   https://github.com/kernc/backtesting.py/blob/65f54f6819cac5f36fd94ebf0377644c62b4ee3d/backtesting/_stats.py#L123

Exception is:  TypeError: 'NoneType' object is not callable

Using numpy version 1.22.3
```python

```

### Additional info

When running without debug (Menu: Run-Run), it works without problems

- Backtesting version: 0.3.3

**Comment by kernc** [comment]
Debugging in PyCharm and similar IDEs automatically evaluates all sorts of properties (starting with calls to `__str__()`) of all variables in every current stack frame / scope. This can sometimes result in errors for complex objects (I've seen worse, including segfaults of the running pandas-based program) and is normally influenced by bugs in versions of Python/OS/numpy/pandas/etc.

With other cases working, this is more than likely not our bug.
