### ISSUE TITLE
access multiple optimization goals for same optimization run

### ISSUE THREAD

**Issue by gypsyzz** [kernc/backtesting.py#658]
### Aim

The aim is to assess a strategy based on multiple criteria, e.g. final equity AND Sharpe Ratio, the decision process is manual, but the process to run the numbers are identical, and would be great to not double run simulations since the numbers are already there after each run.

### Expected Behavior

Run optimization and all of the goals are accessible as dataframes, since in exhaustive search method, the optimizer simply runs the strategy with different parameters.

### Actual Behavior

Only the one stated is accessible by default, the others have to be recorded externally.

**Comment by kernc** [comment]
> Only the one stated is accessible by default, the others have to be recorded externally.

Correct. But you can record them yourself _quite easily_ by passing an appropriate [`maximize=` function](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.optimize):
```py
all_runs = {}

def recording_func(stats):
    all_runs[stats._strategy] = stats
    return stats['Sharpe Ratio']

bt = Backtest(...)
bt.optimize(maximize=recording_func, ...)

print(all_runs)
```
Therefore, I rather choose not to provide this as a built-in feature.
