### ISSUE TITLE
Pandas indicators

### ISSUE THREAD

**Issue by flydr2** [kernc/backtesting.py#661]
### Expected Behavior
same or near some results as normal use

### Actual Behavior

self.atr = self.I(atr,self.data.df.High, self.data.df.Low,self.data.df.Close, lenght=5)
the 5 lengh is not passed on sometimes... If I change it in the pandas library then it works

### Steps to Reproduce

1.
2.
3.

```python
3.7
python code goes here

```

### Additional info

- Backtesting version: 0.?.?

**Comment by kernc** [comment]
`**kwargs` are always passed to the indicator function:
https://github.com/kernc/backtesting.py/blob/65f54f6819cac5f36fd94ebf0377644c62b4ee3d/backtesting/backtesting.py#L127
Looks like not our bug.

**Comment by kernc** [comment]
And it's spelled _leng**th**_. Maybe it's that what tripped it for you.

**Comment by flydr2** [comment]
yup that was it... Thanks and sorry my mistake
