### ISSUE TITLE
stock markets

### ISSUE THREAD

**Issue by maedehkarimi** [kernc/backtesting.py#669]
#667 

hey guys
this is my question tooo
please answer
you are claim that compatible with all kinds of trades such as stock and forex and etc 
compatible with one side market (just buy) and two side markets(buy and sell)
in all of Backtesting codes the library use two side market while we need one side-markets
please help me to find , how can I use this lib in one-side markets
best regards

**Comment by kernc** [comment]
See https://github.com/kernc/backtesting.py/discussions/668.
