### ISSUE TITLE
 cannot import name 'Backtest' from 'backtesting'

### ISSUE THREAD

**Issue by Ilocans** [kernc/backtesting.py#671]
### Expected Behavior
Run the example

```
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from backtesting.test import SMA, GOOG

class SmaCross(Strategy):
    n1 = 10
    n2 = 20

    def init(self):
        close = self.data.Close
        self.sma1 = self.I(SMA, close, self.n1)
        self.sma2 = self.I(SMA, close, self.n2)

    def next(self):
        if crossover(self.sma1, self.sma2):
            self.buy()
        elif crossover(self.sma2, self.sma1):
            self.sell()


bt = Backtest(GOOG, SmaCross,
              cash=10000, commission=.002,
              exclusive_orders=True)

output = bt.run()
bt.plot()

```
### Actual Behavior
 cannot import name 'Backtest' from 'backtesting'

from backtesting import Backtest, Strategy
ImportError: cannot import name 'Backtest' from 'backtesting'

I have install using pip3 install backtesting
Python 3.9.13

### Steps to Reproduce

1.
2.
3.

```python

python code goes here

```

### Additional info

- Backtesting version: 0.?.?

**Comment by kernc** [comment]
Either you're running the example in a [python environment](https://docs.python.org/3/tutorial/venv.html) that doesn't have Backtesting.py installed, or you're being bitten by circular imports: https://stackoverflow.com/questions/9252543/importerror-cannot-import-name-x
Please recheck. Your example works for me and [the tests pass in CI](https://github.com/kernc/backtesting.py/actions/runs/2559298839).
