### ISSUE TITLE
A few questions on the backtest output plot

### ISSUE THREAD

**Issue by bravegag** [kernc/backtesting.py#676]
I have been looking into this project, and everything looks great. I have a few questions on the main plot visualization example https://kernc.github.io/backtesting.py/#example, which would appreciate if someone could help.

1. Why is the top part of the plot called equity? and what is that data there? If it is a wealth index or cumulative returns of the Strategy I would just call it Strategy instead of Equity and also add a WI or so to know it is a wealth index of the strategy. Equity is confusing as there are many asset classes which could be implemented e.g. FX, FI, Crypto.
2. The second plot top bottom, is it showing the trades? what is the meaning of the size of the triangle? the abs of the return or the amount invested? how do I see the size of the trade?
3. The third plot top bottom, I assume is showing the raw dataset, the legend states that the vertical bars are the trades but I see vertical bars everywhere and they don't match the color or trade direction looking at the plot on top so it is a bit confusing. It would also be nice to give a title to that plot and not leave it to the imagination.
4. I would suggest being able to see a fifth plot with the buy / sell signal alone, if possible and x-axis aligned to the other plots. This will help figure out trade entry issues or any possible signal to implementation lags.

**Comment by eervin123** [comment]
This project has a `Discussions` section you should probably throw this over there for the community to answer. https://github.com/kernc/backtesting.py/discussions

Regarding 
1.) The term `equity` is often used to reflect the amount of capital you have in a given strategy. Particularly when using margin and shorting. I can see how it might be confusing at first glance when thinking about it from an asset class perspective "equity, fixed Income, alternatives, commodities, etc.", but it is very common with backtesting programming libraries. 

2.) The second plot top to bottom is indeed showing the trades. The size of the triangle represents the relative size of the trade. For example, in the beginning you might only be trading 100 shares of Google, but assuming your strategy is profitable, towards the end of the backtest, you are hopefully trading thousands of shares of Google, and the size of the triangle will reflect that.  The direction of the triangle is whether it was a Long (arrow up) or a short trade (arrow down), the color of the triangle is the profitability of the trade (red = loss, green = profit).

3.) Third plot is the Price series, your indicators from your strategy, and the trades. The trades are the "tractor beams" as I call them. See the picture below. I have circled a profitable (green) trade. Red represents a losing trade. Regarding Title, I am pretty sure you can customize the charts. I know I have previously fiddled with the legend to suit my needs. Check out the documentation to see what all you can do without fiddling with the source code.  https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest.plot

![image](https://user-images.githubusercontent.com/32274861/176890606-e64501b5-91c2-45bd-902e-58c4b8ac39e7.png)

4.) You can do this with the trades dataframe that is produced as a result of running the backtest. 
![image](https://user-images.githubusercontent.com/32274861/176892087-5f25f406-d930-419d-9c68-5e17e3475a5a.png)
those last three `_strategy` `_equity_curve` and `_trades` all contain useful information for you to plot or analyze or save for later analysis. 



3.

**Comment by kernc** [comment]
Adding to @eervin123's great answer:

1. equity = cash + assets
2. Additionally, as the y-axis label indicates, triangle's y-offset denotes its return.

**Comment by bravegag** [comment]
Thanks a lot both! it makes a lot of sense.
