### ISSUE TITLE
resample_apply with multiple data columns

### ISSUE THREAD

**Issue by hip280hip280** [kernc/backtesting.py#68]
Hi guys, I found out that when I use resamply_apply, using 2 sets of data, only 1 set is resampled.
The other set is not resampled.
In the example,  self.weekly_rsi = resample_apply('W-FRI', RSI, self.data.Close, self.w_rsi).
There is only 1 set of data, which is self.data.Close, and it works fine.

But when I have 2 sets of data, for example, an indicator that takes in closing price and volume.
self.weekly_rsi = resample_apply('W-FRI', RSI, self.data.Close, self.data.Volume, self.w_rsi).
I got the error that "operands could not be broadcast together with shapes (2148,) (446,)"
Then I realise that 'close' was resampled (446), but 'volume' was not resampled (2148)

Is there a way around this ? Thanks.

**Comment by sdmovie** [comment]
RSI itself takes one series input ， what you need is call 2 reample function for Close and Volume seperately. This is not framework specific but common sense knowledge, google it first

**Comment by kernc** [comment]
This was addressed in https://github.com/kernc/backtesting.py/commit/5051b61618d139cc7859691a755715052cf20721#diff-d03a1d5472e645eb6874df3bf7021256 and f54fd76946d9791b427577e4b2ff74eb78532add. To resample multiple value vectors at the same time, pass them to the function as a data frame:
```py
df = self.data.df[['Close', 'Volume']]
resample_apply('W-FRI', indicator_func, df, parameter)
```

**Comment by JanssensKobe** [comment]
Is this also the case when making use of indicator libraries (in my case tulipy)? Because when I try this I get a 'RunTimeError'.

Code:
```python
import tulipy as ti
from backtesting import Strategy
from backtesting.lib import resample_apply

def next(self):
    df = self.data.df[['Close']]
    self.ema2_4h = resample_apply('4H', ti.ema, df, self.ema2Period)
    self.ema3_4h = resample_apply('4H', ti.ema, df, self.ema3Period)
```

Error:
```
RuntimeError: Indicator "ema(df,11)" errored with exception: 'DataFrame' object has no attribute 'dtype'
```

**Comment by kernc** [comment]
> ```py
> df = self.data.df[['Close']]
> self.ema2_4h = resample_apply('4H', ti.ema, df, self.ema2Period)
> ```

Above, `df` is a DataFrame, and a resampled `df` will be passed to `ti.ema()`, whereas the function expects _a 1-D series_. You can do either:
```py
self.ema2_4h = resample_apply('4H', ti.ema, df.Close, self.ema2Period)
```
or
```py
self.ema2_4h = resample_apply('4H', lambda df: ti.ema(df.Close), df, self.ema2Period, name='ema')
```

**Comment by kernc** [comment]
Note, there was a bug in `resample_apply()` when resampling dataframes with general OHLC columns. So far fixed in master: https://github.com/kernc/backtesting.py/commit/1b88a53809d3eb4230e6a5124406a0efcd357b53.

**Comment by JanssensKobe** [comment]
> ```python
> self.ema2_4h = resample_apply('4H', ti.ema, df.Close, self.ema2Period)
> ```
When I do this I get another RuntimeError.

Error:
```
RuntimeError: Indicator "ema(C[4H],11)" errored with exception: Cannot convert Series to numpy.ndarray
```

**Comment by kernc** [comment]
I assumed tulipy handles pandas structures, which is [not the case](https://github.com/cirla/tulipy/issues/30). Apparently, you need to convert Series into ndarrays yourself:
```py
resample_apply('4H', ti.ema, df.Close.values, self.ema2Period)
```

This is not Python tech support. :stuck_out_tongue_winking_eye:
