### ISSUE TITLE
How to add trailing stop order?

### ISSUE THREAD

**Issue by Fquant** [kernc/backtesting.py#682]
### Steps to Reproduce

1.
2.
3.

```python

python code goes here

```

### Additional info

- Backtesting version: 0.?.?

**Comment by Fquant** [comment]
I want to self.buy() order with trailing stop method, but I didn't know how to do.

**Comment by kernc** [comment]
Read [_Library of Composable Base Strategies_](https://kernc.github.io/backtesting.py/doc/examples/Strategies%20Library.html) and, hopefully, read the rest of [the tutorials](https://kernc.github.io/backtesting.py/doc/backtesting/index.html#tutorials).

Then read how `backtesting.lib.TrailingStrategy` is implemented:
https://github.com/kernc/backtesting.py/blob/65f54f6819cac5f36fd94ebf0377644c62b4ee3d/backtesting/lib.py#L440-L486

If after that anything remains unclear, welcome to raise a [discussion](https://github.com/kernc/backtesting.py/discussions).

**Comment by lmiller251** [comment]
I saw the threads from a few years ago about there being a % driven stop loss order added but was not finding much on examples of how to implement. Was this feature ever added? Apologies if I am overlooking.

Thanks for developing and maintaining all of this!
