### ISSUE TITLE
Suggestion for Faster way to optimize vs GridSearch

### ISSUE THREAD

**Issue by mitrymoe** [kernc/backtesting.py#69]
Hey, 

First of all thank you for the hard work put into this, it's a really awesome project that I still learn how to use.
I'm not that proficient in using python so that is why I'll put my suggestion here. I have used python more for machine learning stuff and there the option of searching hyperparameters was also between grid and random search. However, I found that using bayesian optimization, code runs way faster because it add probabilities to the mix by building a surrogate probability model of the objective function. That being said, you can have a look maybe over this to find out more [here](https://github.com/fmfn/BayesianOptimization/blob/master/bayes_opt/bayesian_optimization.py)

My guess is that this can be applied to your _maximize_func_ in some way and computations should, in theory, run faster. 
I'll spend the next few days trying and playing around with this and if I come up with something, I'll let you know. 

Keep it up!

**Comment by kernc** [comment]
Thanks for the kind words. :heart: 

> bayesian optimization

Sounds useful. We should certainly look into using that package as a library:

https://github.com/fmfn/BayesianOptimization#1-specifying-the-function-to-be-optimized

In most cases probably even something as simple as random grid search should work much faster, while still [giving sufficient ballpark results](https://scikit-learn.org/stable/auto_examples/model_selection/plot_randomized_search.html):
https://github.com/kernc/backtesting.py/blob/7010d68ca3d3593457447e68d19efbf51c14ae72/backtesting/backtesting.py#L816-L823

**Comment by ttfreeman** [comment]
I would suggest using `scikit-optimize`?  The random search is not guaranteed to converge faster to the optimum point because it does not learn from previous trial points.

**Comment by kernc** [comment]
We could use [skopt](https://scikit-optimize.github.io/stable/auto_examples/bayesian-optimization.html) as our constraints do match. :+1: The question is, will you implement it? Random search should be roughly a 5-line change. :smiley:

**Comment by ttfreeman** [comment]
Sure, if nothing comes up I'll work on this in the next few days. I'll also look into `skopt`. So, we can just add a parameter `method` to optimize() method, and that way, different techniques of optimization can be chosen based on the input for method param.

**Comment by kernc** [comment]
Exactly. For random search I also envisioned an argument: `n_calls: Union[int, float] = 1000`. Integer for absolute; float for relative to exhaustive search. This should match `n_calls` for skopt.

**Comment by ttfreeman** [comment]
@kernc Good progress. I have implemented skopt's `forest_minimize()` method with encouraging results. Just need to validate the things and I also think it would be helpful to add the partial dependency plots. I am looking at how you've used bokeh and will add a function to plot this after the optimization. Hopefully will have something for your review next weekend.  
![image](https://user-images.githubusercontent.com/36289053/95027317-be9e5880-0654-11eb-9f38-35251a011ee0.png)

**Comment by kernc** [comment]
> it would be helpful to add the partial dependency plots

Think you can just return the raw [`scipy.optimize.OptimizeResult`](https://scikit-optimize.github.io/stable/modules/generated/skopt.optimizer.forest_minimize.html#skopt.optimizer.forest_minimize) that [`skopt.plots.plot_objective()`](https://scikit-optimize.github.io/stable/modules/generated/skopt.plots.plot_objective.html#skopt.plots.plot_objective) (and possibly other utils) already knows how to work with? No need to reinvent the wheel.

We should, however, look into adopting the lower-triangular subplot layout for the `backtesting.lib.plot_heatmaps()`. That makes it all much clearer!

**Comment by ttfreeman** [comment]
Yes, plotting the optimization results in a jupyter notebook is straightforward with `plot_objective` (and that's how I plotted the charts above for the Quick Start example). Though I am not sure if it would be as straightforward to integrate that with bokeh. The only thing that might be possible if we can export the plot_objective plots as PNG and bokeh can use them as <img/> tag in their html file? It just won't be interactive like native bokeh charts.

I quickly looked at the heatmap plots from backtesting.lib.plot_heatmaps() and they are not as nice and clear with contour lines and test points etc.

**Comment by kernc** [comment]
> Though I am not sure if it would be as straightforward to integrate that with bokeh.

I don't fully understand why we'd want it to integrate it with Bokeh. `plot_objective()` will output into notebooks just as well, and the returned `matplotlib.Axes` can be savefig'd for an image. Sure, the plot won't be interactive, but that's a miniature price to pay for not needing to write/maintain any extra code? What I'm suggesting, therefore, is that we just return the `OptimizeResult` and mark a note in the docs that the user might want to run `skopt.plots.plot_objective()` upon it. It's perfectly ok to mix best of breed utilities from the ecosystem. :grin:


> I quickly looked at the heatmap plots from `backtesting.lib.plot_heatmaps()` and they are not as nice and clear with contour lines and test points etc.

They are not. It's just a note-to-self proposal that we lay them out sorted in a more immediately clear lower-triangular  instead of the simple grid layout.

**Comment by guzuomuse** [comment]
this should be on the top priority!  big win if we have this feature!
