### ISSUE TITLE
No orders being placed with tulip 

### ISSUE THREAD

**Issue by leonbe** [kernc/backtesting.py#70]
I'm trying to use tulipy indicator library but then no buys or sells are placed any more whereas the indicators are plotted correctly in the chart. Do you have an idea what I did wrong?
Thanks alot in advance!

# code

```python
class SmaCrossTulip(bt.Strategy):
    n1 = 10
    n2 = 50

    def init(self):
        def tulip_pad(func, *args, **kwargs):
            outputs = func(*args, **kwargs)
            if not isinstance(outputs, tuple):
                outputs = (outputs,)
            expect_size = len(args[0])
            padded = [np.r_[np.repeat(np.nan, expect_size - o.size), o] for o in outputs]
            return padded

        # Doesn't buy or sell anything:
        self.sma1 = self.I(tulip_pad, ti.sma, self.data.Close, self.n1)
        self.sma2 = self.I(tulip_pad, ti.sma, self.data.Close, self.n2)

        # Does work as expected:
        # self.sma1 = self.I(SMA, self.data.Close, self.n1)
        # self.sma2 = self.I(SMA, self.data.Close, self.n2)

    def next(self):
        if bt.lib.crossover(self.sma1, self.sma2):
            self.buy()
        elif bt.lib.crossover(self.sma2, self.sma1):
            self.sell()
```

# result with tulip sma

![grafik](https://user-images.githubusercontent.com/19193742/82048009-1a6f4180-96b4-11ea-9648-cf0b3d2945d8.png)

# result build in sma

![grafik](https://user-images.githubusercontent.com/19193742/82048063-38d53d00-96b4-11ea-89c2-4446844ca82f.png)

**Comment by kernc** [comment]
What's the value of `self.sma1` and `self.sma2` in each `next()` iteration?

I think the bug may be in your `tulip_pad()` returning a list of one single array, or `Strategy.I()` handling it incorrectly.

**Comment by leonbe** [comment]
Great, that was the right hint.
I had to append ``[0]`` in the return statement of ``tulip_pad``:
```python
return padded[0]
```
such a simple solution... thank you very much!
