### ISSUE TITLE
Sharpe Ratio does not take risk-free rate as a parameter

### ISSUE THREAD

**Issue by afzalmushtaque** [kernc/backtesting.py#71]
Backtesting.py Line #954 

https://github.com/kernc/backtesting.py/blob/7010d68ca3d3593457447e68d19efbf51c14ae72/backtesting/backtesting.py#L952

### Expected Behavior
```py
s.loc['Sharpe Ratio'] = (mean_return - risk_free_return) / (returns.std() or np.nan)
```

### Actual Behavior
```py
s.loc['Sharpe Ratio'] = mean_return / (returns.std() or np.nan)
```

### Additional info
[Sharpe Ratio](https://www.investopedia.com/terms/s/sharperatio.asp)

**Comment by kernc** [comment]
With interest rates effectively zero or negative and with short-term bond yields close to zero, assuming the risk-free rate at 0% was an honest, intended, and not unreasonable simplification.

Does your Sharpe change significantly if you amend it so?

**Comment by afzalmushtaque** [comment]
Yes it does. Risk free rate here in India is ~6%.

**Comment by kernc** [comment]
As a quick workaround, might this fix your Sharpe?

```py
def adjusted_sharpe(stats, riskfree_rate=.06):
    mean_returns = stats['Avg. Trade [%]'] / 100
    return stats['Sharpe Ratio'] / mean_returns * (mean_returns - riskfree_rate)
```

You can also use it to optimize: `Backtest.optimize(..., maximize=adjusted_sharpe)`

**Comment by afzalmushtaque** [comment]
Haha thanks for going the extra mile but that's pretty much what I am already doing. Not a deal breaker for me. However most users kind of expect a risk-free-rate parameter for a Sharpe function coming from other quant packages so I guess adding it avoid some confusion and time spent scouring through the source code to ensure it hasn't been hardcoded to something like 2%.

**Comment by kernc** [comment]
It is since v0.3.2 possible to use [`backtesting.lib.compute_stats`](https://kernc.github.io/backtesting.py/doc/backtesting/lib.html#backtesting.lib.compute_stats) and recompute the statistics with a custom risk-free rate:
```py
stats = Backtest(GOOG, MyStrategy).run()
new_stats = compute_stats(stats=stats, data=GOOG, risk_free_rate=.02)
```
