### ISSUE TITLE
Return [%] Obviously Wrong when applying Backtest() within a For loop

### ISSUE THREAD

**Issue by clousehouse** [kernc/backtesting.py#717]
### Expected Behavior
I'm backtesting something that optimizes EMA for x period, then applies that optimal EMA as the strategy for the next x period. Somehow, this creates mathematically inconsistent stats within backtesting.py. I could tell something was wrong because the test turned $10k into $100b...

### Actual Behavior

- 4 trades
- Avg trade = -0.19%
- But total return = -0.17% (?)

![Screen Shot 2022-08-11 at 7 07 13 PM](https://user-images.githubusercontent.com/111096816/184284987-49829df4-178b-41a9-b720-e33278e6cc1a.png)

- 2 trades
- Avg = 0.16%
- Total return = 1.45% (?)

![Screen Shot 2022-08-11 at 7 06 50 PM](https://user-images.githubusercontent.com/111096816/184284989-c1c77a57-8401-414e-85ec-56f8f606bcba.png)

This example includes an 8-day period instead of a single day. Avg trade is negative, but return is positive:

![Screen Shot 2022-08-11 at 11 49 44 PM](https://user-images.githubusercontent.com/111096816/184287173-872a89a9-557f-4567-8e0b-5e4ab310229a.png)

Every single result gives me incorrect calculations with inflated Return %'s. All inflate it by slightly different amounts.

### Steps to Reproduce

As far as I can tell, this is happening because I'm backtesting within a for loop. Here's the relevant code below:

```python

#set initial value for EMA_length
z = 23
#set initial starting point for Sample period
x = DATA.index[0]
#set starting balance
balance = 10_000

for m, i in zip(DATA.New_Day, DATA.index):

#create a new subset of data each Day
  if m == 1:
    y = i
    Sample = DATA.loc[x:y]

    def EOD_Day():
      return Sample.EOD_status
    def Buyable_Day():
      return Sample.Buyable
    def Shortable_Day():
      return Sample.Shortable

    class EMA(Strategy):

      EMA_length = z

      def init(self):
        self.eod = self.I(EOD_month)
        self.buyable = self.I(Buyable_month)
        self.shortable = self.I(Shortable_month)
        self.EMA = self.I(tb.EMA, self.data.Close, self.EMA_length)

      def next(self):
    #CLOSE
        if self.eod:
          self.position.close()
          #if self.position.is_short or not self.position:  
          #  self.position.close()
          #  self.buy()      
    #SHORT    
        elif self.EMA > self.data.Close:
          if self.position.is_long or not self.position:
            self.position.close()
            self.sell()
    #BUY
        elif self.data.Close > self.EMA:
          if self.position.is_short or not self.position:  
            self.position.close()
            self.buy()

    bt = Backtest(Sample, EMA, cash = balance, commission = .00005, trade_on_close=True)
    
    #backtest current subset using previously determined EMA_length
    stats = bt.run()
    
    #optimize current subset to determine the EMA_length for next subset
    optimize = bt.optimize(
      return_heatmap=True,
      EMA_length = range (5, 20, 1),
      maximize = 'Return [%]'
    )

    print(stats)
    print(optimize)

    #extract optimized EMA_length
    a = ' '.join(str(n) for n in optimize)
    b = re.search('EMA_length=(.*)', a)
    bb = re.search(pattern = "[0-9]+", string = b.group())
    z = float(bb.group())
    
    #extract Final Balance, which will be used as Initial Balance when backtesting the next subset
    c = ' '.join(str(n) for n in stats)
    d = re.search(' days (.*)', c)
    dlist = d.group().split()
    balance = float(dlist[3])

    #end point of current subset is now the starting point for the next subset
    x = y

```

**Comment by kernc** [comment]
> Avg trade = -0.19% But total return = -0.17% (?)

> Avg trade is negative, but return is positive

If you find those strange, I think your assumptions in math might be wrong? What about median and best trades?

Total Return is computed simply:
https://github.com/kernc/backtesting.py/blob/0ce24d80b1bcb8120d95d31dc3bb351b1052a27d/backtesting/_stats.py#L95

And for Avg Return we use [geometric average return](https://www.investopedia.com/ask/answers/06/geometricmean.asp):
https://github.com/kernc/backtesting.py/blob/0ce24d80b1bcb8120d95d31dc3bb351b1052a27d/backtesting/_stats.py#L74
https://github.com/kernc/backtesting.py/blob/0ce24d80b1bcb8120d95d31dc3bb351b1052a27d/backtesting/_stats.py#L133-L136
If there's a bug, please point it out.

**Comment by clousehouse** [comment]
I mean, sorry that I'm not contributing a solution, but denying the mathematical flaws on this is absurd

Consider example #2 for the most obvious case: Show me a set of 2 trades that average +0.16% per trade and net out to +1.45%...

I found the error because I was backtesting recursively (assigning variables based on their prior period's performance). When stacking these inflated return %'s over and over again, the total return approached infinity lol

I'll concede that recursive backtesting is an edge case; I've since written my own framework that better suits those needs. But the fact that the mathematical logic can be broken like this is alarming and merits investigation imo

**Comment by clousehouse** [comment]
You asked about best trade, median trade...

Again look at example 2. It does two trades: best was +0.44%, worst was -0.1%

The avg is correct at ~0.16% but then the total return should be 0.33%. 1.45% is wildly inaccurate. Would love to know if others can reproduce this. My hunch is this inaccuracy is less problematic when calculating eg 1000s of trades instead. If so, we should at least be aware of the fact that combining multiple backtests of low sample size will produce meaningless results
