### ISSUE TITLE
Long-only strategy

### ISSUE THREAD

**Issue by riodda** [kernc/backtesting.py#72]
Hi, i would like to know if it's possible to create a long only strategy without short sell on position close.

**Comment by kernc** [comment]
Sure, you just call [`Strategy.position.close()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Position.close).

**Comment by riodda** [comment]
Yes, this was my first taught, but i have 

AttributeError: 'property' object has no attribute 'close' error.
I probably haven't got yet the librari structure.

I have a buy label from 0-1 and when the label goes over 0.5 i whant the stretegy to buy, if falls below to sell but not short.

`class RF_Label(Strategy):    
        
    def init(self):
        self.rf_buy = self.I(RF_buy, self.data.RF_Label, self.data.PP)
        super().init()
        
    def next(self):
        if not self.position:  # not in the market
            if crossover(self.data.RF_Label,self.data.thersold):
                self.buy()
        else:
            if crossover(self.data.thersold,self.data.RF_Label):
                Strategy.position.close()`

**Comment by riodda** [comment]
Was actually quite easy, self.position.close().....

**Comment by kernc** [comment]
Yeah, "Strategy" in `Strategy.position.close()` just stands for the reference class. The method/accessors are to be called on an instance of said class, here `self`. :+1:
