### ISSUE TITLE
different output for same strategy

### ISSUE THREAD

**Issue by bolka64** [kernc/backtesting.py#732]
Hi everyone,

I'm trying to backtest some strategies. I added EMA 200 to the "init" function. I didn't want to use it in the "next" function, just  wanted to see it in output plot.
When I add EMA200 to my "init" function some parameters like 'Return [%]' are changed .
I don't know why this happened.
I put my jupyter notebook file in the ZIP attached file. 
[Q.zip](https://github.com/kernc/backtesting.py/files/9459396/Q.zip)

**Comment by kernc** [comment]
Your EMA(200) delays trading by the first 200 bars while it's "gathering" values:
https://github.com/kernc/backtesting.py/blob/65f54f6819cac5f36fd94ebf0377644c62b4ee3d/backtesting/backtesting.py#L1147-L1150
I sense this results in a different Return you see.
