### ISSUE TITLE
Option to turn off progress bar in optimization

### ISSUE THREAD

**Issue by gypsyzz** [kernc/backtesting.py#744]
### Expected Behavior

able to turn off progress bar in optimization, or only display the current bar with an option similar to tqdm disable 

### Actual Behavior

progress bar appear for each loop of optimization, which can be lengthy

### Steps to Reproduce

Contain backtest class within another backtest class and optimize parameters while outer loop is running.

```
class stratExt(Strategy):

    optimizeInterval = 48
    
    def init(self):
        pass

   def next(self):
       internalData = self.data.df[-self.optimizeInterval:]
       btInternal = Backtest(internalData, stratInt, cash=10000, commission=.000, exclusive_orders=False, trade_on_close=False)

        if not np.isnan(optimizeRes(btInternal)):
            self.minThresh = optimizeRes(btInternal)

        (some order actions)

class stratInt(Strategy):

    optimizeInterval = 48
    
    def init(self):
        pass

   def next(self):
       (same order actions)

def optimizeRes(btInternal):
    optimizeInternal = btInternal.optimize(optimizeInterval =list(np.arange(20,100,1)), maximize='Equity Final [$]', return_heatmap=True)
    return np.max(optimizeInternal)
```

### Addtional infomation

Using jupyter notebook

**Comment by kernc** [comment]
We are already using [tqdm with `leave=False`](https://github.com/tqdm/tqdm#parameters):
https://github.com/kernc/backtesting.py/blob/592ea4122bfefd9e5b7d5a383aedd7b55e709749/backtesting/backtesting.py#L27
so your notebooks should clear as [our example notebooks do](https://kernc.github.io/backtesting.py/doc/examples/Quick%20Start%20User%20Guide.html#Optimization).

Are you sure progress remains are from the inner loop?

**Comment by gypsyzz** [comment]
Currently it does leave the current progress bar, but creates a new empty line in the process. So at the end of the backtest, there is a huge gap between current cell and next. So for my purpose, I would like to completely remove the progress bar if needed by passing disable=True in place of leave=True.

**Comment by kernc** [comment]
I don't want a new switch for this. Would monkey-patching like this work for you?
```py
import backtesting.backtesting

def identity_function(x, *args, **kwargs):
    return x

backtesting.backtesting._tqdm = identity_function
```

**Comment by kernc** [comment]
Better yet, you can con appropriate tqdm with [`TQDM_*` environment variables](https://github.com/tqdm/tqdm/pull/1491).
