### ISSUE TITLE
Pandas ta STOCH indicator

### ISSUE THREAD

**Issue by flydr2** [kernc/backtesting.py#752]
### Expected Behavior
return the Data as other indicators 

### Actual Behavior

'Indicators must return (optionally a tuple of) numpy.arrays of same '
ValueError: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (4868,); indicator "stoch(H,L,C)"shape: (2, 4855), returned value: [[        nan         nan 47.4032634  ... 95.3968254  92.51461988
  89.47368421]
 [        nan         nan         nan ... 88.2010582  91.65831245
  92.46170983]])

### Steps to Reproduce

import pandas_ta as ta

```python
            def init(self):

                self.st = self.I(ta.stoch, high=self.data.df.High, low=self.data.df.Low, close=self.data.df.Close)

**Comment by kernc** [comment]
The [documentation for `Strategy.I`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.I) clearly states:
> `func` is a function that returns the indicator array(s) of same length as `Strategy.data`

In your case: `ta.stoch` returns 13 values less than the data length, so its return df should be front-padded with nans.

Use a wrapper function to clean the call return value. See e.g. https://github.com/kernc/backtesting.py/discussions/754
