### ISSUE TITLE
Infinite profit when blind-trading with hedging

### ISSUE THREAD

**Issue by oreqizer** [kernc/backtesting.py#767]
I get crazy results from a brainless strategy:

<img width="326" alt="Screenshot 2022-10-06 at 10 26 47" src="https://user-images.githubusercontent.com/11172408/194498938-a2ff65fb-c778-4853-b890-a8287a7a09f8.png">

What I do is specify `hedging=True` and essentially just do this:
1. open buy/sell on cooldown with a stoploss, unless an opposite profitable position exists
2. trail the positions
3. when a position is closed, start again at 1.

I noticed this behavior by adjusting my opening strategy, and noticed that the greater the number of trades, the greater is the profit. This essentially rendered all my attempts at optimising open strategy useless. 😕 

What am I doing wrong?

- Backtesting version: 0.3.3   

My data is EURGBP m15.

**Comment by kernc** [comment]
I'll have to assume you're not setting any [`Backtest(..., commission=)`](https://www.getfreedomain.name/privacy/). Without accounting for spread/commission, any simple SMA crossover strategy would be a hugely profitable one.

**Comment by oreqizer** [comment]
> I'll have to assume you're not setting any [`Backtest(..., commission=)`](https://www.getfreedomain.name/privacy/). Without accounting for spread/commission, any simple SMA crossover strategy would be a hugely profitable one.

you're right, I didn't set commission. I tried to emulate spread since this is a forex-based strategy, but wasn't able to

**Comment by kernc** [comment]
What do you mean, _weren't able to_? Passing `commission=.0002` doesn't work for you?

**Comment by oreqizer** [comment]
> What do you mean, _weren't able to_? Passing `commission=.0002` doesn't work for you?

hmm I did not try that. I was trying to manually adjust the current price when setting trades, but that broke the system. I will try that. thanks

**Comment by texasraj** [comment]
I have seen similar things.. when limit is set in the self.buy or self.sell, results are completely different.. if I use the same data and limit buy sells and calculate profits, they're completely different.. looks like this module is not reliable for judging the strategies.. based on the results

**Comment by texasraj** [comment]
Start                                       0
End                                     49999
Duration                                49999
Exposure Time [%]                      48.278
Equity Final [$]                      31894.5
Equity Peak [$]                       31894.5
Return [%]                            32.8937
Buy & Hold Return [%]               -0.118121
Return (Ann.) [%]                           0
Volatility (Ann.) [%]                     NaN
Sharpe Ratio                              NaN
Sortino Ratio                             NaN
Calmar Ratio                                0
Max. Drawdown [%]                  -0.0898333
Avg. Drawdown [%]                 -0.00928412
Max. Drawdown Duration                    165
Avg. Drawdown Duration                10.7615
# Trades                                  376
Win Rate [%]                           99.734
Best Trade [%]                       0.166736
Worst Trade [%]                            -0
Avg. Trade [%]                      0.0813345
Max. Trade Duration                       331
Avg. Trade Duration                   63.1995
Profit Factor                             NaN
Expectancy [%]                      0.0813358
SQN                                   87.2059
_strategy                    es_tick_strategy
_equity_curve                     Equity  ...
_trades                        Size  Entry...
dtype: object


Simple SMA.. but unreal numbers.. deployed the code in real bot and surprised and incurred losses.

        if self.short_signal != "SHORT" and self.sma1[-1] < self.sma1[-2] < self.sma1[-3]:
            self.sell(limit=self.close[-1] , tp=self.close[-1]-4, stop=self.close[-1] + 2)
            self.short_signal = "SHORT"

        if self.short_signal == "SHORT" and self.sma1[-1] > self.sma1[-2]:
            self.position.close()
            self.short_signal = "COVER"

I have used the same exact limits, take profit and stop losses in the real bot.

**Comment by kernc** [comment]
For the time being, we'll have to assume passing `Backtest(..., commission=>0)` better aligns results with expectations.

**Comment by texasraj** [comment]
Here is another clue. Limit is driving the calculations wrong for some reason.. I cant believe this.. verified manually. its tick data and there is no big difference in the prices from tick to tick:

self.sell(limit=self.close[-1])  
..
self.position.close()


Start                                       0
End                                     49999
Duration                                49999
Exposure Time [%]                      48.522
Equity Final [$]                      25872.5
Equity Peak [$]                       25872.5
Return [%]                            7.80222
Buy & Hold Return [%]                0.048601
Return (Ann.) [%]                           0
Volatility (Ann.) [%]                     NaN
Sharpe Ratio                              NaN
Sortino Ratio                             NaN
Calmar Ratio                                0
Max. Drawdown [%]                  -0.0482785
Avg. Drawdown [%]                  -0.0100691
Max. Drawdown Duration                    500
Avg. Drawdown Duration                15.9185
# Trades                                  310
Win Rate [%]                          97.4194
Best Trade [%]                       0.138525
Worst Trade [%]                  -0.000500003
Avg. Trade [%]                       0.026528
Max. Trade Duration                       663
Avg. Trade Duration                   77.2613
Profit Factor                         2057.07
Expectancy [%]                      0.0265301
SQN                                   23.2671
_strategy                    es_tick_strategy
_equity_curve                         Equi...
_trades                        Size  Entry...
dtype: object


self.sell()  
..
self.position.close()

Start                                       0
End                                     49999
Duration                                49999
Exposure Time [%]                      48.522
Equity Final [$]                      23911.1
Equity Peak [$]                       24039.8
Return [%]                          -0.370518
Buy & Hold Return [%]                0.048601
Return (Ann.) [%]                           0
Volatility (Ann.) [%]                     NaN
Sharpe Ratio                              NaN
Sortino Ratio                             NaN
Calmar Ratio                                0
Max. Drawdown [%]                   -0.596117
Avg. Drawdown [%]                  -0.0302652
Max. Drawdown Duration                  45189
Avg. Drawdown Duration                1162.88
# Trades                                  310
Win Rate [%]                          23.5484
Best Trade [%]                       0.110751
Worst Trade [%]                    -0.0353628
Avg. Trade [%]                    -0.00133355
Max. Trade Duration                       663
Avg. Trade Duration                   77.2613
Profit Factor                        0.832428
Expectancy [%]                    -0.00133147
SQN                                  -1.14489
_strategy                    es_tick_strategy
_equity_curve                          Equ...
_trades                        Size  Entry...
dtype: object

**Comment by kernc** [comment]
@texasraj Please open a new bug report for your issues, and I'll be happy to have a serious look. If so capable, please follow [contributing guidelines regarding how to report bugs effectively](https://github.com/kernc/backtesting.py/blob/master/CONTRIBUTING.md#issues) as what you've blurted above isn't something we can use. Until then, let's shed the vehemence and assume simply that some of _your assumptions_ about this framework might be wrong. :slightly_smiling_face:

**Comment by texasraj** [comment]
Sorry about that. I’ll open another case. I do love this library and would be great to get this validated. I’ll  be happy to share my screen and show the results here.

**Comment by texasraj** [comment]
Thanks Kernc. I have spent two days to find out the cause.. I have figured out the differences.. its the data issue for tick data.. Sorry about the trouble here.. I've deleted all the blurts :)

This library rocks ... thanks much!!!

**Comment by texasraj** [comment]
> Here is another clue. Limit is driving the calculations wrong for some reason.. I cant believe this.. verified manually. its tick data and there is no big difference in the prices from tick to tick:
> 
> # self.sell(limit=self.close[-1])
> ..
> 
> # self.position.close()
> Start 0 End 49999 Duration 49999 Exposure Time [%] 48.522 Equity Final [$] 25872.5 Equity Peak [$] 25872.5 Return [%] 7.80222 Buy & Hold Return [%] 0.048601 Return (Ann.) [%] 0 Volatility (Ann.) [%] NaN Sharpe Ratio NaN Sortino Ratio NaN Calmar Ratio 0 Max. Drawdown [%] -0.0482785 Avg. Drawdown [%] -0.0100691 Max. Drawdown Duration 500 Avg. Drawdown Duration 15.9185 Trades 310 Win Rate [%] 97.4194 Best Trade [%] 0.138525 Worst Trade [%] -0.000500003 Avg. Trade [%] 0.026528 Max. Trade Duration 663 Avg. Trade Duration 77.2613 Profit Factor 2057.07 Expectancy [%] 0.0265301 SQN 23.2671 _strategy es_tick_strategy _equity_curve Equi... _trades Size Entry... dtype: object
> 
> # self.sell()
> ..
> 
> # self.position.close()
> Start 0 End 49999 Duration 49999 Exposure Time [%] 48.522 Equity Final [$] 23911.1 Equity Peak [$] 24039.8 Return [%] -0.370518 Buy & Hold Return [%] 0.048601 Return (Ann.) [%] 0 Volatility (Ann.) [%] NaN Sharpe Ratio NaN Sortino Ratio NaN Calmar Ratio 0 Max. Drawdown [%] -0.596117 Avg. Drawdown [%] -0.0302652 Max. Drawdown Duration 45189 Avg. Drawdown Duration 1162.88 Trades 310 Win Rate [%] 23.5484 Best Trade [%] 0.110751 Worst Trade [%] -0.0353628 Avg. Trade [%] -0.00133355 Max. Trade Duration 663 Avg. Trade Duration 77.2613 Profit Factor 0.832428 Expectancy [%] -0.00133147 SQN -1.14489 _strategy es_tick_strategy _equity_curve Equ... _trades Size Entry... dtype: object


Just realized that the data quality is not good from the provider.. This library rocks!!! Thanks!!!
