### ISSUE TITLE
Backtest.optimize() function not running in parallel.

### ISSUE THREAD

**Issue by JensvandeZande** [kernc/backtesting.py#777]
### Expected Behaviour
All my cores will be utilised when optimizing the hyper-parameters

### Actual Behaviour
I get a userwarning and the execution is done sequentially.
UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` 

- Backtesting version: "0.3.3"

**Comment by kernc** [comment]
Good job on discovering that relevant warning! Did you happen to consider maybe [looking it up](https://www.google.com/search?q=set+multiprocessing+start+method+to+fork)? :sweat_smile: 

It [boils down to](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method):
```py
import multiprocessing as mp

mp.set_start_method('fork')
```
placed somewhere before `Backtest.optimize()` call.

**Comment by JensvandeZande** [comment]
Ah sorry for the inconvenience. Thanks for the fast reply.
