### ISSUE TITLE
AttributeError:'Bband object has no attribute 'close'

### ISSUE THREAD

**Issue by nicksim91** [kernc/backtesting.py#78]
Hi,

I'm fairly new to python. Wanted to use backtesting.py to set a strategy for bollinger bands. 

my strategy is rougly like below: 
def BBupper(values, n, std):
    """
    Return simple moving average of `values`, at
    each step taking into account `n` previous values.
    """
    rolling_mean = pd.Series(values).rolling(n).mean()
    rolling_std = pd.Series(values).rolling(n).std()
    return rolling_mean + rolling_std*std

def BBmid(values, n, std):
    """
    Return simple moving average of `values`, at
    each step taking into account `n` previous values.
    """
    rolling_mean = pd.Series(values).rolling(n).mean()
    rolling_std = pd.Series(values).rolling(n).std()
    return rolling_mean

def BBlower(values, n, std):
    """
    Return simple moving average of `values`, at
    each step taking into account `n` previous values.
    """
    rolling_mean = pd.Series(values).rolling(n).mean()
    rolling_std = pd.Series(values).rolling(n).std()
    return rolling_mean - rolling_std*std

from backtesting import Strategy
from backtesting.lib import crossover

class BBand(Strategy):
    
    # Define the two MA lags as *class variables*
    # for later optimization
    n = 10
    std = 2
    
    def init(self):
        
        self.upperband = self.I(BBupper, self.data.close, self.n, self.std)
        self.middleband = self.I(BBmid, self.data.close, self.n, self.std)
        self.lowerband = self.I(BBlower, self.data.close, self.n, self.std)
    
    def next(self):
        # If close crosses above upperband, buy the asset
        if crossover(self.close, self.upperband):
            self.sell()

        # Else, if close crosses below lowerband, sell it
        elif crossover(self.close, self.lowerband):
            self.buy()

from backtesting import Backtest

bt = Backtest(euraud, BBand, cash=10000, commission=.002)
bt.run()

when i run the last step, i get this error. how do i get the program to pull the 'close' data from my file?

AttributeError: 'BBand' object has no attribute 'close'

**Comment by sdmovie** [comment]
capital issue - Bband require "close" while data feed is "Close".

**Comment by kernc** [comment]
Luckily, the capital issue is easily remedied: just pass it the uppercase `Close`:
```py
self.upperband = self.I(BBupper, self.data.Close, self.n, self.std)
...
if crossover(self.data.Close, self.upperband):
```

**Comment by nicksim91** [comment]
Thanks for the help!
