### ISSUE TITLE
Buy on T+1/2/3..../N days

### ISSUE THREAD

**Issue by susuusus** [kernc/backtesting.py#786]
Hi,

 Is it possible to buy or sell on T+1/2/3.../N days . Now its only buy/sell on T day.

**Comment by kernc** [comment]
You can use instance variables to keep and manage your state:
```py
def next(self):
    if signal_condition():
        self.counter = 3  # Buy on bar T+3
    self.counter -= 1
    if self.counter < 0:
        self.buy(...)
        self.counter = float('inf')  # Reset
```
For general questions and help, please use the forums.
