### ISSUE TITLE
Wrong calculation of PnL?

### ISSUE THREAD

**Issue by bizeasy17** [kernc/backtesting.py#795]
Hi Kernc:

I run the sample code which shows as the code snippet and i printed out the trades as screenshot shows, but seems the PnL calculation is wrong?

e.g. EntryPrice - 371, ExitPrice - 405 but the PnL is -884? it is a negative value?  

### Expected Behavior
But in this case the PnL should be anyhow a positive value which is (405 - 371) * (10000 / 371) = ~916 (regardless of commission).  

### Actual Behavior
![截屏2022-11-01 上午9 02 45](https://user-images.githubusercontent.com/28600032/199136490-6a130c51-4f63-408b-9e80-c50f8bdb853e.png)

### Steps to Reproduce

```python

from backtesting import Backtest, Strategy
from backtesting.lib import crossover

from backtesting.test import SMA, GOOG


class SmaCross(Strategy):
    n1 = 20
    n2 = 200

    def init(self):
        close = self.data.Close
        self.sma1 = self.I(SMA, close, self.n1)
        self.sma2 = self.I(SMA, close, self.n2)

    def next(self):
        if crossover(self.sma1, self.sma2):
            self.buy()
        elif crossover(self.sma2, self.sma1):
            self.sell()


bt = Backtest(GOOG, SmaCross,
              cash=10000, commission=.001,
              exclusive_orders=True)

output = bt.run()
trades = output.loc['_trades']
print(trades)
bt.plot()

```

### Additional info

- Backtesting version: 0.3.3

**Comment by bizeasy17** [comment]
that is miss understanding, sorry.

**Comment by kernc** [comment]
Yeah, it's all got to do with the minus signs in the Size column and whether the order is long or short.
