### ISSUE TITLE
TA-Lib indicators not stats

### ISSUE THREAD

**Issue by eramosr16** [kernc/backtesting.py#801]
### Expected Behavior

Using ta-lib indicators should produce stats 

### Actual Behavior

Stats after running strategy comes empty

### Steps to Reproduce
Use SmaCross from examples, replace:

```python
    self.ma1 = self.I(SMA, price, 10)
    self.ma2 = self.I(SMA, price, 20)
``` 

With:      

```python   
       self.ma1 = talib.EMA(price, 10)
        self.ma2 = talib.EMA(price, 20)
```

### Additional info
- Backtesting version: 0.3.3

**Comment by kernc** [comment]
[`Strategy.I()`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.I) takes a function reference + args:
```py
self.ma1 = self.I(talib.EMA, price, 10)
