### ISSUE TITLE
Add support for tick data

### ISSUE THREAD

**Issue by casperbh96** [kernc/backtesting.py#818]
Very concretely, I wish for there to be added support for tick data in the backtest.

One example of how it could work:
- Your backtest is on the 5m timeframe
- You can additionally pass a 1m timeframe or even down to 1 second data

Benefits:
- More accurate results when backtesting, more accurate trigger on stop loss and take profits
- More flexibility in your strategies, e.g. you can implement an approach to check if the tick distribution fits your assumptions

Cons:
- Could possibly be slower because of increased size of data, but this can be resolved with making it optional and keep the normal functionality just as fast as always

**Comment by kernc** [comment]
See https://github.com/kernc/backtesting.py/issues/130#issuecomment-678784147.

Simply begin/run the backtest on 1m or 1s instead of the 5m timeframe? 🤨
