### ISSUE TITLE
Profit factor statistic

### ISSUE THREAD

**Issue by TomaszLakota** [kernc/backtesting.py#84]
Hey, this is one great backtesting framework. 
I'm surprised that there is no profit factor (gross profit/gross loss) in backtest stats. 
Why is that? Is that something you could add?

**Comment by kernc** [comment]
Thanks. We have expectancy which maybe is similar:
https://github.com/kernc/backtesting.py/blob/b460092c5e832706596ac6652eb1762b22044a95/backtesting/backtesting.py#L948-L949
Is profit factor something _you_ could add? :smiley:

**Comment by TomaszLakota** [comment]
How could I not do that, if you made it that easy for me? :) Can I place it between # Trades and Win rate?

**Comment by kernc** [comment]
I would prefer it a bit further down, maybe before Expectancy or after SQN.

**Comment by TomaszLakota** [comment]
Sure. Added PR #85.

**Comment by TomaszLakota** [comment]
Adjusted test.
