### ISSUE TITLE
And debug guide for nan result?

### ISSUE THREAD

**Issue by eromoe** [kernc/backtesting.py#857]
I am backtesting BTC price in minute( every minute predict next 15 minute pct return),  strategy is from https://kernc.github.io/backtesting.py/doc/examples/Trading%20with%20Machine%20Learning.html 
But the result stats are nan .

I can confirm that are many `buy` & `sell` triggered :
![image](https://user-images.githubusercontent.com/3938751/210205126-069ba490-31ff-4f8a-94fb-369cb03c8099.png)

This is confusing, I need clue to debug the problem

**Comment by kernc** [comment]
This has got to do with btc price around nearing 60k but only starting with 10k of cash, so not a single unit can be bought. See https://github.com/kernc/backtesting.py/issues/134.
