### ISSUE TITLE
dealing with large data sets

### ISSUE THREAD

**Issue by jamhot1** [kernc/backtesting.py#86]
I tried to process a data set with 5000 bars aprx 8 years of hourly data. 

The algo got about 3 years through and stopped simulating trades. Is there a limit to the data set size?

**Comment by kernc** [comment]
> Is there a limit to the data set size?

Only as confined by available runtime system resources, such as virtual memory in particular. Normally, 8k bars is not a lot and should, for simpler strategies, run in a few seconds.

What is your strategy like? What do you mean by "stopped simulating trades"?

**Comment by jamhot1** [comment]
Hi Kernc. Sorry, I missed a zero from that. its 50k of bars, not 5k. What I mean is that it stops any buy and sells after just under 3 years very abruptly. See attached. There seems to be a high density of trades within the 3 years.
![graph](https://user-images.githubusercontent.com/35459836/84374399-d8172280-abd5-11ea-86e8-e0aea4b7f12a.png)

**Comment by kernc** [comment]
That's very curious indeed. Without insight into reproducible strategy code itself, I'd suggest clipping the data to sufficient one third and placing a breakpoint somewhere into `_Broker.next()` to investigate what is going on:
https://github.com/kernc/backtesting.py/blob/0436e56ab42186a167c5ee187ff33e40eb39334b/backtesting/backtesting.py#L529-L533
For lack of better debugging means given unfamiliarity of your environment, I guess you could use [ipdb debugger](https://gist.github.com/mono0926/6326015#place-a-breakpoint-in-your-code):
```bash
pip install ipdb
```
and to set the breakpoint:
```py
import ipdb; ipdb.set_trace()
```
where you want the Python interpreter to stop to investigate. I think this should work within Jupyter notebooks too.

**Comment by kernc** [comment]
@jamhot1 Have you maybe figured something out? :smiley:

**Comment by kernc** [comment]
Closing this issue as unreproducible. If not the case, reopen.
