### ISSUE TITLE
bt.plot() indicators computed in next()

### ISSUE THREAD

**Issue by sidsidsidsid** [kernc/backtesting.py#87]
First, great product. I've been looking for something like this for a while.  What are your future plans/direction with the product?

Second, my question is an extension of issue #74. I understand how to add indicators. But, is there a way that their results are added to the `bt.plot()`? For example below; I would like `indicator1` and `indicator2` plotted. Note: my indicators do not pass in any values created in the `init()` method.

I thought of wrapping them in the `self.I()`, but as stated above, they are using data created from data generated in the `init()`. Is there a way to get `c_var` and `s_var` plotted using `bt.plot()`.

```py
def myIndicator1():
   value = ...
   return value

def myIndicator2():
   value = ...
   return value

class SmaCross(Strategy):
    def init(self):
        self.sma1 = self.I(SMA, self.data.Close, self.n1)
        self.sma2 = self.I(SMA, self.data.Close, self.n2)
    
    def next(self):
        c_var = (self.sma1 * 345).std() - 5
        out = myIndicator( c_var)
        s_var = out.std()
        results = myIndicator2(s_var)

```

Thanks

**Comment by kernc** [comment]
> What are your future plans/direction with the product?

PR #47 is expected to be merged once some remaining edges are smoothed out.

-------

I understand you'd like to define and show an indicator whose values are computed in `next()` instead of in `init()`.

First of all, it's usually _incomparably faster_ to precompute values in vector form in `init()`.

When the computation can't be simply or clearly vectorized, you can probably do something like:
```py
class SomeStrategy(Strategy):
    def init(self):
       # Pre-allocate and designate an indicator, fill with NaNs
       self.indicator = self.I(lambda: np.repeat(np.nan, len(self.data.Close))

    def next(self):
       # Compute indicator value at time t
       values = myIndicator(self.data.Close, ...)
       # If myIndicator returns a vector, we are only interested in its last value
       value = values[-1]

       self.indicator[-1] = value
```
This is from top of the head. Let me know if it works.

**Comment by sidsidsidsid** [comment]
Thanks. I believe your answer has given me a better understanding of what you are attempting with the framework. I will try again to place the indicator in the init() and if that fails, then try your recommendation.

Thanks for the help

**Comment by kernc** [comment]
Hopefully you got it working. :rocket:
