### ISSUE TITLE
bt.plot possible enhancement - plot organization and/or grouping. 

### ISSUE THREAD

**Issue by sidsidsidsid** [kernc/backtesting.py#88]
Strategy1 below:
I noticed that an overlayed plot would be created for self.m1, self.m2, and self.m3, and candlestick. But, 3 plots will be created for each self.m4, self.m5, and self.m6. Is there a way to overlay a second plot that would combine self.m4, self.m5, and self.m6?

Strategy2 below:
If the above is not possible, I have an enhancement request. Add a flag to selfI() that tells how the plots should be organized. A flag would tell the grouping/overlays and the order of the plots. See below

```py
class Strategy1(Strategy):
    def init(self):
        Close = self.data.Close
        self.m1  = self.I(Indicator_1, Close)
        self.m2  = self.I(Indicator_1, Close)
        self.m3  = self.I(Indicator_1, Close)
       
	Var = (self.data.High + self.data.Close) * 100
        
        self.m4  = self.I(Indicator_2, Var)
        self.m5  = self.I(Indicator_2, Var)
        self.m6  = self.I(Indicator_2, Var)

     def next(self):
        ...

class Strategy2(Strategy):
    def init(self):
        Close = self.data.Close
        self.m1  = self.I(Indicator_1, Close,overlay_group=1)
        self.m2  = self.I(Indicator_1, Close,overlay_group=1)
        self.m3  = self.I(Indicator_1, Close,overlay_group=1)
       
	Var = (self.data.High + self.data.Close) * 100
       
        self.m4  = self.I(Indicator_2, Var,overlay_group=2)
        self.m5  = self.I(Indicator_2, Var,overlay_group=2)
        self.m6  = self.I(Indicator_2, Var,overlay_group=2)

     def next(self):
        ...
```

**Comment by sidsidsidsid** [comment]
Typo  -->   class Strategy@ = class Strategy2

**Comment by kernc** [comment]
`self.I(..., overlay=True)`, [as documented](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.I), already forces the defined indicator to be overlaid on the OHLC chart. By default, a heuristic determines whether the indicator should be overlaid or not.

When an indicator is not overlaid over OHLC chart, it is plotted separately under it.

One way to plot multiple non-overlaid indicators on the same underneath plot is to define a new indicator that returns a _tuple of indicators_ that are to be plotted together: 
```py
    def init(self):
        def new_indicator(values):
            return (Indicator1(values),
                    Indicator2(values),
                    Indicator3(values))
        self.I(new_indicator, self.data.Close, overlay=False)
```

**Comment by sidsidsidsid** [comment]
Thanks for the response.

A new plot with the six indicators was created and overlaid. Cool!

Questions:
[1] Is it still needed to create the 6 self.mX variables as below? Is your recommend snippet only purpose to create multiple plots with multiple indicators? For the future; It would be interesting to understand any other use-cases and/problems this code snippet could solve.
[2] The plot legend is not showing all the indicator items, it appears to cut-off once it gets to the 4th indicators. Also, the legend is not labelling, the four it does show, names correctly.

Thanks

def new_indicator(value,one,two,three,four,five,six):
            return (Indicator1(value,one),
                    Indicator2(values,two),
                    Indicator3(values,three),
		    Indicator4(values,four),
                    Indicator5(values,five),
		    Indicator6(values,six))
                    
class Strategy2(Strategy):
    def init(self):
       
	Var = (self.data.High + self.data.Close) * 100
       
        self.m1  = self.I(Indicator1, Var,overlay=False,plot=False)
        self.m2  = self.I(Indicator2, Var,overlay=False,plot=False)
        self.m3  = self.I(Indicator3, Var,overlay=False,plot=False)
        self.m4  = self.I(Indicator1, Var,overlay=False,plot=False)
        self.m5  = self.I(Indicator2, Var,overlay=False,plot=False)
        self.m6  = self.I(Indicator3, Var,overlay=False,plot=False)

        self.I(new_indicator, self.data.Close,234,78,9.2,21111,4n5,900, overlay=False)

     def next(self):
	code

**Comment by kernc** [comment]
> 1. Is it still needed to create the 6 self.mX variables as below?

Not really, unless you are aware that `self.m1` and `new_indicator()[0]` compute different values (e.g. one uses `(High + Close) * 100`, the other `Close` only).

Indeed, my snippet's only purpose is to show how to plot a non-overlaid chart with multiple indicators. In fact, `self.m1` (...) are actually far more easily and transparently used in strategy logic / computation.

> 2. The plot legend is not showing all the indicator items, it appears to cut-off once it gets to the 4th indicators.

This likely stems from the fact that the underlying plot is not high enough for so many legend labels:
https://github.com/kernc/backtesting.py/blob/0436e56ab42186a167c5ee187ff33e40eb39334b/backtesting/_plotting.py#L191-L196
Plotting more than four lines on such a tiny chart is unclear and should likely be avoided.

> Also, the legend is not labelling, the four it does show, names correctly.

The names of the encompassing indicator are used: `new_indicator-1`, `new_indicator-2`, ... I think this gets improved a bit in #47.

**Comment by kernc** [comment]
Let's consider this roughly addressed and behavior satisfactory. Try v0.2.0 for improvements.
