### ISSUE TITLE
Orders closed when TP/SL hit by High/Low

### ISSUE THREAD

**Issue by packandsell** [kernc/backtesting.py#9]
When working with O,H,L,C and having TP/SL which is within the range of H/L, does the lib automatically close orders inside the bar, not on actual borders of the range? Sorry, not an issue,  just to be sure...

**Comment by kernc** [comment]
If SL/TP are touched anywhere within the candle (e.g. `low <= sl <= high`), the position is considered closed at the price specified (e.g. `sl`) (except if Open price gaps, in which case the position is closed at the Open price).
https://github.com/kernc/backtesting.py/blob/8e2bfb53220c9a67c33a5c8b60a92d33f2128f43/backtesting/backtesting.py#L536-L554

**Comment by packandsell** [comment]
Thanks a lot for confirmation!

**Comment by packandsell** [comment]
Sorry, one more: a tricky one. Let's say I'd like to open my orders like limit orders, so instead of buy/sell, I'd be waiting for the price to move in the direction of threshold after bar opening, and once the threshold is hit, I'd like it to open that trade:

Q1: can that be simulated without providing the history of price on lower time-frames within the bar? (I guess - no). If this possible at all, given I specify that tick or 1-min or some lower-timeframe data-series?

Q2: can it simulate that kind of behavior (pending orders) multiple times within the bar, as technically such setup can happen multiple times, eg: 
(SL=0.0010, TP=0.0050)
1.  open price is 1.5000, buy pending with threshold of 0.0010
2. when the price is 1.5010 the system buys, SL is 0.0005 => 1.5005
3. the price hits 1.5005 and closes
4. now another pending is set for 1.5015 (0.0010 threshold), TP is 0.0050 => 1.5065
5. whenever TP/SL is hit, we continue creating pending orders with TP/SL and thresholds like above.

**Comment by kernc** [comment]
Backtesting supports limit orders via `Strategy.buy(price=...)`, but you're looking for a [stop-limit order](https://www.investopedia.com/terms/s/stop-limitorder.asp). Not currently possible without bars on lower time frames. :disappointed:  It's on the eventual roadmap, as I've been thinking on using this myself, but unless someone contributes a PR with it, with no temporal deadlines.

The second question is not really feasible. A candlestick bar is always just the aggregate of price changes that happened inside it.
https://github.com/kernc/backtesting.py/blob/8e2bfb53220c9a67c33a5c8b60a92d33f2128f43/backtesting/lib.py#L28-L40
There is no way to know what price level came first or how the price moved inside the bar, so backtesting.py just pessimistically assumes the worst by first checking if SL was hit, then TP, once per bar.

**Comment by packandsell** [comment]
Aha, thx for clarification.
