### ISSUE TITLE
optimization using linked parameters not working

### ISSUE THREAD

**Issue by gypsyzz** [kernc/backtesting.py#920]
### Expected Behavior
optimization using 1 parameter for a pair of parameters, such as RSI high and low, controlled by mid +- diff

### Actual Behavior

parameter does not vary, showing the same results for optimization.

Have to code the pair of parameters as separate and use constraint.

### Steps to Reproduce

class RSIStrategy(Strategy):

    periods = 12
    rsi_diff = 20
    low_thresh = 50 - rsi_diff
    high_thresh = 50 + rsi_diff

    def init(self):
        self.rsi_high = self.I(RSI, self.data.High, self.periods)
        self.rsi_low = self.I(RSI, self.data.Low, self.periods)

    def next(self):

        if self.rsi_low[-1] < self.low_thresh:
            self.buy(size=0.001)
 
        if self.rsi_high[-1] > self.high_thresh:
            self.sell(size=0.001)

optimize_result = bt.optimize(rsi_diff=list(np.arange(10,30,2)), maximize='Equity Final [$]', return_heatmap=True)
optimize_result[1]

### Additional info
The code block below works:
optimize_result = bt.optimize(low_thresh=list(np.arange(10,40,2)), high_thresh=list(np.arange(10,40,2)), maximize='Equity Final [$]',constraint=lambda p: p.low_thresh == p.high_thresh, return_heatmap=True)
optimize_result[1]

**Comment by gypsyzz** [comment]
rsi_diff is used by low_thresh and high_thresh, so you're saying that only variables used in init() or next() will change, and not the part before that.

**Comment by kernc** [comment]
Indeed, this is how Python works. [Class variables](https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables) are assigned values upon class _declaration_.

**Comment by gypsyzz** [comment]
okay something new about Python everyday
