### ISSUE TITLE
Is here a method to make the size of P/L triangle directly proportional to the P/L number?

### ISSUE THREAD

**Issue by rusty-peilin** [kernc/backtesting.py#937]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/77475610/225559560-b6c215ca-130e-4e2f-a744-ad6174b9dd0d.png">

As you can see in the picture, the green triangle is smaller than the red one, but it has a larger P/L number. I'm wondering if there's a way to make the size of the P/L triangle directly proportional to the P/L number. If we can do that, it would help us analyze our strategy more accurately.

**Comment by kernc** [comment]
Size indicates (absolute) [trade size](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Trade.size). P/L is already indicated by the _vertical offset_, as the axis says.

**Comment by rusty-peilin** [comment]
> Size indicates (absolute) [trade size](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Trade.size). P/L is already indicated by the _vertical offset_, as the axis says.

I see, I understood, thanks!
