### ISSUE TITLE
How to make the backtesting continue eventhough I got a forced liquidation in a single trade.

### ISSUE THREAD

**Issue by rusty-peilin** [kernc/backtesting.py#938]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/77475610/225706597-075f9c2b-1a83-46d2-bddb-03cc08300f93.png">
As shown in the picture, I experienced a forced liquidation during my second trade due to setting my margin to 0.01. To avoid this, I added "size=0.5" to both my self.buy() and self.sell() functions, which allowed me to still have 50% of my funds available for future trades even after the forced liquidation occurred. However, the backtesting ended prematurely due to the forced liquidation. Can you please advise me on how to continue the backtesting process?

**Comment by kernc** [comment]
Note with `margin=.01`, you're trading with 100x leverage. Reduce your leverage first or reduce your order sizes or simply improve your strategy entry/exit times. 🙂

By simple design, the backtest ends when [`Strategy.equity <= 0`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.equity) — you lost.
