### ISSUE TITLE
Why the use of Bokeh for graphing and not plotly?

### ISSUE THREAD

**Issue by jamhot1** [kernc/backtesting.py#94]
Just a general question to understand the choice?

**Comment by kernc** [comment]
No particular reason. The shoe fit. I view Bokeh as better integrated with PyData ecosystem, which is what the project already relies on.

What are you missing?

**Comment by jamhot1** [comment]
Nothing missing. I was digging around and decided to see how they compare. Was only interested in what drove the choice in particular if any. 👍

**Comment by kernc** [comment]
What did you find? Would you have chosen Plotly and why? :smiley:

**Comment by guzuomuse** [comment]
suggest plotly as an option so that we can choose bokeh or plotly ...etc..

**Comment by kernc** [comment]
@guzuomuse any solid justification for that seemingly needless doubling of effort?
