### ISSUE TITLE
Stocks Screener

### ISSUE THREAD

**Issue by AliFurqanHaider** [kernc/backtesting.py#96]
I want to screen stocks in which 6 EMA is crossing above 18 EMA in last 7 days. Please guide.
Example: If there are a total 200 stocks in a given stock index (example KSE-100) i would want  to see only those stocks in which 6EMA has crossed above 18EMA recently, ie in a period of 7 days.

**Comment by kernc** [comment]
Well, this is a backtesting _framework_. It does presuppose some knowledge of [Python](https://www.python.org/). In Python, you could screen those stocks simply:
```py
from talib import EMA, MAX

stocks = [ ... ]

for stock in stocks:
    close = stock.Close
    if MAX(EMA(close, 6) > EMA(close, 18), 7) == 1:
        print(stock)  # This stock matches 👍
```

Hope this helps.

**Comment by AliFurqanHaider** [comment]
Ok. Thank you for the help.. I'll try this code.

Regards,
Ali Furqan.
