### ISSUE TITLE
not opening position at the given level

### ISSUE THREAD

**Issue by zeshansari** [kernc/backtesting.py#964]
Expected Behavior
open position at 3903 and take profit at 3911

Actual Behavior
open position at 3911.05 and take profit at 3911.5

Steps to Reproduce
guys i am having trouble with following code, i set buying order with a condition so it should open position when close price hit the given level and it does, but take buy position at the wrong level which is not given anywhere but one thing is there that it open order just before given tp level and close position at earliest with profit of 0.5 points only. Although as per the given code it should open position at close price i.e. 3903 when the given condition is true but instead it open position at 3911 and closing it at 3911.5. can anyone help how can i resolve this problem?

```python

def trade_level(self):
if self.data.close <= 3903 +1 and self.data.close >= 3903 - 1:
self.buy(sl= 3903 - 2, tp= 3903 + 9)

```

### Additional info

- Backtesting version: 0.3.3   
- `bokehJS 2.4.3:
- OS: Windows 11

**Comment by manageseverin** [comment]
Do you think it correlates to the initial cash ?
```
t = Backtest(df, SmaCross,
              cash=30000, commission=0.002,
              exclusive_orders=True)
```

**Comment by zeshansari** [comment]
> Do you think it correlates to the initial cash ?
> 
> ```
> t = Backtest(df, SmaCross,
>               cash=30000, commission=0.002,
>               exclusive_orders=True)
> ```

I don't think so because it is taking position but not at the given level. I need to open position at the market execution price but I don't know why it use to open position 8 points ahead of the given level everytime, and I don't understand why it is happening.

**Comment by zeshansari** [comment]
> exclusive_orders=True

I have tried adding "exclusive_orders=True" and it changed to results, but again it is not honoring my strategy and given levels and thats my issue. Why it is not honoring my strategy and given levels?

**Comment by zeshansari** [comment]
this is the true picture of my question, my given level was 3869, and that bar where my position was opened OHLC contain my given level so it took action at the right time but it opened my buy position at the wrong level at 3877 which is not even in the OHLC of that bar. it opened my position somewhere out of the current bar where my condition got true, but it closes that position exactly at the given tp level. So, the problem is at the position opening time and its level whether it is buy or sell.  


![image](https://user-images.githubusercontent.com/130185897/233871243-9e6ba01a-25de-4ea1-80ba-75eae3b95730.png)

**Comment by kernc** [comment]
It's your `commission=`. See FAQ https://github.com/kernc/backtesting.py/issues/538, https://github.com/kernc/backtesting.py/issues/633.

**Comment by zeshansari** [comment]
> It's your `commission=`. See FAQ #538, #633.

I have removed 'commission=' from my code and now its working, Thanks alot problem solved.
