### ISSUE TITLE
How can I write right code for market execution orders?

### ISSUE THREAD

**Issue by zeshansari** [kernc/backtesting.py#966]
### Expected Behavior
trade on close price 

### Actual Behavior
trading 8 points ahead of closing price

### Steps to Reproduce

I am backtesting my code using backtesting in Python 3 and I am using self.buy or self.sell to open a new position but it used to open my position 8 points ahead of given buy/sell level but I want to execute order at the current level at closing price like Market Execution order in MT5.

What I understand by this that self.buy or self.sell function is used for limit orders only but not for market execution orders.

How can I write right code for market execution orders?

Additional info
Backtesting version: 0.3.3
`bokehJS 2.4.3:
OS: Windows 11

**Comment by kernc** [comment]
No code. Can't help. Please see [CONTRIBUTING.md#Issues](https://github.com/kernc/backtesting.py/blob/master/CONTRIBUTING.md#issues).
