### ISSUE TITLE
Both long and short resting orders should stay in the market

### ISSUE THREAD

**Issue by javabrew** [kernc/backtesting.py#967]
With the following snippet in the next () method

if not self.position:
            self.buy(size = 20, stop=buy_stop_entry)
            self.sell(size = 20, stop=sell_stop_entry)

the long order seems to disappear after the sell short order is created (not even executed.
Tried creating Backtest with hedging=TRUE and got the same behavior.
Note that buy_stop_entry and sell_stop_entry may dynamically change from bar to bar.

### Expected Behavior
Both orders should stay in the market until executed or cancelled

### Steps to Reproduce
    print (self.orders) and observe orders disappear

1.
2.
3.

```python

if not self.position:
          self.buy(size = 20, stop=buy_stop_entry)
          self.sell(size = 20, stop=sell_stop_entry)

```

### Additional info

- Backtesting version: 0.?.?   
- `bokeh.__version__`:
- OS:

**Comment by kernc** [comment]
Besides `hedging=True`, you also need [`exclusive_orders=False`](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Backtest).
