### ISSUE TITLE
Buy asset for a fixed amount of cash

### ISSUE THREAD

**Issue by snapo** [kernc/backtesting.py#97]
Hi, 
First of all thanks for the library... but after starting having already my first issue and dont know if it is even implemented.
In the crypto world you can buy partial currencys like 0.22 BTC.
What i did try now is a simple Dollar Cost Average strategy (buy 10$ BTC per close) but faced the issue that you can not define a fixed USD ammount for the self.buy() or is there another way you can think of?

Thanks in advance for an answer

**Comment by kernc** [comment]
The current version doesn't support position sizing and instead goes all in all the time. 🤪

If you care to look, #47 proposes a set of changes that allow for variable order sizes. Note, it's as yet incomplete, has a few remaining bugs, and, in particular, doesn't support sub-unit sizing. Meaning: If you're trading Bitcoin, you need to trade in whole integer units, e.g. satoshis. Then, the question of spending $10 becomes a simple matter of:
```py
self.buy(size=10 // self.data.Close)  # $10 divided by unit price gives number of units 
```

**Comment by snapo** [comment]
Pretty cool #47 will for sure try it out... thanks for the answer.
