### ISSUE TITLE
Broken Link on Homepage

### ISSUE THREAD

**Issue by DominikBerger01** [kernc/backtesting.py#984]
<img width="1414" alt="Screenshot 2023-05-14 at 10 45 18" src="https://github.com/kernc/backtesting.py/assets/41689534/edbf89de-0869-4f61-81e1-19e97d53ff35">

Looks like this repo has been moved. 
<img width="1059" alt="Screenshot 2023-05-14 at 10 53 18" src="https://github.com/kernc/backtesting.py/assets/41689534/99124382-a6df-473d-9248-d2505949f182">

These are the new links I have found:
Repo: https://github.com/TA-Lib/ta-lib-python
Dokumentation: http://ta-lib.github.io/ta-lib-python/

Kind regards, 
Dominik Berger

**Comment by kernc** [comment]
Fixed in https://github.com/kernc/backtesting.py/issues/985. Thanks @DominikBerger01!
