### ISSUE TITLE
How can I maximize two parameters?

### ISSUE THREAD

**Issue by naheshi** [kernc/backtesting.py#988]
How can I maximize two parameters in optimization ? for example I want to maximize Return and Winrate

**Comment by naheshi** [comment]
I was able to solve it :)

**Comment by efeint01** [comment]
how did you fix that?

**Comment by kernc** [comment]
See e.g. https://github.com/kernc/backtesting.py/issues/256, https://github.com/kernc/backtesting.py/issues/978, ...
